import {Country} from '../../model/Country';

export const DATASAMERICAVI: Country[] = [
  {
    answer: ['Colombia', 'Bolivia', 'Guyana', 'Argentina'],
    correct: 3,
    id: 'AR',
    index: 9,
    name: 'Argentina',
    uri: require('../../assets/flagpng/ar.png'),
  },
  {
    answer: ['Ecuador', 'Bolivia', 'Venezuela', 'Guyane thuộc Pháp'],
    correct: 1,
    id: 'BO',
    index: 28,
    name: 'Bolivia',
    uri: require('../../assets/flagpng/bo.png'),
  },
  {
    answer: ['Uruguay', 'Colombia', 'Venezuela', 'Brazil'],
    correct: 3,
    id: 'BR',
    index: 29,
    name: 'Brazil',
    uri: require('../../assets/flagpng/br.png'),
  },
  {
    answer: ['Chile', 'Uruguay', 'Venezuela', 'Brazil'],
    correct: 0,
    id: 'CL',
    index: 44,
    name: 'Chile',
    uri: require('../../assets/flagpng/cl.png'),
  },
  {
    answer: ['Colombia', 'Venezuela', 'Guyane thuộc Pháp', 'Argentina'],
    correct: 0,
    id: 'CO',
    index: 47,
    name: 'Colombia',
    uri: require('../../assets/flagpng/co.png'),
  },
  {
    answer: ['Colombia', 'Venezuela', 'Guyane thuộc Pháp', 'Ecuador'],
    correct: 3,
    id: 'EC',
    index: 61,
    name: 'Ecuador',
    uri: require('../../assets/flagpng/ec.png'),
  },
  // {
  //   answer: [
  //     'Venezuela',
  //     'Quần đảo Falkland',
  //     'Argentina',
  //     'Quần đảo Falkland',
  //   ],
  //   correct: 3,
  //   id: 'FK',
  //   index: 71,
  //   name: 'Quần đảo Falkland',
  //   uri: require('../../assets/flagpng/fk.png'),
  // },
  // {
  //   answer: ['Uruguay', 'Venezuela', 'Guyane thuộc Pháp', 'Ecuador'],
  //   correct: 2,
  //   id: 'GF',
  //   index: 83,
  //   name: 'Guyane thuộc Pháp',
  //   uri: require('../../assets/flagpng/gf.png'),
  // },
  {
    answer: ['Chile', 'Peru', 'Venezuela', 'Guyana'],
    correct: 3,
    id: 'GY',
    index: 97,
    name: 'Guyana',
    uri: require('../../assets/flagpng/gy.png'),
  },
  {
    answer: ['Peru', 'Venezuela', 'Brazil', 'Uruguay'],
    correct: 0,
    id: 'PE',
    index: 177,
    name: 'Peru',
    uri: require('../../assets/flagpng/pe.png'),
  },
  {
    answer: ['Paraguay', 'Bolivia', 'Guyane thuộc Pháp', 'Venezuela'],
    correct: 0,
    id: 'PY',
    index: 189,
    name: 'Paraguay',
    uri: require('../../assets/flagpng/py.png'),
  },
  {
    answer: ['Venezuela', 'Suriname', 'Ecuador', 'Peru'],
    correct: 1,
    id: 'SR',
    index: 210,
    name: 'Suriname',
    uri: require('../../assets/flagpng/sr.png'),
  },
  {
    answer: ['Uruguay', 'Chile', 'Venezuela', 'Paraguay'],
    correct: 0,
    id: 'UY',
    index: 236,
    name: 'Uruguay',
    uri: require('../../assets/flagpng/uy.png'),
  },
  {
    answer: ['Paraguay', 'Venezuela', 'Uruguay', 'Chile'],
    correct: 1,
    id: 'VE',
    index: 240,
    name: 'Venezuela',
    uri: require('../../assets/flagpng/ve.png'),
  },
];

export const DATASAMERICA: Country[] = [
  {
    answer: [
      'Bolivia (Plurinational State of)',
      'Argentina',
      'Peru',
      'Venezuela (Bolivarian Republic of)',
    ],
    correct: 1,
    id: 'AR',
    index: 6,
    name: 'Argentina',
    uri: require('../../assets/flagpng/ar.png'),
  },
  {
    answer: [
      'Argentina',
      'Peru',
      'Venezuela (Bolivarian Republic of)',
      'Bolivia (Plurinational State of)',
    ],
    correct: 3,
    id: 'BO',
    index: 20,
    name: 'Bolivia (Plurinational State of)',
    uri: require('../../assets/flagpng/bo.png'),
  },
  {
    answer: [
      'Ecuador',
      'Brazil',
      'Bolivia (Plurinational State of)',
      'Venezuela (Bolivarian Republic of)',
    ],
    correct: 1,
    id: 'BR',
    index: 23,
    name: 'Brazil',
    uri: require('../../assets/flagpng/br.png'),
  },
  {
    answer: ['Venezuela (Bolivarian Republic of)', 'Uruguay', 'Chile', 'Paraguay'],
    correct: 2,
    id: 'CL',
    index: 34,
    name: 'Chile',
    uri: require('../../assets/flagpng/cl.png'),
  },
  {
    answer: [
      'Brazil',
      'Paraguay',
      'Colombia',
      'Venezuela (Bolivarian Republic of)',
    ],
    correct: 2,
    id: 'CO',
    index: 36,
    name: 'Colombia',
    uri: require('../../assets/flagpng/co.png'),
  },
  {
    answer: [
      'Suriname',
      'Ecuador',
      'Venezuela (Bolivarian Republic of)',
      'Argentina',
    ],
    correct: 1,
    id: 'EC',
    index: 50,
    name: 'Ecuador',
    uri: require('../../assets/flagpng/ec.png'),
  },
  {
    answer: [
      'Venezuela (Bolivarian Republic of)',
      'Paraguay',
      'Colombia',
      'Guyana',
    ],
    correct: 3,
    id: 'GY',
    index: 71,
    name: 'Guyana',
    uri: require('../../assets/flagpng/gy.png'),
  },
  {
    answer: [
      'Ecuador',
      'Paraguay',
      'Venezuela (Bolivarian Republic of)',
      'Bolivia (Plurinational State of)',
    ],
    correct: 1,
    id: 'PY',
    index: 135,
    name: 'Paraguay',
    uri: require('../../assets/flagpng/py.png'),
  },
  {
    answer: ['Chile', 'Paraguay', 'Peru', 'Venezuela (Bolivarian Republic of)'],
    correct: 2,
    id: 'PE',
    index: 136,
    name: 'Peru',
    uri: require('../../assets/flagpng/pe.png'),
  },
  {
    answer: [
      'Peru',
      'Venezuela (Bolivarian Republic of)',
      'Bolivia (Plurinational State of)',
      'Suriname',
    ],
    correct: 3,
    id: 'SR',
    index: 165,
    name: 'Suriname',
    uri: require('../../assets/flagpng/sr.png'),
  },
  {
    answer: [
      'Uruguay',
      'Venezuela (Bolivarian Republic of)',
      'Chile',
      'Paraguay',
    ],
    correct: 0,
    id: 'UY',
    index: 185,
    name: 'Uruguay',
    uri: require('../../assets/flagpng/uy.png'),
  },
  {
    answer: [
      'Venezuela (Bolivarian Republic of)',
      'Bolivia (Plurinational State of)',
      'Guyana',
      'Uruguay',
    ],
    correct: 0,
    id: 'VE',
    index: 188,
    name: 'Venezuela (Bolivarian Republic of)',
    uri: require('../../assets/flagpng/ve.png'),
  },
];
