export type country = {
  id: string;
  name: string;
  uri: any;
  answer: string[];
  correct: number;
  index: number;
};
export const DATANAMERICA: country[] = [
  {
    id: 'AG',
    name: 'Antigua và Barbuda',
    uri: "require('../../assets/flagpng/AG.png)",
    answer: ['Antigua và Barbuda', 'Mỹ (Hoa Kỳ)', 'Jamaica', 'Canada'],
    correct: 0,
    index: 3,
  },
  {
    id: 'AI',
    name: 'Anguilla',
    uri: "require('../../assets/flagpng/AI.png)",
    answer: ['Mỹ (Hoa Kỳ)', 'Haiti', 'Aruba', 'Anguilla'],
    correct: 3,
    index: 4,
  },
  {
    id: 'AW',
    name: 'Aruba',
    uri: "require('../../assets/flagpng/AW.png)",
    answer: ['Antigua và Barbuda', 'Aruba', 'Mỹ (Hoa Kỳ)', 'Saint Lucia'],
    correct: 1,
    index: 13,
  },
  {
    id: 'BB',
    name: 'Barbados',
    uri: "require('../../assets/flagpng/BB.png)",
    answer: ['Aruba', 'Barbados', 'Quần đảo Virgin', 'Nicaragua'],
    correct: 1,
    index: 17,
  },
  {
    id: 'BL',
    name: 'Saint Barthélemy',
    uri: "require('../../assets/flagpng/BL.png)",
    answer: [
      'Guatemala',
      'Cộng hòa Dominica',
      'Saint Barthélemy',
      'Trinidad và Tobago',
    ],
    correct: 2,
    index: 25,
  },
  {
    id: 'BM',
    name: 'Bermuda',
    uri: "require('../../assets/flagpng/BM.png)",
    answer: ['Greenland', 'Saint Pierre và Miquelon', 'Belize', 'Bermuda'],
    correct: 3,
    index: 26,
  },
  {
    id: 'BS',
    name: 'Bahamas',
    uri: "require('../../assets/flagpng/BS.png)",
    answer: ['Grenada', 'Bahamas', 'Saint Barthélemy', 'El Salvador'],
    correct: 1,
    index: 30,
  },
  {
    id: 'BZ',
    name: 'Belize',
    uri: "require('../../assets/flagpng/BZ.png)",
    answer: ['Belize', 'Saint Barthélemy', 'Mỹ (Hoa Kỳ)', 'Saint Martin'],
    correct: 0,
    index: 35,
  },
  {
    id: 'CA',
    name: 'Canada',
    uri: "require('../../assets/flagpng/CA.png)",
    answer: ['Mỹ (Hoa Kỳ)', 'Cộng hòa Dominica', 'Canada', 'Jamaica'],
    correct: 2,
    index: 36,
  },
  {
    id: 'CR',
    name: 'Costa Rica',
    uri: "require('../../assets/flagpng/CR.png)",
    answer: ['Saint Pierre và Miquelon', 'Bermuda', 'Nicaragua', 'Costa Rica'],
    correct: 3,
    index: 48,
  },
  {
    id: 'CU',
    name: 'Cuba',
    uri: "require('../../assets/flagpng/CU.png)",
    answer: ['Aruba', 'Cuba', 'Haiti', 'Quần đảo Virgin'],
    correct: 1,
    index: 49,
  },
  {
    id: 'CW',
    name: 'Curaçao',
    uri: "require('../../assets/flagpng/CW.png)",
    answer: [
      'Saint Kitts và Nevis',
      'Curaçao',
      'Saint Vincent và Grenadines',
      'Curaçao',
    ],
    correct: 1,
    index: 51,
  },
  {
    id: 'DM',
    name: 'Dominica',
    uri: "require('../../assets/flagpng/DM.png)",
    answer: ['Cộng hòa Dominica', 'Dominica', 'Jamaica', 'Quần đảo Virgin'],
    correct: 1,
    index: 58,
  },
  {
    id: 'DO',
    name: 'Cộng hòa Dominica',
    uri: "require('../../assets/flagpng/DO.png)",
    answer: [
      'Quần đảo Turks và Caicos',
      'Cộng hòa Dominica',
      'Barbados',
      'Honduras',
    ],
    correct: 1,
    index: 59,
  },
  {
    id: 'GD',
    name: 'Grenada',
    uri: "require('../../assets/flagpng/GD.png)",
    answer: ['Grenada', 'Haiti', 'Saint Pierre và Miquelon', 'Cuba'],
    correct: 0,
    index: 81,
  },
  {
    id: 'GL',
    name: 'Greenland',
    uri: "require('../../assets/flagpng/GL.png)",
    answer: [
      'Saint Lucia',
      'Saint Vincent và Grenadines',
      'Greenland',
      'Dominica',
    ],
    correct: 2,
    index: 87,
  },
  {
    id: 'GP',
    name: 'Guadeloupe',
    uri: "require('../../assets/flagpng/GP.png)",
    answer: [
      'Saint Pierre và Miquelon',
      'Guadeloupe',
      'Grenada',
      'Cộng hòa Dominica',
    ],
    correct: 1,
    index: 90,
  },
  {
    id: 'GT',
    name: 'Guatemala',
    uri: "require('../../assets/flagpng/GT.png)",
    answer: ['Honduras', 'Guatemala', 'Bermuda', 'Panama'],
    correct: 1,
    index: 94,
  },
  {
    id: 'HN',
    name: 'Honduras',
    uri: "require('../../assets/flagpng/HN.png)",
    answer: [
      'Antigua và Barbuda',
      'Honduras',
      'Saint Martin',
      'Saint Pierre và Miquelon',
    ],
    correct: 1,
    index: 100,
  },
  {
    id: 'HT',
    name: 'Haiti',
    uri: "require('../../assets/flagpng/HT.png)",
    answer: ['Saint Vincent và Grenadines', 'Haiti', 'Curaçao', 'Saint Martin'],
    correct: 1,
    index: 102,
  },
  {
    id: 'JM',
    name: 'Jamaica',
    uri: "require('../../assets/flagpng/JM.png)",
    answer: ['Jamaica', 'Jamaica', 'Quần đảo Virgin', 'Cộng hòa Dominica'],
    correct: 1,
    index: 115,
  },
  {
    id: 'KN',
    name: 'Saint Kitts và Nevis',
    uri: "require('../../assets/flagpng/KN.png)",
    answer: ['El Salvador', 'Nicaragua', 'Bahamas', 'Saint Kitts và Nevis'],
    correct: 3,
    index: 123,
  },
  {
    id: 'KY',
    name: 'Quần đảo Cayman',
    uri: "require('../../assets/flagpng/KY.png)",
    answer: [
      'Anguilla',
      'Saint Kitts và Nevis',
      'Quần đảo Cayman',
      'El Salvador',
    ],
    correct: 2,
    index: 127,
  },
  {
    id: 'LC',
    name: 'Saint Lucia',
    uri: "require('../../assets/flagpng/LC.png)",
    answer: [
      'Saint Pierre và Miquelon',
      'Curaçao',
      'Saint Lucia',
      'Saint Lucia',
    ],
    correct: 2,
    index: 131,
  },
  {
    id: 'MF',
    name: 'Saint Martin',
    uri: "require('../../assets/flagpng/MF.png)",
    answer: ['Haiti', 'Sint Maarten', 'Saint Martin', 'Belize'],
    correct: 2,
    index: 144,
  },
  {
    id: 'MQ',
    name: 'Martinique',
    uri: "require('../../assets/flagpng/MQ.png)",
    answer: ['Quần đảo Virgin', 'Costa Rica', 'Martinique', 'Greenland'],
    correct: 2,
    index: 153,
  },
  {
    id: 'MS',
    name: 'Montserrat',
    uri: "require('../../assets/flagpng/MS.png)",
    answer: ['Montserrat', 'Belize', 'Panama', 'Martinique'],
    correct: 0,
    index: 155,
  },
  {
    id: 'MX',
    name: 'Mexico',
    uri: "require('../../assets/flagpng/MX.png)",
    answer: ['Saint Martin', 'Mexico', 'Belize', 'Mỹ (Hoa Kỳ)'],
    correct: 1,
    index: 160,
  },
  {
    id: 'NI',
    name: 'Nicaragua',
    uri: "require('../../assets/flagpng/NI.png)",
    answer: ['Saint Martin', 'Saint Pierre và Miquelon', 'Belize', 'Nicaragua'],
    correct: 3,
    index: 168,
  },
  {
    id: 'PA',
    name: 'Panama',
    uri: "require('../../assets/flagpng/PA.png)",
    answer: ['Puerto Rico', 'Panama', 'Barbados', 'Greenland'],
    correct: 1,
    index: 176,
  },
  {
    id: 'PM',
    name: 'Saint Pierre và Miquelon',
    uri: "require('../../assets/flagpng/PM.png)",
    answer: [
      'Cộng hòa Dominica',
      'Saint Pierre và Miquelon',
      'Puerto Rico',
      'Saint Martin',
    ],
    correct: 1,
    index: 183,
  },
  {
    id: 'PR',
    name: 'Puerto Rico',
    uri: "require('../../assets/flagpng/PR.png)",
    answer: [
      'Saint Vincent và Grenadines',
      'Anguilla',
      'Puerto Rico',
      'Guatemala',
    ],
    correct: 2,
    index: 185,
  },
  {
    id: 'SV',
    name: 'El Salvador',
    uri: "require('../../assets/flagpng/SV.png)",
    answer: ['Saint Lucia', 'Barbados', 'El Salvador', 'Sint Maarten'],
    correct: 2,
    index: 213,
  },
  {
    id: 'SX',
    name: 'Sint Maarten',
    uri: "require('../../assets/flagpng/SX.png)",
    answer: [
      'Quần đảo Turks và Caicos',
      'Sint Maarten',
      'Saint Kitts và Nevis',
      'Saint Barthélemy',
    ],
    correct: 1,
    index: 214,
  },
  {
    id: 'TC',
    name: 'Quần đảo Turks và Caicos',
    uri: "require('../../assets/flagpng/TC.png)",
    answer: [
      'Canada',
      'Guatemala',
      'Quần đảo Turks và Caicos',
      'Quần đảo Virgin',
    ],
    correct: 2,
    index: 217,
  },
  {
    id: 'TT',
    name: 'Trinidad và Tobago',
    uri: "require('../../assets/flagpng/TT.png)",
    answer: [
      'Saint Vincent và Grenadines',
      'Canada',
      'Trinidad và Tobago',
      'Jamaica',
    ],
    correct: 2,
    index: 229,
  },
  {
    id: 'US',
    name: 'Mỹ (Hoa Kỳ)',
    uri: "require('../../assets/flagpng/US.png)",
    answer: ['Mỹ (Hoa Kỳ)', 'Martinique', 'Puerto Rico', 'Barbados'],
    correct: 0,
    index: 235,
  },
  {
    id: 'VC',
    name: 'Saint Vincent và Grenadines',
    uri: "require('../../assets/flagpng/VC.png)",
    answer: [
      'Guatemala',
      'Cộng hòa Dominica',
      'Panama',
      'Saint Vincent và Grenadines',
    ],
    correct: 3,
    index: 239,
  },
  {
    id: 'VG',
    name: 'Quần đảo Virgin',
    uri: "require('../../assets/flagpng/VG.png)",
    answer: [
      'Quần đảo Virgin',
      'Saint Barthélemy',
      'Martinique',
      'Mỹ (Hoa Kỳ)',
    ],
    correct: 0,
    index: 241,
  },
  {
    id: 'VI',
    name: 'Quần đảo Virgin',
    uri: "require('../../assets/flagpng/VI.png)",
    answer: ['Mỹ (Hoa Kỳ)', 'Bahamas', 'Montserrat', 'Quần đảo Virgin'],
    correct: 3,
    index: 242,
  },
];
