export type country = {
  id: string;
  name: string;
  uri: any;
  answer: string[];
  correct: number;
  index: number;
};
export const DATAASIA: country[] = [
  {
    id: 'AE',
    name: 'Các tiểu vương quốc Ả Rập Thống nhất',
    uri: "require('../../assets/flagpng/AE.png)",
    answer: [
      'Maldives',
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 1,
    index: 1,
  },
  {
    id: 'AF',
    name: 'Afghanistan',
    uri: "require('../../assets/flagpng/AF.png)",
    answer: ['Nhật Bản', 'Tajikistan', 'Bangladesh', 'Afghanistan'],
    correct: 3,
    index: 2,
  },
  {
    id: 'AM',
    name: 'Armenia',
    uri: "require('../../assets/flagpng/AM.png)",
    answer: ['Singapore', 'Armenia', 'Indonesia', 'Kyrgyzstan'],
    correct: 1,
    index: 6,
  },
  {
    id: 'AZ',
    name: 'Azerbaijan',
    uri: "require('../../assets/flagpng/AZ.png)",
    answer: ['Triều Tiên', 'Singapore', 'Azerbaijan', 'Azerbaijan'],
    correct: 3,
    index: 15,
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    uri: "require('../../assets/flagpng/BD.png)",
    answer: ['Nga', 'Hồng Kông', 'Triều Tiên', 'Bangladesh'],
    correct: 3,
    index: 18,
  },
  {
    id: 'BH',
    name: 'Bahrain',
    uri: "require('../../assets/flagpng/BH.png)",
    answer: ['Li-băng', 'Bahrain', 'Nepal', 'Trung Quốc'],
    correct: 1,
    index: 22,
  },
  {
    id: 'BN',
    name: 'Brunei Darussalam',
    uri: "require('../../assets/flagpng/BN.png)",
    answer: ['Brunei Darussalam', 'Lãnh thổ Đảo Christmas', 'Iran', 'Syria'],
    correct: 0,
    index: 27,
  },
  {
    id: 'BT',
    name: 'Bhutan',
    uri: "require('../../assets/flagpng/BT.png)",
    answer: ['Armenia', 'Bhutan', 'Li-băng', 'Palestine'],
    correct: 1,
    index: 31,
  },
  {
    id: 'CC',
    name: 'Quần đảo Cocos',
    uri: "require('../../assets/flagpng/CC.png)",
    answer: ['Georgia', 'Malaysia', 'Nepal', 'Quần đảo Cocos'],
    correct: 3,
    index: 37,
  },
  {
    id: 'CN',
    name: 'Trung Quốc',
    uri: "require('../../assets/flagpng/CN.png)",
    answer: ['Georgia', 'Trung Quốc', 'Sri Lanka', 'Việt Nam'],
    correct: 1,
    index: 46,
  },
  {
    id: 'CX',
    name: 'Lãnh thổ Đảo Christmas',
    uri: "require('../../assets/flagpng/CX.png)",
    answer: ['Lào', 'Lãnh thổ Đảo Christmas', 'Turkmenistan', 'Trung Quốc'],
    correct: 1,
    index: 52,
  },
  {
    id: 'GE',
    name: 'Georgia',
    uri: "require('../../assets/flagpng/GE.png)",
    answer: ['Oman', 'Georgia', 'Bangladesh', 'Nhật Bản'],
    correct: 1,
    index: 82,
  },
  {
    id: 'HK',
    name: 'Hồng Kông',
    uri: "require('../../assets/flagpng/HK.png)",
    answer: ['Israel', 'Thổ Nhĩ Kỳ', 'Nhật Bản', 'Hồng Kông'],
    correct: 3,
    index: 98,
  },
  {
    id: 'ID',
    name: 'Indonesia',
    uri: "require('../../assets/flagpng/ID.png)",
    answer: ['Sri Lanka', 'Indonesia', 'Thổ Nhĩ Kỳ', 'Georgia'],
    correct: 1,
    index: 104,
  },
  {
    id: 'IL',
    name: 'Israel',
    uri: "require('../../assets/flagpng/IL.png)",
    answer: ['Israel', 'Mongolia', 'Bhutan', 'Yemen'],
    correct: 0,
    index: 106,
  },
  {
    id: 'IN',
    name: 'Ấn Độ',
    uri: "require('../../assets/flagpng/IN.png)",
    answer: ['Ấn Độ', 'Kazakhstan', 'Lãnh thổ Đảo Christmas', 'Yemen'],
    correct: 0,
    index: 108,
  },
  {
    id: 'IO',
    name: 'Lãnh thổ Anh tại Ấn Độ Dương',
    uri: "require('../../assets/flagpng/IO.png)",
    answer: [
      'Hồng Kông',
      'Nepal',
      'Kyrgyzstan',
      'Lãnh thổ Anh tại Ấn Độ Dương',
    ],
    correct: 3,
    index: 109,
  },
  {
    id: 'IQ',
    name: 'Iraq',
    uri: "require('../../assets/flagpng/IQ.png)",
    answer: ['Kazakhstan', 'Iraq', 'Thailand', 'Israel'],
    correct: 1,
    index: 110,
  },
  {
    id: 'IR',
    name: 'Iran',
    uri: "require('../../assets/flagpng/IR.png)",
    answer: ['Iran', 'Ấn Độ', 'Mongolia', 'Việt Nam'],
    correct: 0,
    index: 111,
  },
  {
    id: 'JO',
    name: 'Jordan',
    uri: "require('../../assets/flagpng/JO.png)",
    answer: ['Jordan', 'Thailand', 'Armenia', 'Myanmar'],
    correct: 0,
    index: 116,
  },
  {
    id: 'JP',
    name: 'Nhật Bản',
    uri: "require('../../assets/flagpng/JP.png)",
    answer: ['Campuchia', 'Israel', 'Nhật Bản', 'Nepal'],
    correct: 2,
    index: 117,
  },
  {
    id: 'KG',
    name: 'Kyrgyzstan',
    uri: "require('../../assets/flagpng/KG.png)",
    answer: ['Hồng Kông', 'Nga', 'Kyrgyzstan', 'Malaysia'],
    correct: 2,
    index: 119,
  },
  {
    id: 'KH',
    name: 'Campuchia',
    uri: "require('../../assets/flagpng/KH.png)",
    answer: ['Indonesia', 'Jordan', 'Qatar', 'Campuchia'],
    correct: 3,
    index: 120,
  },
  {
    id: 'KP',
    name: 'Triều Tiên',
    uri: "require('../../assets/flagpng/KP.png)",
    answer: ['Maldives', 'Triều Tiên', 'Đài Loan', 'Indonesia'],
    correct: 1,
    index: 124,
  },
  {
    id: 'KR',
    name: 'Hàn Quốc',
    uri: "require('../../assets/flagpng/KR.png)",
    answer: ['Brunei Darussalam', 'Turkmenistan', 'Li-băng', 'Hàn Quốc'],
    correct: 3,
    index: 125,
  },
  {
    id: 'KW',
    name: 'Kuwait',
    uri: "require('../../assets/flagpng/KW.png)",
    answer: ['Ấn Độ', 'Qatar', 'Kuwait', 'Jordan'],
    correct: 2,
    index: 126,
  },
  {
    id: 'KZ',
    name: 'Kazakhstan',
    uri: "require('../../assets/flagpng/KZ.png)",
    answer: ['Lãnh thổ Đảo Christmas', 'Kazakhstan', 'Uzbekistan', 'Iran'],
    correct: 1,
    index: 128,
  },
  {
    id: 'LA',
    name: 'Lào',
    uri: "require('../../assets/flagpng/LA.png)",
    answer: ['Hồng Kông', 'Đài Loan', 'Hàn Quốc', 'Lào'],
    correct: 3,
    index: 129,
  },
  {
    id: 'LB',
    name: 'Li-băng',
    uri: "require('../../assets/flagpng/LB.png)",
    answer: ['Pakistan', 'Li-băng', 'Bahrain', 'Triều Tiên'],
    correct: 1,
    index: 130,
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    uri: "require('../../assets/flagpng/LK.png)",
    answer: ['Bangladesh', 'Sri Lanka', 'Triều Tiên', 'Singapore'],
    correct: 1,
    index: 133,
  },
  {
    id: 'MM',
    name: 'Myanmar',
    uri: "require('../../assets/flagpng/MM.png)",
    answer: ['Myanmar', 'Indonesia', 'Kuwait', 'Philippines'],
    correct: 0,
    index: 149,
  },
  {
    id: 'MN',
    name: 'Mongolia',
    uri: "require('../../assets/flagpng/MN.png)",
    answer: ['Quần đảo Cocos', 'Kazakhstan', 'Nga', 'Mongolia'],
    correct: 3,
    index: 150,
  },
  {
    id: 'MO',
    name: 'Macao',
    uri: "require('../../assets/flagpng/MO.png)",
    answer: ['Mongolia', 'Macao', 'Oman', 'Bhutan'],
    correct: 1,
    index: 151,
  },
  {
    id: 'MV',
    name: 'Maldives',
    uri: "require('../../assets/flagpng/MV.png)",
    answer: ['Quần đảo Cocos', 'Iran', 'Maldives', 'Tajikistan'],
    correct: 2,
    index: 158,
  },
  {
    id: 'MY',
    name: 'Malaysia',
    uri: "require('../../assets/flagpng/MY.png)",
    answer: ['Uzbekistan', 'Myanmar', 'Israel', 'Malaysia'],
    correct: 3,
    index: 161,
  },
  {
    id: 'NP',
    name: 'Nepal',
    uri: "require('../../assets/flagpng/NP.png)",
    answer: ['Trung Quốc', 'Thổ Nhĩ Kỳ', 'Iran', 'Nepal'],
    correct: 3,
    index: 171,
  },
  {
    id: 'OM',
    name: 'Oman',
    uri: "require('../../assets/flagpng/OM.png)",
    answer: ['Oman', 'Lào', 'Oman', 'Azerbaijan'],
    correct: 0,
    index: 175,
  },
  {
    id: 'PH',
    name: 'Philippines',
    uri: "require('../../assets/flagpng/PH.png)",
    answer: ['Philippines', 'Turkmenistan', 'Afghanistan', 'Kazakhstan'],
    correct: 0,
    index: 180,
  },
  {
    id: 'PK',
    name: 'Pakistan',
    uri: "require('../../assets/flagpng/PK.png)",
    answer: ['Uzbekistan', 'Pakistan', 'Israel', 'Kyrgyzstan'],
    correct: 1,
    index: 181,
  },
  {
    id: 'PS',
    name: 'Palestine',
    uri: "require('../../assets/flagpng/PS.png)",
    answer: ['Palestine', 'Iran', 'Quần đảo Cocos', 'Turkmenistan'],
    correct: 0,
    index: 186,
  },
  {
    id: 'QA',
    name: 'Qatar',
    uri: "require('../../assets/flagpng/QA.png)",
    answer: ['Singapore', 'Hàn Quốc', 'Lãnh thổ Đảo Christmas', 'Qatar'],
    correct: 3,
    index: 190,
  },
  {
    id: 'RU',
    name: 'Nga',
    uri: "require('../../assets/flagpng/RU.png)",
    answer: ['Azerbaijan', 'Nepal', 'Nga', 'Iran'],
    correct: 2,
    index: 194,
  },
  {
    id: 'SA',
    name: 'Ả Rập Xê Út',
    uri: "require('../../assets/flagpng/SA.png)",
    answer: ['Ả Rập Xê Út', 'Armenia', 'Macao', 'Nepal'],
    correct: 0,
    index: 196,
  },
  {
    id: 'SG',
    name: 'Singapore',
    uri: "require('../../assets/flagpng/SG.png)",
    answer: ['Afghanistan', 'Jordan', 'Singapore', 'Turkmenistan'],
    correct: 2,
    index: 201,
  },
  {
    id: 'SY',
    name: 'Syria',
    uri: "require('../../assets/flagpng/SY.png)",
    answer: ['Israel', 'Kuwait', 'Syria', 'Nga'],
    correct: 2,
    index: 215,
  },
  {
    id: 'TH',
    name: 'Thailand',
    uri: "require('../../assets/flagpng/TH.png)",
    answer: ['Myanmar', 'Thổ Nhĩ Kỳ', 'Ấn Độ', 'Thailand'],
    correct: 3,
    index: 221,
  },
  {
    id: 'TJ',
    name: 'Tajikistan',
    uri: "require('../../assets/flagpng/TJ.png)",
    answer: ['Qatar', 'Nhật Bản', 'Tajikistan', 'Bahrain'],
    correct: 2,
    index: 222,
  },
  {
    id: 'TM',
    name: 'Turkmenistan',
    uri: "require('../../assets/flagpng/TM.png)",
    answer: ['Hồng Kông', 'Turkmenistan', 'Campuchia', 'Qatar'],
    correct: 1,
    index: 225,
  },
  {
    id: 'TR',
    name: 'Thổ Nhĩ Kỳ',
    uri: "require('../../assets/flagpng/TR.png)",
    answer: ['Việt Nam', 'Jordan', 'Afghanistan', 'Thổ Nhĩ Kỳ'],
    correct: 3,
    index: 228,
  },
  {
    id: 'TW',
    name: 'Đài Loan',
    uri: "require('../../assets/flagpng/TW.png)",
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Đài Loan',
      'Campuchia',
    ],
    correct: 2,
    index: 231,
  },
  {
    id: 'UZ',
    name: 'Uzbekistan',
    uri: "require('../../assets/flagpng/UZ.png)",
    answer: ['Lãnh thổ Anh tại Ấn Độ Dương', 'Uzbekistan', 'Nepal', 'Mongolia'],
    correct: 1,
    index: 237,
  },
  {
    id: 'VN',
    name: 'Việt Nam',
    uri: "require('../../assets/flagpng/VN.png)",
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Kuwait',
      'Thổ Nhĩ Kỳ',
    ],
    correct: 1,
    index: 243,
  },
  {
    id: 'YE',
    name: 'Yemen',
    uri: "require('../../assets/flagpng/YE.png)",
    answer: ['Qatar', 'Jordan', 'Yemen', 'Azerbaijan'],
    correct: 2,
    index: 248,
  },
];
