import {Country} from '../../model/Country';

export const DATANAMERICAVI: Country[] = [
  {
    answer: ['Antigua và Barbuda', 'Mỹ (Hoa Kỳ)', 'Jamaica', 'Canada'],
    correct: 0,
    id: 'AG',
    index: 3,
    name: 'Antigua và Barbuda',
    uri: require('../../assets/flagpng/ag.png'),
  },
  // {
  //   answer: ['Mỹ (Hoa Kỳ)', 'Haiti', 'Aruba', 'Anguilla'],
  //   correct: 3,
  //   id: 'AI',
  //   index: 4,
  //   name: 'Anguilla',
  //   uri: require('../../assets/flagpng/ai.png'),
  // },
  // {
  //   answer: ['Antigua và Barbuda', 'Aruba', 'Mỹ (Hoa Kỳ)', 'Saint Lucia'],
  //   correct: 1,
  //   id: 'AW',
  //   index: 13,
  //   name: 'Aruba',
  //   uri: require('../../assets/flagpng/aw.png'),
  // },
  {
    answer: ['Aruba', 'Barbados', 'Quần đảo Virgin', 'Nicaragua'],
    correct: 1,
    id: 'BB',
    index: 17,
    name: 'Barbados',
    uri: require('../../assets/flagpng/bb.png'),
  },
  // {
  //   answer: [
  //     'Guatemala',
  //     'Cộng hòa Dominica',
  //     'Saint Barthélemy',
  //     'Trinidad và Tobago',
  //   ],
  //   correct: 2,
  //   id: 'BL',
  //   index: 25,
  //   name: 'Saint Barthélemy',
  //   uri: require('../../assets/flagpng/bl.png'),
  // },
  // {
  //   answer: ['Greenland', 'Saint Pierre và Miquelon', 'Belize', 'Bermuda'],
  //   correct: 3,
  //   id: 'BM',
  //   index: 26,
  //   name: 'Bermuda',
  //   uri: require('../../assets/flagpng/bm.png'),
  // },
  {
    answer: ['Grenada', 'Bahamas', 'Saint Barthélemy', 'El Salvador'],
    correct: 1,
    id: 'BS',
    index: 30,
    name: 'Bahamas',
    uri: require('../../assets/flagpng/bs.png'),
  },
  {
    answer: ['Belize', 'Saint Barthélemy', 'Mỹ (Hoa Kỳ)', 'Saint Martin'],
    correct: 0,
    id: 'BZ',
    index: 35,
    name: 'Belize',
    uri: require('../../assets/flagpng/bz.png'),
  },
  {
    answer: ['Mỹ (Hoa Kỳ)', 'Cộng hòa Dominica', 'Canada', 'Jamaica'],
    correct: 2,
    id: 'CA',
    index: 36,
    name: 'Canada',
    uri: require('../../assets/flagpng/ca.png'),
  },
  {
    answer: ['Saint Pierre và Miquelon', 'Bermuda', 'Nicaragua', 'Costa Rica'],
    correct: 3,
    id: 'CR',
    index: 48,
    name: 'Costa Rica',
    uri: require('../../assets/flagpng/cr.png'),
  },
  {
    answer: ['Aruba', 'Cuba', 'Haiti', 'Quần đảo Virgin'],
    correct: 1,
    id: 'CU',
    index: 49,
    name: 'Cuba',
    uri: require('../../assets/flagpng/cu.png'),
  },
  // {
  //   answer: [
  //     'Saint Kitts và Nevis',
  //     'Curaçao',
  //     'Saint Vincent và Grenadines',
  //     'Curaçao',
  //   ],
  //   correct: 1,
  //   id: 'CW',
  //   index: 51,
  //   name: 'Curaçao',
  //   uri: require('../../assets/flagpng/cw.png'),
  // },
  {
    answer: ['Cộng hòa Dominica', 'Dominica', 'Jamaica', 'Quần đảo Virgin'],
    correct: 1,
    id: 'DM',
    index: 58,
    name: 'Dominica',
    uri: require('../../assets/flagpng/dm.png'),
  },
  {
    answer: [
      'Quần đảo Turks và Caicos',
      'Cộng hòa Dominica',
      'Barbados',
      'Honduras',
    ],
    correct: 1,
    id: 'DO',
    index: 59,
    name: 'Cộng hòa Dominica',
    uri: require('../../assets/flagpng/do.png'),
  },
  {
    answer: ['Grenada', 'Haiti', 'Saint Pierre và Miquelon', 'Cuba'],
    correct: 0,
    id: 'GD',
    index: 81,
    name: 'Grenada',
    uri: require('../../assets/flagpng/gd.png'),
  },
  // {
  //   answer: [
  //     'Saint Lucia',
  //     'Saint Vincent và Grenadines',
  //     'Greenland',
  //     'Dominica',
  //   ],
  //   correct: 2,
  //   id: 'GL',
  //   index: 87,
  //   name: 'Greenland',
  //   uri: require('../../assets/flagpng/gl.png'),
  // },
  // {
  //   answer: [
  //     'Saint Pierre và Miquelon',
  //     'Guadeloupe',
  //     'Grenada',
  //     'Cộng hòa Dominica',
  //   ],
  //   correct: 1,
  //   id: 'GP',
  //   index: 90,
  //   name: 'Guadeloupe',
  //   uri: require('../../assets/flagpng/gp.png'),
  // },
  {
    answer: ['Honduras', 'Guatemala', 'Bermuda', 'Panama'],
    correct: 1,
    id: 'GT',
    index: 94,
    name: 'Guatemala',
    uri: require('../../assets/flagpng/gt.png'),
  },
  {
    answer: [
      'Antigua và Barbuda',
      'Honduras',
      'Saint Martin',
      'Saint Pierre và Miquelon',
    ],
    correct: 1,
    id: 'HN',
    index: 100,
    name: 'Honduras',
    uri: require('../../assets/flagpng/hn.png'),
  },
  {
    answer: ['Saint Vincent và Grenadines', 'Haiti', 'Curaçao', 'Saint Martin'],
    correct: 1,
    id: 'HT',
    index: 102,
    name: 'Haiti',
    uri: require('../../assets/flagpng/ht.png'),
  },
  {
    answer: ['Jamaica', 'Jamaica', 'Quần đảo Virgin', 'Cộng hòa Dominica'],
    correct: 1,
    id: 'JM',
    index: 115,
    name: 'Jamaica',
    uri: require('../../assets/flagpng/jm.png'),
  },
  {
    answer: ['El Salvador', 'Nicaragua', 'Bahamas', 'Saint Kitts và Nevis'],
    correct: 3,
    id: 'KN',
    index: 123,
    name: 'Saint Kitts và Nevis',
    uri: require('../../assets/flagpng/kn.png'),
  },
  // {
  //   answer: [
  //     'Anguilla',
  //     'Saint Kitts và Nevis',
  //     'Quần đảo Cayman',
  //     'El Salvador',
  //   ],
  //   correct: 2,
  //   id: 'KY',
  //   index: 127,
  //   name: 'Quần đảo Cayman',
  //   uri: require('../../assets/flagpng/ky.png'),
  // },
  {
    answer: [
      'Saint Pierre và Miquelon',
      'Curaçao',
      'Saint Lucia',
      'Saint Lucia',
    ],
    correct: 2,
    id: 'LC',
    index: 131,
    name: 'Saint Lucia',
    uri: require('../../assets/flagpng/lc.png'),
  },
  // {
  //   answer: ['Haiti', 'Sint Maarten', 'Saint Martin', 'Belize'],
  //   correct: 2,
  //   id: 'MF',
  //   index: 144,
  //   name: 'Saint Martin',
  //   uri: require('../../assets/flagpng/mf.png'),
  // },
  // {
  //   answer: ['Quần đảo Virgin', 'Costa Rica', 'Martinique', 'Greenland'],
  //   correct: 2,
  //   id: 'MQ',
  //   index: 153,
  //   name: 'Martinique',
  //   uri: require('../../assets/flagpng/mq.png'),
  // },
  // {
  //   answer: ['Montserrat', 'Belize', 'Panama', 'Martinique'],
  //   correct: 0,
  //   id: 'MS',
  //   index: 155,
  //   name: 'Montserrat',
  //   uri: require('../../assets/flagpng/ms.png'),
  // },
  {
    answer: ['Saint Martin', 'Mexico', 'Belize', 'Mỹ (Hoa Kỳ)'],
    correct: 1,
    id: 'MX',
    index: 160,
    name: 'Mexico',
    uri: require('../../assets/flagpng/mx.png'),
  },
  {
    answer: ['Saint Martin', 'Saint Pierre và Miquelon', 'Belize', 'Nicaragua'],
    correct: 3,
    id: 'NI',
    index: 168,
    name: 'Nicaragua',
    uri: require('../../assets/flagpng/ni.png'),
  },
  {
    answer: ['Puerto Rico', 'Panama', 'Barbados', 'Greenland'],
    correct: 1,
    id: 'PA',
    index: 176,
    name: 'Panama',
    uri: require('../../assets/flagpng/pa.png'),
  },
  // {
  //   answer: [
  //     'Cộng hòa Dominica',
  //     'Saint Pierre và Miquelon',
  //     'Puerto Rico',
  //     'Saint Martin',
  //   ],
  //   correct: 1,
  //   id: 'PM',
  //   index: 183,
  //   name: 'Saint Pierre và Miquelon',
  //   uri: require('../../assets/flagpng/pm.png'),
  // },
  // {
  //   answer: [
  //     'Saint Vincent và Grenadines',
  //     'Anguilla',
  //     'Puerto Rico',
  //     'Guatemala',
  //   ],
  //   correct: 2,
  //   id: 'PR',
  //   index: 185,
  //   name: 'Puerto Rico',
  //   uri: require('../../assets/flagpng/pr.png'),
  // },
  {
    answer: ['Saint Lucia', 'Barbados', 'El Salvador', 'Sint Maarten'],
    correct: 2,
    id: 'SV',
    index: 213,
    name: 'El Salvador',
    uri: require('../../assets/flagpng/sv.png'),
  },
  // {
  //   answer: [
  //     'Quần đảo Turks và Caicos',
  //     'Sint Maarten',
  //     'Saint Kitts và Nevis',
  //     'Saint Barthélemy',
  //   ],
  //   correct: 1,
  //   id: 'SX',
  //   index: 214,
  //   name: 'Sint Maarten',
  //   uri: require('../../assets/flagpng/sx.png'),
  // },
  // {
  //   answer: [
  //     'Canada',
  //     'Guatemala',
  //     'Quần đảo Turks và Caicos',
  //     'Quần đảo Virgin',
  //   ],
  //   correct: 2,
  //   id: 'TC',
  //   index: 217,
  //   name: 'Quần đảo Turks và Caicos',
  //   uri: require('../../assets/flagpng/tc.png'),
  // },
  {
    answer: [
      'Saint Vincent và Grenadines',
      'Canada',
      'Trinidad và Tobago',
      'Jamaica',
    ],
    correct: 2,
    id: 'TT',
    index: 229,
    name: 'Trinidad và Tobago',
    uri: require('../../assets/flagpng/tt.png'),
  },
  {
    answer: ['Mỹ (Hoa Kỳ)', 'Martinique', 'Puerto Rico', 'Barbados'],
    correct: 0,
    id: 'US',
    index: 235,
    name: 'Mỹ (Hoa Kỳ)',
    uri: require('../../assets/flagpng/us.png'),
  },
  {
    answer: [
      'Guatemala',
      'Cộng hòa Dominica',
      'Panama',
      'Saint Vincent và Grenadines',
    ],
    correct: 3,
    id: 'VC',
    index: 239,
    name: 'Saint Vincent và Grenadines',
    uri: require('../../assets/flagpng/vc.png'),
  },
  // {
  //   answer: [
  //     'Quần đảo Virgin',
  //     'Saint Barthélemy',
  //     'Martinique',
  //     'Mỹ (Hoa Kỳ)',
  //   ],
  //   correct: 0,
  //   id: 'VG',
  //   index: 241,
  //   name: 'Quần đảo Virgin',
  //   uri: require('../../assets/flagpng/vg.png'),
  // },
  // {
  //   answer: ['Mỹ (Hoa Kỳ)', 'Bahamas', 'Montserrat', 'Quần đảo Virgin'],
  //   correct: 3,
  //   id: 'VI',
  //   index: 242,
  //   name: 'Quần đảo Virgin',
  //   uri: require('../../assets/flagpng/vi.png'),
  // },
];

export const DATANAMERICA: Country[] = [
  {
    answer: ['Trinidad and Tobago', 'Antigua and Barbuda', 'Haiti', 'Canada'],
    correct: 1,
    id: 'AG',
    index: 5,
    name: 'Antigua and Barbuda',
    uri: require('../../assets/flagpng/ag.png'),
  },
  {
    answer: ['Bahamas', 'Dominica', 'Saint Kitts and Nevis', 'Saint Lucia'],
    correct: 0,
    id: 'BS',
    index: 11,
    name: 'Bahamas',
    uri: require('../../assets/flagpng/bs.png'),
  },
  {
    answer: ['Haiti', 'Trinidad and Tobago', 'Barbados', 'Dominica'],
    correct: 2,
    id: 'BB',
    index: 14,
    name: 'Barbados',
    uri: require('../../assets/flagpng/bb.png'),
  },
  {
    answer: ['United States of America', 'Barbados', 'Haiti', 'Belize'],
    correct: 3,
    id: 'BZ',
    index: 17,
    name: 'Belize',
    uri: require('../../assets/flagpng/bz.png'),
  },
  {
    answer: [
      'Antigua and Barbuda',
      'Canada',
      'Trinidad and Tobago',
      'El Salvador',
    ],
    correct: 1,
    id: 'CA',
    index: 31,
    name: 'Canada',
    uri: require('../../assets/flagpng/ca.png'),
  },
  {
    answer: ['United States of America', 'Haiti', 'Belize', 'Costa Rica'],
    correct: 3,
    id: 'CR',
    index: 40,
    name: 'Costa Rica',
    uri: require('../../assets/flagpng/cr.png'),
  },
  {
    answer: [
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Dominican Republic',
      'Cuba',
    ],
    correct: 3,
    id: 'CU',
    index: 43,
    name: 'Cuba',
    uri: require('../../assets/flagpng/cu.png'),
  },
  {
    answer: ['Costa Rica', 'Dominica', 'Saint Lucia', 'Panama'],
    correct: 1,
    id: 'DM',
    index: 48,
    name: 'Dominica',
    uri: require('../../assets/flagpng/dm.png'),
  },
  {
    answer: ['Grenada', 'Dominican Republic', 'Belize', 'Saint Lucia'],
    correct: 1,
    id: 'DO',
    index: 49,
    name: 'Dominican Republic',
    uri: require('../../assets/flagpng/do.png'),
  },
  {
    answer: [
      'Costa Rica',
      'El Salvador',
      'El Salvador',
      'United States of America',
    ],
    correct: 2,
    id: 'SV',
    index: 52,
    name: 'El Salvador',
    uri: require('../../assets/flagpng/sv.png'),
  },
  {
    answer: [
      'Bahamas',
      'Grenada',
      'Saint Vincent and the Grenadines',
      'Saint Kitts and Nevis',
    ],
    correct: 1,
    id: 'GD',
    index: 67,
    name: 'Grenada',
    uri: require('../../assets/flagpng/gd.png'),
  },
  {
    answer: ['Saint Lucia', 'Guatemala', 'Canada', 'Guatemala'],
    correct: 1,
    id: 'GT',
    index: 68,
    name: 'Guatemala',
    uri: require('../../assets/flagpng/gt.png'),
  },
  {
    answer: ['United States of America', 'Haiti', 'Barbados', 'El Salvador'],
    correct: 1,
    id: 'HT',
    index: 72,
    name: 'Haiti',
    uri: require('../../assets/flagpng/ht.png'),
  },
  {
    answer: ['Canada', 'Honduras', 'Saint Lucia', 'Panama'],
    correct: 1,
    id: 'HN',
    index: 73,
    name: 'Honduras',
    uri: require('../../assets/flagpng/hn.png'),
  },
  {
    answer: ['Mexico', 'Canada', 'United States of America', 'Jamaica'],
    correct: 3,
    id: 'JM',
    index: 83,
    name: 'Jamaica',
    uri: require('../../assets/flagpng/jm.png'),
  },
  {
    answer: ['Mexico', 'Nicaragua', 'United States of America', 'Dominica'],
    correct: 0,
    id: 'MX',
    index: 111,
    name: 'Mexico',
    uri: require('../../assets/flagpng/mx.png'),
  },
  {
    answer: [
      'Nicaragua',
      'Saint Vincent and the Grenadines',
      'Dominica',
      'Haiti',
    ],
    correct: 0,
    id: 'NI',
    index: 125,
    name: 'Nicaragua',
    uri: require('../../assets/flagpng/ni.png'),
  },
  {
    answer: ['United States of America', 'Panama', 'Guatemala', 'Bahamas'],
    correct: 1,
    id: 'PA',
    index: 133,
    name: 'Panama',
    uri: require('../../assets/flagpng/pa.png'),
  },
  {
    answer: [
      'Nicaragua',
      'United States of America',
      'Dominican Republic',
      'Saint Kitts and Nevis',
    ],
    correct: 3,
    id: 'KN',
    index: 144,
    name: 'Saint Kitts and Nevis',
    uri: require('../../assets/flagpng/kn.png'),
  },
  {
    answer: ['Panama', 'United States of America', 'Saint Lucia', 'Cuba'],
    correct: 2,
    id: 'LC',
    index: 145,
    name: 'Saint Lucia',
    uri: require('../../assets/flagpng/lc.png'),
  },
  {
    answer: [
      'Dominica',
      'Nicaragua',
      'Saint Vincent and the Grenadines',
      'Saint Vincent and the Grenadines',
    ],
    correct: 2,
    id: 'VC',
    index: 146,
    name: 'Saint Vincent and the Grenadines',
    uri: require('../../assets/flagpng/vc.png'),
  },
  {
    answer: [
      'Honduras',
      'Dominica',
      'Trinidad and Tobago',
      'Trinidad and Tobago',
    ],
    correct: 3,
    id: 'TT',
    index: 175,
    name: 'Trinidad and Tobago',
    uri: require('../../assets/flagpng/tt.png'),
  },
  {
    answer: [
      'Trinidad and Tobago',
      'Grenada',
      'Cuba',
      'United States of America',
    ],
    correct: 3,
    id: 'US',
    index: 184,
    name: 'United States of America',
    uri: require('../../assets/flagpng/us.png'),
  },
];
