import {Country} from '../../model/Country';

export const DATAASIAVI: Country[] = [
  {
    answer: [
      'Maldives',
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 1,
    id: 'AE',
    index: 1,
    name: 'Các tiểu vương quốc Ả Rập Thống nhất',
    uri: require('../../assets/flagpng/ae.png'),
  },
  {
    answer: ['Nhật Bản', 'Tajikistan', 'Bangladesh', 'Afghanistan'],
    correct: 3,
    id: 'AF',
    index: 2,
    name: 'Afghanistan',
    uri: require('../../assets/flagpng/af.png'),
  },
  {
    answer: ['Singapore', 'Armenia', 'Indonesia', 'Kyrgyzstan'],
    correct: 1,
    id: 'AM',
    index: 6,
    name: 'Armenia',
    uri: require('../../assets/flagpng/am.png'),
  },
  {
    answer: ['Triều Tiên', 'Singapore', 'Azerbaijan', 'Azerbaijan'],
    correct: 3,
    id: 'AZ',
    index: 15,
    name: 'Azerbaijan',
    uri: require('../../assets/flagpng/az.png'),
  },
  {
    answer: ['Nga', 'Hồng Kông', 'Triều Tiên', 'Bangladesh'],
    correct: 3,
    id: 'BD',
    index: 18,
    name: 'Bangladesh',
    uri: require('../../assets/flagpng/bd.png'),
  },
  {
    answer: ['Li-băng', 'Bahrain', 'Nepal', 'Trung Quốc'],
    correct: 1,
    id: 'BH',
    index: 22,
    name: 'Bahrain',
    uri: require('../../assets/flagpng/bh.png'),
  },
  {
    answer: ['Brunei Darussalam', 'Lãnh thổ Đảo Christmas', 'Iran', 'Syria'],
    correct: 0,
    id: 'BN',
    index: 27,
    name: 'Brunei Darussalam',
    uri: require('../../assets/flagpng/bn.png'),
  },
  {
    answer: ['Armenia', 'Bhutan', 'Li-băng', 'Palestine'],
    correct: 1,
    id: 'BT',
    index: 31,
    name: 'Bhutan',
    uri: require('../../assets/flagpng/bt.png'),
  },
  {
    answer: ['Georgia', 'Malaysia', 'Nepal', 'Quần đảo Cocos'],
    correct: 3,
    id: 'CC',
    index: 37,
    name: 'Quần đảo Cocos',
    uri: require('../../assets/flagpng/cc.png'),
  },
  {
    answer: ['Georgia', 'Trung Quốc', 'Sri Lanka', 'Việt Nam'],
    correct: 1,
    id: 'CN',
    index: 46,
    name: 'Trung Quốc',
    uri: require('../../assets/flagpng/cn.png'),
  },
  {
    answer: ['Lào', 'Lãnh thổ Đảo Christmas', 'Turkmenistan', 'Trung Quốc'],
    correct: 1,
    id: 'CX',
    index: 52,
    name: 'Lãnh thổ Đảo Christmas',
    uri: require('../../assets/flagpng/cx.png'),
  },
  {
    answer: ['Oman', 'Georgia', 'Bangladesh', 'Nhật Bản'],
    correct: 1,
    id: 'GE',
    index: 82,
    name: 'Georgia',
    uri: require('../../assets/flagpng/ge.png'),
  },
  {
    answer: ['Israel', 'Thổ Nhĩ Kỳ', 'Nhật Bản', 'Hồng Kông'],
    correct: 3,
    id: 'HK',
    index: 98,
    name: 'Hồng Kông',
    uri: require('../../assets/flagpng/hk.png'),
  },
  {
    answer: ['Sri Lanka', 'Indonesia', 'Thổ Nhĩ Kỳ', 'Georgia'],
    correct: 1,
    id: 'ID',
    index: 104,
    name: 'Indonesia',
    uri: require('../../assets/flagpng/id.png'),
  },
  {
    answer: ['Israel', 'Mongolia', 'Bhutan', 'Yemen'],
    correct: 0,
    id: 'IL',
    index: 106,
    name: 'Israel',
    uri: require('../../assets/flagpng/il.png'),
  },
  {
    answer: ['Ấn Độ', 'Kazakhstan', 'Lãnh thổ Đảo Christmas', 'Yemen'],
    correct: 0,
    id: 'IN',
    index: 108,
    name: 'Ấn Độ',
    uri: require('../../assets/flagpng/in.png'),
  },
  {
    answer: [
      'Hồng Kông',
      'Nepal',
      'Kyrgyzstan',
      'Lãnh thổ Anh tại Ấn Độ Dương',
    ],
    correct: 3,
    id: 'IO',
    index: 109,
    name: 'Lãnh thổ Anh tại Ấn Độ Dương',
    uri: require('../../assets/flagpng/io.png'),
  },
  {
    answer: ['Kazakhstan', 'Iraq', 'Thailand', 'Israel'],
    correct: 1,
    id: 'IQ',
    index: 110,
    name: 'Iraq',
    uri: require('../../assets/flagpng/iq.png'),
  },
  {
    answer: ['Iran', 'Ấn Độ', 'Mongolia', 'Việt Nam'],
    correct: 0,
    id: 'IR',
    index: 111,
    name: 'Iran',
    uri: require('../../assets/flagpng/ir.png'),
  },
  {
    answer: ['Jordan', 'Thailand', 'Armenia', 'Myanmar'],
    correct: 0,
    id: 'JO',
    index: 116,
    name: 'Jordan',
    uri: require('../../assets/flagpng/jo.png'),
  },
  {
    answer: ['Campuchia', 'Israel', 'Nhật Bản', 'Nepal'],
    correct: 2,
    id: 'JP',
    index: 117,
    name: 'Nhật Bản',
    uri: require('../../assets/flagpng/jp.png'),
  },
  {
    answer: ['Hồng Kông', 'Nga', 'Kyrgyzstan', 'Malaysia'],
    correct: 2,
    id: 'KG',
    index: 119,
    name: 'Kyrgyzstan',
    uri: require('../../assets/flagpng/kg.png'),
  },
  {
    answer: ['Indonesia', 'Jordan', 'Qatar', 'Campuchia'],
    correct: 3,
    id: 'KH',
    index: 120,
    name: 'Campuchia',
    uri: require('../../assets/flagpng/kh.png'),
  },
  {
    answer: ['Maldives', 'Triều Tiên', 'Đài Loan', 'Indonesia'],
    correct: 1,
    id: 'KP',
    index: 124,
    name: 'Triều Tiên',
    uri: require('../../assets/flagpng/kp.png'),
  },
  {
    answer: ['Brunei Darussalam', 'Turkmenistan', 'Li-băng', 'Hàn Quốc'],
    correct: 3,
    id: 'KR',
    index: 125,
    name: 'Hàn Quốc',
    uri: require('../../assets/flagpng/kr.png'),
  },
  {
    answer: ['Ấn Độ', 'Qatar', 'Kuwait', 'Jordan'],
    correct: 2,
    id: 'KW',
    index: 126,
    name: 'Kuwait',
    uri: require('../../assets/flagpng/kw.png'),
  },
  {
    answer: ['Lãnh thổ Đảo Christmas', 'Kazakhstan', 'Uzbekistan', 'Iran'],
    correct: 1,
    id: 'KZ',
    index: 128,
    name: 'Kazakhstan',
    uri: require('../../assets/flagpng/kz.png'),
  },
  {
    answer: ['Hồng Kông', 'Đài Loan', 'Hàn Quốc', 'Lào'],
    correct: 3,
    id: 'LA',
    index: 129,
    name: 'Lào',
    uri: require('../../assets/flagpng/la.png'),
  },
  {
    answer: ['Pakistan', 'Li-băng', 'Bahrain', 'Triều Tiên'],
    correct: 1,
    id: 'LB',
    index: 130,
    name: 'Li-băng',
    uri: require('../../assets/flagpng/lb.png'),
  },
  {
    answer: ['Bangladesh', 'Sri Lanka', 'Triều Tiên', 'Singapore'],
    correct: 1,
    id: 'LK',
    index: 133,
    name: 'Sri Lanka',
    uri: require('../../assets/flagpng/lk.png'),
  },
  {
    answer: ['Myanmar', 'Indonesia', 'Kuwait', 'Philippines'],
    correct: 0,
    id: 'MM',
    index: 149,
    name: 'Myanmar',
    uri: require('../../assets/flagpng/mm.png'),
  },
  {
    answer: ['Quần đảo Cocos', 'Kazakhstan', 'Nga', 'Mongolia'],
    correct: 3,
    id: 'MN',
    index: 150,
    name: 'Mongolia',
    uri: require('../../assets/flagpng/mn.png'),
  },
  {
    answer: ['Mongolia', 'Macao', 'Oman', 'Bhutan'],
    correct: 1,
    id: 'MO',
    index: 151,
    name: 'Macao',
    uri: require('../../assets/flagpng/mo.png'),
  },
  {
    answer: ['Quần đảo Cocos', 'Iran', 'Maldives', 'Tajikistan'],
    correct: 2,
    id: 'MV',
    index: 158,
    name: 'Maldives',
    uri: require('../../assets/flagpng/mv.png'),
  },
  {
    answer: ['Uzbekistan', 'Myanmar', 'Israel', 'Malaysia'],
    correct: 3,
    id: 'MY',
    index: 161,
    name: 'Malaysia',
    uri: require('../../assets/flagpng/my.png'),
  },
  {
    answer: ['Trung Quốc', 'Thổ Nhĩ Kỳ', 'Iran', 'Nepal'],
    correct: 3,
    id: 'NP',
    index: 171,
    name: 'Nepal',
    uri: require('../../assets/flagpng/np.png'),
  },
  {
    answer: ['Oman', 'Lào', 'Oman', 'Azerbaijan'],
    correct: 0,
    id: 'OM',
    index: 175,
    name: 'Oman',
    uri: require('../../assets/flagpng/om.png'),
  },
  {
    answer: ['Philippines', 'Turkmenistan', 'Afghanistan', 'Kazakhstan'],
    correct: 0,
    id: 'PH',
    index: 180,
    name: 'Philippines',
    uri: require('../../assets/flagpng/ph.png'),
  },
  {
    answer: ['Uzbekistan', 'Pakistan', 'Israel', 'Kyrgyzstan'],
    correct: 1,
    id: 'PK',
    index: 181,
    name: 'Pakistan',
    uri: require('../../assets/flagpng/pk.png'),
  },
  {
    answer: ['Palestine', 'Iran', 'Quần đảo Cocos', 'Turkmenistan'],
    correct: 0,
    id: 'PS',
    index: 186,
    name: 'Palestine',
    uri: require('../../assets/flagpng/ps.png'),
  },
  {
    answer: ['Singapore', 'Hàn Quốc', 'Lãnh thổ Đảo Christmas', 'Qatar'],
    correct: 3,
    id: 'QA',
    index: 190,
    name: 'Qatar',
    uri: require('../../assets/flagpng/qa.png'),
  },
  {
    answer: ['Azerbaijan', 'Nepal', 'Nga', 'Iran'],
    correct: 2,
    id: 'RU',
    index: 194,
    name: 'Nga',
    uri: require('../../assets/flagpng/ru.png'),
  },
  {
    answer: ['Ả Rập Xê Út', 'Armenia', 'Macao', 'Nepal'],
    correct: 0,
    id: 'SA',
    index: 196,
    name: 'Ả Rập Xê Út',
    uri: require('../../assets/flagpng/sa.png'),
  },
  {
    answer: ['Afghanistan', 'Jordan', 'Singapore', 'Turkmenistan'],
    correct: 2,
    id: 'SG',
    index: 201,
    name: 'Singapore',
    uri: require('../../assets/flagpng/sg.png'),
  },
  {
    answer: ['Israel', 'Kuwait', 'Syria', 'Nga'],
    correct: 2,
    id: 'SY',
    index: 215,
    name: 'Syria',
    uri: require('../../assets/flagpng/sy.png'),
  },
  {
    answer: ['Myanmar', 'Thổ Nhĩ Kỳ', 'Ấn Độ', 'Thailand'],
    correct: 3,
    id: 'TH',
    index: 221,
    name: 'Thailand',
    uri: require('../../assets/flagpng/th.png'),
  },
  {
    answer: ['Qatar', 'Nhật Bản', 'Tajikistan', 'Bahrain'],
    correct: 2,
    id: 'TJ',
    index: 222,
    name: 'Tajikistan',
    uri: require('../../assets/flagpng/tj.png'),
  },
  {
    answer: ['Hồng Kông', 'Turkmenistan', 'Campuchia', 'Qatar'],
    correct: 1,
    id: 'TM',
    index: 225,
    name: 'Turkmenistan',
    uri: require('../../assets/flagpng/tm.png'),
  },
  {
    answer: ['Việt Nam', 'Jordan', 'Afghanistan', 'Thổ Nhĩ Kỳ'],
    correct: 3,
    id: 'TR',
    index: 228,
    name: 'Thổ Nhĩ Kỳ',
    uri: require('../../assets/flagpng/tr.png'),
  },
  {
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Đài Loan',
      'Campuchia',
    ],
    correct: 2,
    id: 'TW',
    index: 231,
    name: 'Đài Loan',
    uri: require('../../assets/flagpng/tw.png'),
  },
  {
    answer: ['Lãnh thổ Anh tại Ấn Độ Dương', 'Uzbekistan', 'Nepal', 'Mongolia'],
    correct: 1,
    id: 'UZ',
    index: 237,
    name: 'Uzbekistan',
    uri: require('../../assets/flagpng/uz.png'),
  },
  {
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Việt Nam',
      'Kuwait',
      'Thổ Nhĩ Kỳ',
    ],
    correct: 1,
    id: 'VN',
    index: 243,
    name: 'Việt Nam',
    uri: require('../../assets/flagpng/vn.png'),
  },
  {
    answer: ['Qatar', 'Jordan', 'Yemen', 'Azerbaijan'],
    correct: 2,
    id: 'YE',
    index: 248,
    name: 'Yemen',
    uri: require('../../assets/flagpng/ye.png'),
  },
];

export const DATAASIA: Country[] = [
  {
    answer: ['Azerbaijan', 'Jordan', 'Russian Federation', 'Afghanistan'],
    correct: 3,
    id: 'AF',
    index: 0,
    name: 'Afghanistan',
    uri: require('../../assets/flagpng/af.png'),
  },
  {
    answer: ['United Arab Emirates', 'Armenia', 'Israel', 'Malaysia'],
    correct: 1,
    id: 'AM',
    index: 7,
    name: 'Armenia',
    uri: require('../../assets/flagpng/am.png'),
  },
  {
    answer: ['Uzbekistan', 'Afghanistan', 'Korea, Republic of', 'Azerbaijan'],
    correct: 3,
    id: 'AZ',
    index: 10,
    name: 'Azerbaijan',
    uri: require('../../assets/flagpng/az.png'),
  },
  {
    answer: ['Bahrain', 'Jordan', 'Cambodia', 'Türkiye'],
    correct: 0,
    id: 'BH',
    index: 12,
    name: 'Bahrain',
    uri: require('../../assets/flagpng/bh.png'),
  },
  {
    answer: [
      "Lao People's Democratic Republic",
      'Bangladesh',
      'Georgia',
      'Tajikistan',
    ],
    correct: 1,
    id: 'BD',
    index: 13,
    name: 'Bangladesh',
    uri: require('../../assets/flagpng/bd.png'),
  },
  {
    answer: ['Turkmenistan', 'Korea, Republic of', 'Bhutan', 'Indonesia'],
    correct: 2,
    id: 'BT',
    index: 19,
    name: 'Bhutan',
    uri: require('../../assets/flagpng/bt.png'),
  },
  {
    answer: [
      'Turkmenistan',
      'Brunei Darussalam',
      "Korea (Democratic People's Republic of)",
      'Israel',
    ],
    correct: 1,
    id: 'BN',
    index: 24,
    name: 'Brunei Darussalam',
    uri: require('../../assets/flagpng/bn.png'),
  },
  {
    answer: ['Yemen', 'China', 'Kazakhstan', 'Cambodia'],
    correct: 3,
    id: 'KH',
    index: 29,
    name: 'Cambodia',
    uri: require('../../assets/flagpng/kh.png'),
  },
  {
    answer: ['Cambodia', 'Singapore', 'China', 'Maldives'],
    correct: 2,
    id: 'CN',
    index: 35,
    name: 'China',
    uri: require('../../assets/flagpng/cn.png'),
  },
  {
    answer: ['Jordan', 'Viet Nam', 'Cambodia', 'Georgia'],
    correct: 3,
    id: 'GE',
    index: 63,
    name: 'Georgia',
    uri: require('../../assets/flagpng/ge.png'),
  },
  {
    answer: ['United Arab Emirates', 'Philippines', 'India', 'Cambodia'],
    correct: 2,
    id: 'IN',
    index: 76,
    name: 'India',
    uri: require('../../assets/flagpng/in.png'),
  },
  {
    answer: ['Russian Federation', 'Indonesia', 'Pakistan', 'Armenia'],
    correct: 1,
    id: 'ID',
    index: 77,
    name: 'Indonesia',
    uri: require('../../assets/flagpng/id.png'),
  },
  {
    answer: ['Tajikistan', 'Iraq', 'Iran (Islamic Republic of)', 'Philippines'],
    correct: 2,
    id: 'IR',
    index: 78,
    name: 'Iran (Islamic Republic of)',
    uri: require('../../assets/flagpng/ir.png'),
  },
  {
    answer: ['Japan', 'Kyrgyzstan', 'Singapore', 'Iraq'],
    correct: 3,
    id: 'IQ',
    index: 79,
    name: 'Iraq',
    uri: require('../../assets/flagpng/iq.png'),
  },
  {
    answer: ['Yemen', 'Brunei Darussalam', 'Korea, Republic of', 'Israel'],
    correct: 3,
    id: 'IL',
    index: 81,
    name: 'Israel',
    uri: require('../../assets/flagpng/il.png'),
  },
  {
    answer: ['Japan', 'Korea, Republic of', 'Bangladesh', 'Viet Nam'],
    correct: 0,
    id: 'JP',
    index: 84,
    name: 'Japan',
    uri: require('../../assets/flagpng/jp.png'),
  },
  {
    answer: ['Iran (Islamic Republic of)', 'Jordan', 'Thailand', 'Kyrgyzstan'],
    correct: 1,
    id: 'JO',
    index: 85,
    name: 'Jordan',
    uri: require('../../assets/flagpng/jo.png'),
  },
  {
    answer: ['Jordan', 'Saudi Arabia', 'Bahrain', 'Kazakhstan'],
    correct: 3,
    id: 'KZ',
    index: 86,
    name: 'Kazakhstan',
    uri: require('../../assets/flagpng/kz.png'),
  },
  {
    answer: [
      "Korea (Democratic People's Republic of)",
      'Thailand',
      'Malaysia',
      'India',
    ],
    correct: 0,
    id: 'KP',
    index: 89,
    name: "Korea (Democratic People's Republic of)",
    uri: require('../../assets/flagpng/kp.png'),
  },
  {
    answer: [
      'Iraq',
      'Kyrgyzstan',
      'Korea, Republic of',
      'Syrian Arab Republic',
    ],
    correct: 2,
    id: 'KR',
    index: 90,
    name: 'Korea, Republic of',
    uri: require('../../assets/flagpng/kr.png'),
  },
  {
    answer: ['Kuwait', 'Iraq', 'Philippines', 'Tajikistan'],
    correct: 0,
    id: 'KW',
    index: 91,
    name: 'Kuwait',
    uri: require('../../assets/flagpng/kw.png'),
  },
  {
    answer: ['Singapore', 'China', 'Malaysia', 'Kyrgyzstan'],
    correct: 3,
    id: 'KG',
    index: 92,
    name: 'Kyrgyzstan',
    uri: require('../../assets/flagpng/kg.png'),
  },
  {
    answer: [
      "Lao People's Democratic Republic",
      'Maldives',
      'Cambodia',
      'Syrian Arab Republic',
    ],
    correct: 0,
    id: 'LA',
    index: 93,
    name: "Lao People's Democratic Republic",
    uri: require('../../assets/flagpng/la.png'),
  },
  {
    answer: [
      'Uzbekistan',
      'Lebanon',
      'Philippines',
      'Iran (Islamic Republic of)',
    ],
    correct: 1,
    id: 'LB',
    index: 95,
    name: 'Lebanon',
    uri: require('../../assets/flagpng/lb.png'),
  },
  {
    answer: ['Philippines', 'Malaysia', 'China', 'Thailand'],
    correct: 1,
    id: 'MY',
    index: 104,
    name: 'Malaysia',
    uri: require('../../assets/flagpng/my.png'),
  },
  {
    answer: ['Maldives', 'Turkmenistan', 'Oman', 'Iraq'],
    correct: 0,
    id: 'MV',
    index: 105,
    name: 'Maldives',
    uri: require('../../assets/flagpng/mv.png'),
  },
  {
    answer: ['Bahrain', 'Mongolia', 'Türkiye', 'Korea, Republic of'],
    correct: 1,
    id: 'MN',
    index: 115,
    name: 'Mongolia',
    uri: require('../../assets/flagpng/mn.png'),
  },
  {
    answer: ['Myanmar', 'Philippines', 'Cambodia', 'Yemen'],
    correct: 0,
    id: 'MM',
    index: 119,
    name: 'Myanmar',
    uri: require('../../assets/flagpng/mm.png'),
  },
  {
    answer: ['Tajikistan', 'Nepal', 'Indonesia', 'Lebanon'],
    correct: 1,
    id: 'NP',
    index: 122,
    name: 'Nepal',
    uri: require('../../assets/flagpng/np.png'),
  },
  {
    answer: [
      'China',
      'Oman',
      'Saudi Arabia',
      "Korea (Democratic People's Republic of)",
    ],
    correct: 1,
    id: 'OM',
    index: 130,
    name: 'Oman',
    uri: require('../../assets/flagpng/om.png'),
  },
  {
    answer: ['Singapore', 'Pakistan', 'Cambodia', 'Philippines'],
    correct: 1,
    id: 'PK',
    index: 131,
    name: 'Pakistan',
    uri: require('../../assets/flagpng/pk.png'),
  },
  {
    answer: ['Philippines', 'Sri Lanka', 'Lebanon', 'China'],
    correct: 0,
    id: 'PH',
    index: 137,
    name: 'Philippines',
    uri: require('../../assets/flagpng/ph.png'),
  },
  {
    answer: ['Yemen', 'China', 'Korea, Republic of', 'Qatar'],
    correct: 3,
    id: 'QA',
    index: 140,
    name: 'Qatar',
    uri: require('../../assets/flagpng/qa.png'),
  },
  {
    answer: [
      'United Arab Emirates',
      'Georgia',
      'Kyrgyzstan',
      'Russian Federation',
    ],
    correct: 3,
    id: 'RU',
    index: 142,
    name: 'Russian Federation',
    uri: require('../../assets/flagpng/ru.png'),
  },
  {
    answer: [
      'Saudi Arabia',
      'Iran (Islamic Republic of)',
      'Kazakhstan',
      'Tajikistan',
    ],
    correct: 0,
    id: 'SA',
    index: 150,
    name: 'Saudi Arabia',
    uri: require('../../assets/flagpng/sa.png'),
  },
  {
    answer: ['Bahrain', 'Singapore', 'Kazakhstan', 'Sri Lanka'],
    correct: 1,
    id: 'SG',
    index: 155,
    name: 'Singapore',
    uri: require('../../assets/flagpng/sg.png'),
  },
  {
    answer: ['United Arab Emirates', 'Nepal', 'Georgia', 'Sri Lanka'],
    correct: 3,
    id: 'LK',
    index: 163,
    name: 'Sri Lanka',
    uri: require('../../assets/flagpng/lk.png'),
  },
  {
    answer: [
      'Iraq',
      'Syrian Arab Republic',
      "Korea (Democratic People's Republic of)",
      'Turkmenistan',
    ],
    correct: 1,
    id: 'SY',
    index: 168,
    name: 'Syrian Arab Republic',
    uri: require('../../assets/flagpng/sy.png'),
  },
  {
    answer: ['Bahrain', 'Jordan', 'Tajikistan', 'Viet Nam'],
    correct: 2,
    id: 'TJ',
    index: 169,
    name: 'Tajikistan',
    uri: require('../../assets/flagpng/tj.png'),
  },
  {
    answer: ['Afghanistan', 'Syrian Arab Republic', 'Thailand', 'Jordan'],
    correct: 2,
    id: 'TH',
    index: 171,
    name: 'Thailand',
    uri: require('../../assets/flagpng/th.png'),
  },
  {
    answer: [
      "Korea (Democratic People's Republic of)",
      'Türkiye',
      'Japan',
      'Türkiye',
    ],
    correct: 1,
    id: 'TR',
    index: 177,
    name: 'Türkiye',
    uri: require('../../assets/flagpng/tr.png'),
  },
  {
    answer: ['Yemen', 'Korea, Republic of', 'Indonesia', 'Turkmenistan'],
    correct: 3,
    id: 'TM',
    index: 178,
    name: 'Turkmenistan',
    uri: require('../../assets/flagpng/tm.png'),
  },
  {
    answer: [
      'Russian Federation',
      'Malaysia',
      'United Arab Emirates',
      'Bangladesh',
    ],
    correct: 2,
    id: 'AE',
    index: 182,
    name: 'United Arab Emirates',
    uri: require('../../assets/flagpng/ae.png'),
  },
  {
    answer: [
      'Japan',
      "Korea (Democratic People's Republic of)",
      'Turkmenistan',
      'Uzbekistan',
    ],
    correct: 3,
    id: 'UZ',
    index: 186,
    name: 'Uzbekistan',
    uri: require('../../assets/flagpng/uz.png'),
  },
  {
    answer: [
      'Iraq',
      'Viet Nam',
      "Korea (Democratic People's Republic of)",
      'Sri Lanka',
    ],
    correct: 1,
    id: 'VN',
    index: 189,
    name: 'Viet Nam',
    uri: require('../../assets/flagpng/vn.png'),
  },
  {
    answer: ['Afghanistan', 'Maldives', 'Uzbekistan', 'Yemen'],
    correct: 3,
    id: 'YE',
    index: 190,
    name: 'Yemen',
    uri: require('../../assets/flagpng/ye.png'),
  },
];
