import {Country} from '../../model/Country';

export const DATAOCEANIAVI: Country[] = [
  {
    answer: ['Tonga', 'American Samoa', 'American Samoa', 'Papua New Guinea'],
    correct: 1,
    id: 'AS',
    index: 10,
    name: 'American Samoa',
    uri: require('../../assets/flagpng/as.png'),
  },
  {
    answer: ['Palau', 'Wallis và Futuna Islands', 'Úc', 'Cook Islands'],
    correct: 2,
    id: 'AU',
    index: 12,
    name: 'Úc',
    uri: require('../../assets/flagpng/au.png'),
  },
  {
    answer: ['Vanuatu', 'American Samoa', 'New Zealand', 'Cook Islands'],
    correct: 3,
    id: 'CK',
    index: 43,
    name: 'Cook Islands',
    uri: require('../../assets/flagpng/ck.png'),
  },
  {
    answer: ['Fiji', 'Tuvalu', 'Úc', 'Niue'],
    correct: 0,
    id: 'FJ',
    index: 70,
    name: 'Fiji',
    uri: require('../../assets/flagpng/fj.png'),
  },
  {
    answer: ['Niue', 'Micronesia', 'Vanuatu', 'Úc'],
    correct: 1,
    id: 'FM',
    index: 72,
    name: 'Micronesia',
    uri: require('../../assets/flagpng/fm.png'),
  },
  {
    answer: ['Guam', 'Tonga', 'Niue', 'Cook Islands'],
    correct: 0,
    id: 'GU',
    index: 95,
    name: 'Guam',
    uri: require('../../assets/flagpng/gu.png'),
  },
  {
    answer: ['Kiribati', 'American Samoa', 'Tuvalu', 'Norfolk Island'],
    correct: 0,
    id: 'KI',
    index: 121,
    name: 'Kiribati',
    uri: require('../../assets/flagpng/ki.png'),
  },
  {
    answer: ['Marshall Islands', 'Fiji', 'Pitcairn', 'Vanuatu'],
    correct: 0,
    id: 'MH',
    index: 146,
    name: 'Marshall Islands',
    uri: require('../../assets/flagpng/mh.png'),
  },
  {
    answer: ['Quần đảo Bắc Mariana', 'Quần đảo Bắc Mariana', 'Palau', 'Tuvalu'],
    correct: 1,
    id: 'MP',
    index: 152,
    name: 'Quần đảo Bắc Mariana',
    uri: require('../../assets/flagpng/mp.png'),
  },
  {
    answer: ['Quần đảo Solomon', 'New Caledonia', 'New Caledonia', 'Tonga'],
    correct: 2,
    id: 'NC',
    index: 164,
    name: 'New Caledonia',
    uri: require('../../assets/flagpng/nc.png'),
  },
  {
    answer: ['American Samoa', 'Pitcairn', 'Norfolk Island', 'Tonga'],
    correct: 2,
    id: 'NF',
    index: 166,
    name: 'Norfolk Island',
    uri: require('../../assets/flagpng/nf.png'),
  },
  {
    answer: ['Fiji', 'Nauru', 'Wallis và Futuna Islands', 'New Zealand'],
    correct: 1,
    id: 'NR',
    index: 172,
    name: 'Nauru',
    uri: require('../../assets/flagpng/nr.png'),
  },
  {
    answer: ['Niue', 'Tokelau', 'Cook Islands', 'Vanuatu'],
    correct: 0,
    id: 'NU',
    index: 173,
    name: 'Niue',
    uri: require('../../assets/flagpng/nu.png'),
  },
  {
    answer: ['Đông Timor', 'Marshall Islands', 'Vanuatu', 'New Zealand'],
    correct: 3,
    id: 'NZ',
    index: 174,
    name: 'New Zealand',
    uri: require('../../assets/flagpng/nz.png'),
  },
  {
    answer: [
      'Papua New Guinea',
      'Polynésie thuộc Pháp',
      'New Caledonia',
      'Vanuatu',
    ],
    correct: 1,
    id: 'PF',
    index: 178,
    name: 'Polynésie thuộc Pháp',
    uri: require('../../assets/flagpng/pf.png'),
  },
  {
    answer: ['Guam', 'Samoa', 'Papua New Guinea', 'Papua New Guinea'],
    correct: 2,
    id: 'PG',
    index: 179,
    name: 'Papua New Guinea',
    uri: require('../../assets/flagpng/pg.png'),
  },
  {
    answer: ['Vanuatu', 'Pitcairn', 'Cook Islands', 'Nauru'],
    correct: 1,
    id: 'PN',
    index: 184,
    name: 'Pitcairn',
    uri: require('../../assets/flagpng/pn.png'),
  },
  {
    answer: ['Vanuatu', 'Palau', 'Micronesia', 'Niue'],
    correct: 1,
    id: 'PW',
    index: 188,
    name: 'Palau',
    uri: require('../../assets/flagpng/pw.png'),
  },
  {
    answer: ['Samoa', 'Nauru', 'Quần đảo Bắc Mariana', 'Quần đảo Solomon'],
    correct: 3,
    id: 'SB',
    index: 197,
    name: 'Quần đảo Solomon',
    uri: require('../../assets/flagpng/sb.png'),
  },
  {
    answer: ['Quần đảo Solomon', 'American Samoa', 'Tokelau', 'Vanuatu'],
    correct: 2,
    id: 'TK',
    index: 223,
    name: 'Tokelau',
    uri: require('../../assets/flagpng/tk.png'),
  },
  {
    answer: ['New Zealand', 'Quần đảo Bắc Mariana', 'Tonga', 'Đông Timor'],
    correct: 3,
    id: 'TL',
    index: 224,
    name: 'Đông Timor',
    uri: require('../../assets/flagpng/tl.png'),
  },
  {
    answer: ['Tonga', 'Polynésie thuộc Pháp', 'Cook Islands', 'Tonga'],
    correct: 3,
    id: 'TO',
    index: 227,
    name: 'Tonga',
    uri: require('../../assets/flagpng/to.png'),
  },
  {
    answer: ['Úc', 'Tuvalu', 'Quần đảo Solomon', 'Tuvalu'],
    correct: 1,
    id: 'TV',
    index: 230,
    name: 'Tuvalu',
    uri: require('../../assets/flagpng/tv.png'),
  },
  {
    answer: ['Quần đảo Solomon', 'Vanuatu', 'Samoa', 'Fiji'],
    correct: 1,
    id: 'VU',
    index: 244,
    name: 'Vanuatu',
    uri: require('../../assets/flagpng/vu.png'),
  },
  {
    answer: [
      'Tuvalu',
      'Wallis và Futuna Islands',
      'Quần đảo Bắc Mariana',
      'Norfolk Island',
    ],
    correct: 1,
    id: 'WF',
    index: 245,
    name: 'Wallis và Futuna Islands',
    uri: require('../../assets/flagpng/wf.png'),
  },
  {
    answer: ['Tonga', 'Samoa', 'Quần đảo Bắc Mariana', 'Papua New Guinea'],
    correct: 1,
    id: 'WS',
    index: 246,
    name: 'Samoa',
    uri: require('../../assets/flagpng/ws.png'),
  },
];

export const DATAOCEANIA: Country[] = [
  {
    answer: ['Solomon Islands', 'Tuvalu', 'Australia', 'Australia'],
    correct: 2,
    id: 'AU',
    index: 8,
    name: 'Australia',
    uri: require('../../assets/flagpng/au.png'),
  },
  {
    answer: ['Tuvalu', 'Solomon Islands', 'Nauru', 'Fiji'],
    correct: 3,
    id: 'FJ',
    index: 58,
    name: 'Fiji',
    uri: require('../../assets/flagpng/fj.png'),
  },
  {
    answer: ['Australia', 'Kiribati', 'Tuvalu', 'Timor-Leste'],
    correct: 1,
    id: 'KI',
    index: 88,
    name: 'Kiribati',
    uri: require('../../assets/flagpng/ki.png'),
  },
  {
    answer: ['Samoa', 'Tuvalu', 'Marshall Islands', 'Nauru'],
    correct: 2,
    id: 'MH',
    index: 108,
    name: 'Marshall Islands',
    uri: require('../../assets/flagpng/mh.png'),
  },
  {
    answer: [
      'Palau',
      'Kiribati',
      'Micronesia (Federated States of)',
      'Vanuatu',
    ],
    correct: 2,
    id: 'FM',
    index: 112,
    name: 'Micronesia (Federated States of)',
    uri: require('../../assets/flagpng/fm.png'),
  },
  {
    answer: ['Tonga', 'Vanuatu', 'Australia', 'Nauru'],
    correct: 3,
    id: 'NR',
    index: 121,
    name: 'Nauru',
    uri: require('../../assets/flagpng/nr.png'),
  },
  {
    answer: ['Tuvalu', 'New Zealand', 'Fiji', 'Solomon Islands'],
    correct: 1,
    id: 'NZ',
    index: 124,
    name: 'New Zealand',
    uri: require('../../assets/flagpng/nz.png'),
  },
  {
    answer: ['Fiji', 'Vanuatu', 'Palau', 'Palau'],
    correct: 2,
    id: 'PW',
    index: 132,
    name: 'Palau',
    uri: require('../../assets/flagpng/pw.png'),
  },
  {
    answer: ['Australia', 'Tuvalu', 'Palau', 'Papua New Guinea'],
    correct: 3,
    id: 'PG',
    index: 134,
    name: 'Papua New Guinea',
    uri: require('../../assets/flagpng/pg.png'),
  },
  {
    answer: ['Marshall Islands', 'Tuvalu', 'Papua New Guinea', 'Samoa'],
    correct: 3,
    id: 'WS',
    index: 147,
    name: 'Samoa',
    uri: require('../../assets/flagpng/ws.png'),
  },
  {
    answer: ['Tuvalu', 'Nauru', 'Solomon Islands', 'Samoa'],
    correct: 2,
    id: 'SB',
    index: 158,
    name: 'Solomon Islands',
    uri: require('../../assets/flagpng/sb.png'),
  },
  {
    answer: ['Timor-Leste', 'Samoa', 'Tuvalu', 'Nauru'],
    correct: 0,
    id: 'TL',
    index: 172,
    name: 'Timor-Leste',
    uri: require('../../assets/flagpng/tl.png'),
  },
  {
    answer: ['Tuvalu', 'Tonga', 'New Zealand', 'Marshall Islands'],
    correct: 1,
    id: 'TO',
    index: 174,
    name: 'Tonga',
    uri: require('../../assets/flagpng/to.png'),
  },
  {
    answer: ['New Zealand', 'Tuvalu', 'Fiji', 'Tuvalu'],
    correct: 1,
    id: 'TV',
    index: 179,
    name: 'Tuvalu',
    uri: require('../../assets/flagpng/tv.png'),
  },
  {
    answer: ['Vanuatu', 'Vanuatu', 'Marshall Islands', 'New Zealand'],
    correct: 0,
    id: 'VU',
    index: 187,
    name: 'Vanuatu',
    uri: require('../../assets/flagpng/vu.png'),
  },
];
