export type country = {
  id: string;
  name: string;
  uri: any;
  answer: string[];
  correct: number;
  index: number;
};
export const DATAAFRICA: country[] = [
  {
    id: 'AO',
    name: 'Angola',
    uri: "require('../../assets/flagpng/AO.png)",
    answer: ['Rwanda', 'Benin', 'Angola', 'Zambia'],
    correct: 2,
    index: 7,
  },
  {
    id: 'BF',
    name: 'Burkina Faso',
    uri: "require('../../assets/flagpng/BF.png)",
    answer: ['Mauritius', 'Zambia', 'Burkina Faso', 'Benin'],
    correct: 2,
    index: 20,
  },
  {
    id: 'BI',
    name: 'Burundi',
    uri: "require('../../assets/flagpng/BI.png)",
    answer: ['Cộng hoà dân chủ Congo', 'Burundi', 'Mali', 'Tanzania'],
    correct: 1,
    index: 23,
  },
  {
    id: 'BJ',
    name: 'Benin',
    uri: "require('../../assets/flagpng/BJ.png)",
    answer: ['Cộng hoà Congo', 'Zambia', 'Benin', 'Lesotho'],
    correct: 2,
    index: 24,
  },
  {
    id: 'BW',
    name: 'Botswana',
    uri: "require('../../assets/flagpng/BW.png)",
    answer: ['Eritrea', 'Botswana', 'Swaziland', 'Kenya'],
    correct: 1,
    index: 33,
  },
  {
    id: 'CD',
    name: 'Cộng hoà dân chủ Congo',
    uri: "require('../../assets/flagpng/CD.png)",
    answer: ['Swaziland', 'Egypt', 'Cộng hoà dân chủ Congo', 'Niger'],
    correct: 2,
    index: 38,
  },
  {
    id: 'CF',
    name: 'Cộng hòa Trung Phi',
    uri: "require('../../assets/flagpng/CF.png)",
    answer: [
      'Ma-rốc',
      'Cộng hòa Trung Phi',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Angola',
    ],
    correct: 1,
    index: 39,
  },
  {
    id: 'CG',
    name: 'Cộng hoà Congo',
    uri: "require('../../assets/flagpng/CG.png)",
    answer: ['Bờ Biển Ngà', 'Cộng hoà Congo', 'Mauritius', 'Tanzania'],
    correct: 1,
    index: 40,
  },
  {
    id: 'CI',
    name: 'Bờ Biển Ngà',
    uri: "require('../../assets/flagpng/CI.png)",
    answer: ['Bờ Biển Ngà', 'Djibouti', 'Mayotte', 'Lesotho'],
    correct: 0,
    index: 42,
  },
  {
    id: 'CM',
    name: 'Cameroon',
    uri: "require('../../assets/flagpng/CM.png)",
    answer: ['Egypt', 'Cameroon', 'Seychelles', 'Nam Phi'],
    correct: 1,
    index: 45,
  },
  {
    id: 'CV',
    name: 'Cape Verde',
    uri: "require('../../assets/flagpng/CV.png)",
    answer: ['Zambia', 'Gabon', 'Cape Verde', 'Mali'],
    correct: 2,
    index: 50,
  },
  {
    id: 'DJ',
    name: 'Djibouti',
    uri: "require('../../assets/flagpng/DJ.png)",
    answer: ['South Sudan', 'Ethiopia', 'Djibouti', 'Réunion'],
    correct: 2,
    index: 56,
  },
  {
    id: 'DZ',
    name: 'Algeria',
    uri: "require('../../assets/flagpng/DZ.png)",
    answer: ['Chad', 'Liberia', 'Algeria', 'Algeria'],
    correct: 3,
    index: 60,
  },
  {
    id: 'EG',
    name: 'Egypt',
    uri: "require('../../assets/flagpng/EG.png)",
    answer: ['Djibouti', 'Somalia', 'Guinea-Bissau', 'Egypt'],
    correct: 3,
    index: 63,
  },
  {
    id: 'EH',
    name: 'Tây Sahara',
    uri: "require('../../assets/flagpng/EH.png)",
    answer: ['Mali', 'Algeria', 'Nam Phi', 'Tây Sahara'],
    correct: 3,
    index: 64,
  },
  {
    id: 'ER',
    name: 'Eritrea',
    uri: "require('../../assets/flagpng/ER.png)",
    answer: ['Chad', 'Gabon', 'Mali', 'Eritrea'],
    correct: 3,
    index: 65,
  },
  {
    id: 'ET',
    name: 'Ethiopia',
    uri: "require('../../assets/flagpng/ET.png)",
    answer: ['Eritrea', 'Ethiopia', 'Mauritania', 'Tanzania'],
    correct: 1,
    index: 67,
  },
  {
    id: 'GA',
    name: 'Gabon',
    uri: "require('../../assets/flagpng/GA.png)",
    answer: ['Gabon', 'Uganda', 'Bờ Biển Ngà', 'Liberia'],
    correct: 0,
    index: 75,
  },
  {
    id: 'GH',
    name: 'Ghana',
    uri: "require('../../assets/flagpng/GH.png)",
    answer: ['Cape Verde', 'Sierra Leone', 'Ghana', 'Malawi'],
    correct: 2,
    index: 85,
  },
  {
    id: 'GM',
    name: 'Gambia',
    uri: "require('../../assets/flagpng/GM.png)",
    answer: ['Burkina Faso', 'Mayotte', 'Gambia', 'Libya'],
    correct: 2,
    index: 88,
  },
  {
    id: 'GN',
    name: 'Guinea',
    uri: "require('../../assets/flagpng/GN.png)",
    answer: ['South Sudan', 'Guinea', 'Mauritius', 'Burundi'],
    correct: 1,
    index: 89,
  },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    uri: "require('../../assets/flagpng/GQ.png)",
    answer: ['Seychelles', 'Cape Verde', 'Senegal', 'Equatorial Guinea'],
    correct: 3,
    index: 91,
  },
  {
    id: 'GW',
    name: 'Guinea-Bissau',
    uri: "require('../../assets/flagpng/GW.png)",
    answer: ['Somalia', 'Mauritania', 'Botswana', 'Guinea-Bissau'],
    correct: 3,
    index: 96,
  },
  {
    id: 'KE',
    name: 'Kenya',
    uri: "require('../../assets/flagpng/KE.png)",
    answer: ['Togo', 'Mali', 'Kenya', 'Bờ Biển Ngà'],
    correct: 2,
    index: 118,
  },
  {
    id: 'KM',
    name: 'Comoros',
    uri: "require('../../assets/flagpng/KM.png)",
    answer: ['São Tomé và Príncipe', 'Egypt', 'Comoros', 'Liberia'],
    correct: 2,
    index: 122,
  },
  {
    id: 'LR',
    name: 'Liberia',
    uri: "require('../../assets/flagpng/LR.png)",
    answer: ['Comoros', 'Liberia', 'Cộng hoà Congo', 'Zambia'],
    correct: 1,
    index: 134,
  },
  {
    id: 'LS',
    name: 'Lesotho',
    uri: "require('../../assets/flagpng/LS.png)",
    answer: ['Lesotho', 'Nigeria', 'Tây Sahara', 'Togo'],
    correct: 0,
    index: 135,
  },
  {
    id: 'LY',
    name: 'Libya',
    uri: "require('../../assets/flagpng/LY.png)",
    answer: ['Sudan', 'Libya', 'Guinea', 'Benin'],
    correct: 1,
    index: 139,
  },
  {
    id: 'MA',
    name: 'Ma-rốc',
    uri: "require('../../assets/flagpng/MA.png)",
    answer: ['Burundi', 'Ma-rốc', 'Sudan', 'Liberia'],
    correct: 1,
    index: 140,
  },
  {
    id: 'MG',
    name: 'Madagascar',
    uri: "require('../../assets/flagpng/MG.png)",
    answer: ['Gabon', 'Madagascar', 'Comoros', 'Zambia'],
    correct: 1,
    index: 145,
  },
  {
    id: 'ML',
    name: 'Mali',
    uri: "require('../../assets/flagpng/ML.png)",
    answer: ['Uganda', 'Mali', 'Angola', 'Kenya'],
    correct: 1,
    index: 148,
  },
  {
    id: 'MR',
    name: 'Mauritania',
    uri: "require('../../assets/flagpng/MR.png)",
    answer: [
      'Saint Helena, Ascension và Tristan da Cunha',
      'Mauritania',
      'Ethiopia',
      'Seychelles',
    ],
    correct: 1,
    index: 154,
  },
  {
    id: 'MU',
    name: 'Mauritius',
    uri: "require('../../assets/flagpng/MU.png)",
    answer: ['Ethiopia', 'Mayotte', 'Mauritius', 'Lesotho'],
    correct: 2,
    index: 157,
  },
  {
    id: 'MW',
    name: 'Malawi',
    uri: "require('../../assets/flagpng/MW.png)",
    answer: ['Tunisia', 'Ethiopia', 'Ma-rốc', 'Malawi'],
    correct: 3,
    index: 159,
  },
  {
    id: 'MZ',
    name: 'Mozambique',
    uri: "require('../../assets/flagpng/MZ.png)",
    answer: ['Mozambique', 'Namibia', 'Somalia', 'Algeria'],
    correct: 0,
    index: 162,
  },
  {
    id: 'NA',
    name: 'Namibia',
    uri: "require('../../assets/flagpng/NA.png)",
    answer: ['Mali', 'Bờ Biển Ngà', 'Namibia', 'Chad'],
    correct: 2,
    index: 163,
  },
  {
    id: 'NE',
    name: 'Niger',
    uri: "require('../../assets/flagpng/NE.png)",
    answer: ['Sierra Leone', 'Niger', 'Burkina Faso', 'Madagascar'],
    correct: 1,
    index: 165,
  },
  {
    id: 'NG',
    name: 'Nigeria',
    uri: "require('../../assets/flagpng/NG.png)",
    answer: ['Guinea-Bissau', 'Zambia', 'Cộng hoà Congo', 'Nigeria'],
    correct: 3,
    index: 167,
  },
  {
    id: 'RE',
    name: 'Réunion',
    uri: "require('../../assets/flagpng/RE.png)",
    answer: ['Eritrea', 'Réunion', 'Mayotte', 'Namibia'],
    correct: 1,
    index: 191,
  },
  {
    id: 'RW',
    name: 'Rwanda',
    uri: "require('../../assets/flagpng/RW.png)",
    answer: ['Rwanda', 'Swaziland', 'Cameroon', 'Liberia'],
    correct: 0,
    index: 195,
  },
  {
    id: 'SC',
    name: 'Seychelles',
    uri: "require('../../assets/flagpng/SC.png)",
    answer: ['Seychelles', 'Mozambique', 'Zimbabwe', 'Ghana'],
    correct: 0,
    index: 198,
  },
  {
    id: 'SD',
    name: 'Sudan',
    uri: "require('../../assets/flagpng/SD.png)",
    answer: ['Sudan', 'Uganda', 'Tây Sahara', 'Guinea'],
    correct: 0,
    index: 199,
  },
  {
    id: 'SH',
    name: 'Saint Helena, Ascension và Tristan da Cunha',
    uri: "require('../../assets/flagpng/SH.png)",
    answer: [
      'Lesotho',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Sierra Leone',
      'Bờ Biển Ngà',
    ],
    correct: 1,
    index: 202,
  },
  {
    id: 'SL',
    name: 'Sierra Leone',
    uri: "require('../../assets/flagpng/SL.png)",
    answer: ['Mauritania', 'Eritrea', 'São Tomé và Príncipe', 'Sierra Leone'],
    correct: 3,
    index: 206,
  },
  {
    id: 'SN',
    name: 'Senegal',
    uri: "require('../../assets/flagpng/SN.png)",
    answer: ['Senegal', 'Senegal', 'Eritrea', 'Guinea-Bissau'],
    correct: 1,
    index: 208,
  },
  {
    id: 'SO',
    name: 'Somalia',
    uri: "require('../../assets/flagpng/SO.png)",
    answer: ['Niger', 'Somalia', 'Senegal', 'Botswana'],
    correct: 1,
    index: 209,
  },
  {
    id: 'SS',
    name: 'South Sudan',
    uri: "require('../../assets/flagpng/SS.png)",
    answer: [
      'Niger',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Cộng hoà Congo',
      'South Sudan',
    ],
    correct: 3,
    index: 211,
  },
  {
    id: 'ST',
    name: 'São Tomé và Príncipe',
    uri: "require('../../assets/flagpng/ST.png)",
    answer: ['Cộng hoà Congo', 'Madagascar', 'São Tomé và Príncipe', 'Mayotte'],
    correct: 2,
    index: 212,
  },
  {
    id: 'SZ',
    name: 'Swaziland',
    uri: "require('../../assets/flagpng/SZ.png)",
    answer: ['Ghana', 'Swaziland', 'Tanzania', 'Namibia'],
    correct: 1,
    index: 216,
  },
  {
    id: 'TD',
    name: 'Chad',
    uri: "require('../../assets/flagpng/TD.png)",
    answer: ['Liberia', 'Chad', 'Cape Verde', 'Senegal'],
    correct: 1,
    index: 218,
  },
  {
    id: 'TG',
    name: 'Togo',
    uri: "require('../../assets/flagpng/TG.png)",
    answer: ['Togo', 'Seychelles', 'Zambia', 'Gabon'],
    correct: 0,
    index: 220,
  },
  {
    id: 'TN',
    name: 'Tunisia',
    uri: "require('../../assets/flagpng/TN.png)",
    answer: ['Tunisia', 'Liberia', 'Burkina Faso', 'Tanzania'],
    correct: 0,
    index: 226,
  },
  {
    id: 'TZ',
    name: 'Tanzania',
    uri: "require('../../assets/flagpng/TZ.png)",
    answer: ['Malawi', 'Tây Sahara', 'Sudan', 'Tanzania'],
    correct: 3,
    index: 232,
  },
  {
    id: 'UG',
    name: 'Uganda',
    uri: "require('../../assets/flagpng/UG.png)",
    answer: ['Mauritania', 'Uganda', 'Sudan', 'Eritrea'],
    correct: 1,
    index: 234,
  },
  {
    id: 'YT',
    name: 'Mayotte',
    uri: "require('../../assets/flagpng/YT.png)",
    answer: ['Malawi', 'Tanzania', 'Botswana', 'Mayotte'],
    correct: 3,
    index: 249,
  },
  {
    id: 'ZA',
    name: 'Nam Phi',
    uri: "require('../../assets/flagpng/ZA.png)",
    answer: ['Nam Phi', 'Tunisia', 'Equatorial Guinea', 'Gambia'],
    correct: 0,
    index: 250,
  },
  {
    id: 'ZM',
    name: 'Zambia',
    uri: "require('../../assets/flagpng/ZM.png)",
    answer: ['Cộng hoà Congo', 'Uganda', 'Guinea-Bissau', 'Zambia'],
    correct: 3,
    index: 251,
  },
  {
    id: 'ZW',
    name: 'Zimbabwe',
    uri: "require('../../assets/flagpng/ZW.png)",
    answer: [
      'Rwanda',
      'Zimbabwe',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Eritrea',
    ],
    correct: 1,
    index: 252,
  },
];
