export type country = {
  id: string;
  name: string;
  uri: any;
  answer: string[];
  correct: number;
  index: number;
};
export const DATAVI195: country[] = [
  {
    id: 'AD',
    name: 'Andorra',
    uri: "require('../../assets/flagpng/AD.png)",
    answer: ['Andorra', 'Belarus', 'Mauritius', 'Việt Nam'],
    correct: 0,
    index: 0,
  },
  {
    id: 'AE',
    name: 'Các tiểu vương quốc Ả Rập Thống nhất',
    uri: "require('../../assets/flagpng/AE.png)",
    answer: [
      'Vương quốc Anh',
      'Việt Nam',
      'Mexico',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 3,
    index: 1,
  },
  {
    id: 'AF',
    name: 'Afghanistan',
    uri: "require('../../assets/flagpng/AF.png)",
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Papua New Guinea',
      'Afghanistan',
      'Iceland',
    ],
    correct: 2,
    index: 2,
  },
  {
    id: 'AG',
    name: 'Antigua và Barbuda',
    uri: "require('../../assets/flagpng/AG.png)",
    answer: ['Comoros', 'Vanuatu', 'Djibouti', 'Antigua và Barbuda'],
    correct: 3,
    index: 3,
  },
  {
    id: 'AL',
    name: 'Albania',
    uri: "require('../../assets/flagpng/AL.png)",
    answer: ['Samoa', 'Chile', 'Albania', 'Saint Kitts và Nevis'],
    correct: 2,
    index: 5,
  },
  {
    id: 'AM',
    name: 'Armenia',
    uri: "require('../../assets/flagpng/AM.png)",
    answer: ['Campuchia', 'Thailand', 'Armenia', 'Georgia'],
    correct: 2,
    index: 6,
  },
  {
    id: 'AO',
    name: 'Angola',
    uri: "require('../../assets/flagpng/AO.png)",
    answer: [
      'Brunei Darussalam',
      'Saint Vincent và Grenadines',
      'Lithuania',
      'Angola',
    ],
    correct: 3,
    index: 7,
  },
  {
    id: 'AR',
    name: 'Argentina',
    uri: "require('../../assets/flagpng/AR.png)",
    answer: ['Nauru', 'Argentina', 'Maldives', 'Bhutan'],
    correct: 1,
    index: 9,
  },
  {
    id: 'AT',
    name: 'Áo',
    uri: "require('../../assets/flagpng/AT.png)",
    answer: ['Ukraine', 'Mongolia', 'Albania', 'Áo'],
    correct: 3,
    index: 11,
  },
  {
    id: 'AU',
    name: 'Úc',
    uri: "require('../../assets/flagpng/AU.png)",
    answer: ['Marshall Islands', 'Úc', 'Georgia', 'Tajikistan'],
    correct: 1,
    index: 12,
  },
  {
    id: 'AZ',
    name: 'Azerbaijan',
    uri: "require('../../assets/flagpng/AZ.png)",
    answer: ['South Sudan', 'Maldives', 'Azerbaijan', 'Bolivia'],
    correct: 2,
    index: 15,
  },
  {
    id: 'BA',
    name: 'Bosnia và Herzegovina',
    uri: "require('../../assets/flagpng/BA.png)",
    answer: ['Thổ Nhĩ Kỳ', 'Bosnia và Herzegovina', 'Gabon', 'Moldova'],
    correct: 1,
    index: 16,
  },
  {
    id: 'BB',
    name: 'Barbados',
    uri: "require('../../assets/flagpng/BB.png)",
    answer: ['Pakistan', 'Áo', 'Barbados', 'Indonesia'],
    correct: 2,
    index: 17,
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    uri: "require('../../assets/flagpng/BD.png)",
    answer: ['Bangladesh', 'Zambia', 'Phần Lan', 'Liberia'],
    correct: 0,
    index: 18,
  },
  {
    id: 'BE',
    name: 'Bỉ',
    uri: "require('../../assets/flagpng/BE.png)",
    answer: ['Hy Lạp', 'Serbia', 'Bỉ', 'Cộng hòa Dominica'],
    correct: 2,
    index: 19,
  },
  {
    id: 'BF',
    name: 'Burkina Faso',
    uri: "require('../../assets/flagpng/BF.png)",
    answer: ['Vương quốc Anh', 'Lesotho', 'Burkina Faso', 'Thailand'],
    correct: 2,
    index: 20,
  },
  {
    id: 'BG',
    name: 'Bulgaria',
    uri: "require('../../assets/flagpng/BG.png)",
    answer: ['Bulgaria', 'Lào', 'Grenada', 'Zambia'],
    correct: 0,
    index: 21,
  },
  {
    id: 'BH',
    name: 'Bahrain',
    uri: "require('../../assets/flagpng/BH.png)",
    answer: ['Suriname', 'Bahrain', 'Lào', 'Séc'],
    correct: 1,
    index: 22,
  },
  {
    id: 'BI',
    name: 'Burundi',
    uri: "require('../../assets/flagpng/BI.png)",
    answer: ['Lesotho', 'Estonia', 'Tuvalu', 'Burundi'],
    correct: 3,
    index: 23,
  },
  {
    id: 'BJ',
    name: 'Benin',
    uri: "require('../../assets/flagpng/BJ.png)",
    answer: ['Liechtenstein', 'Bahamas', 'Tuvalu', 'Benin'],
    correct: 3,
    index: 24,
  },
  {
    id: 'BN',
    name: 'Brunei Darussalam',
    uri: "require('../../assets/flagpng/BN.png)",
    answer: ['Đông Timor', 'Cameroon', 'Brunei Darussalam', 'Italy'],
    correct: 2,
    index: 27,
  },
  {
    id: 'BO',
    name: 'Bolivia',
    uri: "require('../../assets/flagpng/BO.png)",
    answer: ['Nepal', 'Saint Kitts và Nevis', 'Brunei Darussalam', 'Bolivia'],
    correct: 3,
    index: 28,
  },
  {
    id: 'BR',
    name: 'Brazil',
    uri: "require('../../assets/flagpng/BR.png)",
    answer: ['Indonesia', 'Brazil', 'Belize', 'Nepal'],
    correct: 1,
    index: 29,
  },
  {
    id: 'BS',
    name: 'Bahamas',
    uri: "require('../../assets/flagpng/BS.png)",
    answer: ['Ấn Độ', 'Bahamas', 'Trung Quốc', 'Togo'],
    correct: 1,
    index: 30,
  },
  {
    id: 'BT',
    name: 'Bhutan',
    uri: "require('../../assets/flagpng/BT.png)",
    answer: ['Bhutan', 'Syria', 'Nicaragua', 'Colombia'],
    correct: 0,
    index: 31,
  },
  {
    id: 'BW',
    name: 'Botswana',
    uri: "require('../../assets/flagpng/BW.png)",
    answer: ['Tajikistan', 'Botswana', 'Ghana', 'Liberia'],
    correct: 1,
    index: 33,
  },
  {
    id: 'BY',
    name: 'Belarus',
    uri: "require('../../assets/flagpng/BY.png)",
    answer: ['Malawi', 'Trung Quốc', 'Swaziland', 'Belarus'],
    correct: 3,
    index: 34,
  },
  {
    id: 'BZ',
    name: 'Belize',
    uri: "require('../../assets/flagpng/BZ.png)",
    answer: ['Ba Lan', 'Gambia', 'Belize', 'Lithuania'],
    correct: 2,
    index: 35,
  },
  {
    id: 'CA',
    name: 'Canada',
    uri: "require('../../assets/flagpng/CA.png)",
    answer: ['Andorra', 'Canada', 'Saint Lucia', 'Yemen'],
    correct: 1,
    index: 36,
  },
  {
    id: 'CD',
    name: 'Cộng hoà dân chủ Congo',
    uri: "require('../../assets/flagpng/CD.png)",
    answer: ['Argentina', 'Cộng hoà dân chủ Congo', 'Senegal', 'Guyana'],
    correct: 1,
    index: 38,
  },
  {
    id: 'CF',
    name: 'Cộng hòa Trung Phi',
    uri: "require('../../assets/flagpng/CF.png)",
    answer: ['Panama', 'Moldova', 'Cộng hòa Trung Phi', 'Cộng hòa Trung Phi'],
    correct: 2,
    index: 39,
  },
  {
    id: 'CG',
    name: 'Cộng hoà Congo',
    uri: "require('../../assets/flagpng/CG.png)",
    answer: [
      'Quần đảo Solomon',
      'Cộng hoà Congo',
      'Indonesia',
      'Vương quốc Anh',
    ],
    correct: 1,
    index: 40,
  },
  {
    id: 'CH',
    name: 'Thụy Sỹ',
    uri: "require('../../assets/flagpng/CH.png)",
    answer: ['Thụy Sỹ', 'Hy Lạp', 'Bulgaria', 'Uruguay'],
    correct: 0,
    index: 41,
  },
  {
    id: 'CI',
    name: 'Bờ Biển Ngà',
    uri: "require('../../assets/flagpng/CI.png)",
    answer: ['Bờ Biển Ngà', 'Pakistan', 'Canada', 'Mexico'],
    correct: 0,
    index: 42,
  },
  {
    id: 'CL',
    name: 'Chile',
    uri: "require('../../assets/flagpng/CL.png)",
    answer: ['Chile', 'Moldova', 'Brunei Darussalam', 'Mỹ (Hoa Kỳ)'],
    correct: 0,
    index: 44,
  },
  {
    id: 'CM',
    name: 'Cameroon',
    uri: "require('../../assets/flagpng/CM.png)",
    answer: ['Cameroon', 'Estonia', 'Thailand', 'Jordan'],
    correct: 0,
    index: 45,
  },
  {
    id: 'CN',
    name: 'Trung Quốc',
    uri: "require('../../assets/flagpng/CN.png)",
    answer: ['Trung Quốc', 'Sudan', 'Luxembourg', 'Brunei Darussalam'],
    correct: 0,
    index: 46,
  },
  {
    id: 'CO',
    name: 'Colombia',
    uri: "require('../../assets/flagpng/CO.png)",
    answer: ['Nam Phi', 'Chile', 'Colombia', 'Equatorial Guinea'],
    correct: 2,
    index: 47,
  },
  {
    id: 'CR',
    name: 'Costa Rica',
    uri: "require('../../assets/flagpng/CR.png)",
    answer: ['Costa Rica', 'Mexico', 'Suriname', 'Úc'],
    correct: 0,
    index: 48,
  },
  {
    id: 'CU',
    name: 'Cuba',
    uri: "require('../../assets/flagpng/CU.png)",
    answer: ['Thailand', 'Cuba', 'Cuba', 'Comoros'],
    correct: 1,
    index: 49,
  },
  {
    id: 'CV',
    name: 'Cape Verde',
    uri: "require('../../assets/flagpng/CV.png)",
    answer: ['Áo', 'Cape Verde', 'Ả Rập Xê Út', 'Luxembourg'],
    correct: 1,
    index: 50,
  },
  {
    id: 'CY',
    name: 'Đảo Síp',
    uri: "require('../../assets/flagpng/CY.png)",
    answer: ['Đảo Síp', 'Syria', 'Séc', 'Lào'],
    correct: 0,
    index: 53,
  },
  {
    id: 'CZ',
    name: 'Séc',
    uri: "require('../../assets/flagpng/CZ.png)",
    answer: ['Nhật Bản', 'Slovakia', 'Denmark', 'Séc'],
    correct: 3,
    index: 54,
  },
  {
    id: 'DE',
    name: 'Đức',
    uri: "require('../../assets/flagpng/DE.png)",
    answer: ['Liechtenstein', 'Albania', 'Đức', 'Uruguay'],
    correct: 2,
    index: 55,
  },
  {
    id: 'DJ',
    name: 'Djibouti',
    uri: "require('../../assets/flagpng/DJ.png)",
    answer: [
      'Swaziland',
      'Mauritania',
      'Djibouti',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 2,
    index: 56,
  },
  {
    id: 'DK',
    name: 'Denmark',
    uri: "require('../../assets/flagpng/DK.png)",
    answer: ['Trinidad và Tobago', 'Denmark', 'Liberia', 'Colombia'],
    correct: 1,
    index: 57,
  },
  {
    id: 'DM',
    name: 'Dominica',
    uri: "require('../../assets/flagpng/DM.png)",
    answer: ['Somalia', 'Dominica', 'Estonia', 'Lithuania'],
    correct: 1,
    index: 58,
  },
  {
    id: 'DO',
    name: 'Cộng hòa Dominica',
    uri: "require('../../assets/flagpng/DO.png)",
    answer: [
      'Ukraine',
      'Cộng hòa Dominica',
      'Marshall Islands',
      'Cộng hoà Congo',
    ],
    correct: 1,
    index: 59,
  },
  {
    id: 'DZ',
    name: 'Algeria',
    uri: "require('../../assets/flagpng/DZ.png)",
    answer: ['Kiribati', 'Suriname', 'Azerbaijan', 'Algeria'],
    correct: 3,
    index: 60,
  },
  {
    id: 'EC',
    name: 'Ecuador',
    uri: "require('../../assets/flagpng/EC.png)",
    answer: ['Ecuador', 'Belize', 'Thổ Nhĩ Kỳ', 'Hungary'],
    correct: 0,
    index: 61,
  },
  {
    id: 'EE',
    name: 'Estonia',
    uri: "require('../../assets/flagpng/EE.png)",
    answer: ['Estonia', 'Portugal', 'Vương quốc Anh', 'Equatorial Guinea'],
    correct: 0,
    index: 62,
  },
  {
    id: 'EG',
    name: 'Egypt',
    uri: "require('../../assets/flagpng/EG.png)",
    answer: ['Egypt', 'Botswana', 'Papua New Guinea', 'Lesotho'],
    correct: 0,
    index: 63,
  },
  {
    id: 'ER',
    name: 'Eritrea',
    uri: "require('../../assets/flagpng/ER.png)",
    answer: ['Jordan', 'Bỉ', 'Nga', 'Eritrea'],
    correct: 3,
    index: 65,
  },
  {
    id: 'ES',
    name: 'Tây Ban Nha',
    uri: "require('../../assets/flagpng/ES.png)",
    answer: ['Kyrgyzstan', 'Tây Ban Nha', 'Tây Ban Nha', 'Venezuela'],
    correct: 1,
    index: 66,
  },
  {
    id: 'ET',
    name: 'Ethiopia',
    uri: "require('../../assets/flagpng/ET.png)",
    answer: ['Eritrea', 'Ethiopia', 'Uganda', 'Sri Lanka'],
    correct: 1,
    index: 67,
  },
  {
    id: 'FI',
    name: 'Phần Lan',
    uri: "require('../../assets/flagpng/FI.png)",
    answer: ['Phần Lan', 'Cộng hòa Dominica', 'Rwanda', 'Kuwait'],
    correct: 0,
    index: 69,
  },
  {
    id: 'FJ',
    name: 'Fiji',
    uri: "require('../../assets/flagpng/FJ.png)",
    answer: ['Samoa', 'Bờ Biển Ngà', 'Montenegro', 'Fiji'],
    correct: 3,
    index: 70,
  },
  {
    id: 'FM',
    name: 'Micronesia',
    uri: "require('../../assets/flagpng/FM.png)",
    answer: ['Micronesia', 'Phần Lan', 'Kyrgyzstan', 'Quần đảo Solomon'],
    correct: 0,
    index: 72,
  },
  {
    id: 'FR',
    name: 'Pháp',
    uri: "require('../../assets/flagpng/FR.png)",
    answer: ['Pháp', 'Honduras', 'Pakistan', 'Brazil'],
    correct: 0,
    index: 74,
  },
  {
    id: 'GA',
    name: 'Gabon',
    uri: "require('../../assets/flagpng/GA.png)",
    answer: ['Monaco', 'Cộng hoà dân chủ Congo', 'Slovenia', 'Gabon'],
    correct: 3,
    index: 75,
  },
  {
    id: 'GB',
    name: 'Vương quốc Anh',
    uri: "require('../../assets/flagpng/GB.png)",
    answer: ['Vương quốc Anh', 'Bhutan', 'Suriname', 'Saint Lucia'],
    correct: 0,
    index: 80,
  },
  {
    id: 'GD',
    name: 'Grenada',
    uri: "require('../../assets/flagpng/GD.png)",
    answer: ['Grenada', 'Liberia', 'Suriname', 'Bahamas'],
    correct: 0,
    index: 81,
  },
  {
    id: 'GE',
    name: 'Georgia',
    uri: "require('../../assets/flagpng/GE.png)",
    answer: ['São Tomé và Príncipe', 'Nigeria', 'Georgia', 'Bolivia'],
    correct: 2,
    index: 82,
  },
  {
    id: 'GH',
    name: 'Ghana',
    uri: "require('../../assets/flagpng/GH.png)",
    answer: ['Iraq', 'Ghana', 'Egypt', 'Chad'],
    correct: 1,
    index: 85,
  },
  {
    id: 'GM',
    name: 'Gambia',
    uri: "require('../../assets/flagpng/GM.png)",
    answer: ['Gambia', 'Costa Rica', 'Guinea-Bissau', 'South Sudan'],
    correct: 0,
    index: 88,
  },
  {
    id: 'GN',
    name: 'Guinea',
    uri: "require('../../assets/flagpng/GN.png)",
    answer: ['Úc', 'El Salvador', 'Hungary', 'Guinea'],
    correct: 3,
    index: 89,
  },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    uri: "require('../../assets/flagpng/GQ.png)",
    answer: ['Guatemala', 'Burkina Faso', 'Togo', 'Equatorial Guinea'],
    correct: 3,
    index: 91,
  },
  {
    id: 'GR',
    name: 'Hy Lạp',
    uri: "require('../../assets/flagpng/GR.png)",
    answer: ['Hy Lạp', 'Tuvalu', 'Guinea-Bissau', 'Thụy Sỹ'],
    correct: 0,
    index: 92,
  },
  {
    id: 'GT',
    name: 'Guatemala',
    uri: "require('../../assets/flagpng/GT.png)",
    answer: ['Pakistan', 'Hà Lan', 'Guatemala', 'Belarus'],
    correct: 2,
    index: 94,
  },
  {
    id: 'GW',
    name: 'Guinea-Bissau',
    uri: "require('../../assets/flagpng/GW.png)",
    answer: ['Ecuador', 'Uzbekistan', 'Niger', 'Guinea-Bissau'],
    correct: 3,
    index: 96,
  },
  {
    id: 'GY',
    name: 'Guyana',
    uri: "require('../../assets/flagpng/GY.png)",
    answer: ['Guyana', 'Mauritania', 'Vanuatu', 'Djibouti'],
    correct: 0,
    index: 97,
  },
  {
    id: 'HN',
    name: 'Honduras',
    uri: "require('../../assets/flagpng/HN.png)",
    answer: ['Honduras', 'Guinea-Bissau', 'Oman', 'Séc'],
    correct: 0,
    index: 100,
  },
  {
    id: 'HR',
    name: 'Croatia',
    uri: "require('../../assets/flagpng/HR.png)",
    answer: ['Croatia', 'San Marino', 'Antigua và Barbuda', 'Mozambique'],
    correct: 0,
    index: 101,
  },
  {
    id: 'HT',
    name: 'Haiti',
    uri: "require('../../assets/flagpng/HT.png)",
    answer: ['Bỉ', 'Italy', 'Haiti', 'Tajikistan'],
    correct: 2,
    index: 102,
  },
  {
    id: 'HU',
    name: 'Hungary',
    uri: "require('../../assets/flagpng/HU.png)",
    answer: ['Hungary', 'Antigua và Barbuda', 'Latvia', 'El Salvador'],
    correct: 0,
    index: 103,
  },
  {
    id: 'ID',
    name: 'Indonesia',
    uri: "require('../../assets/flagpng/ID.png)",
    answer: ['Peru', 'Georgia', 'Indonesia', 'Mozambique'],
    correct: 2,
    index: 104,
  },
  {
    id: 'IE',
    name: 'Ireland',
    uri: "require('../../assets/flagpng/IE.png)",
    answer: ['Ireland', 'Uganda', 'Albania', 'Iceland'],
    correct: 0,
    index: 105,
  },
  {
    id: 'IL',
    name: 'Israel',
    uri: "require('../../assets/flagpng/IL.png)",
    answer: ['Rwanda', 'Croatia', 'Barbados', 'Israel'],
    correct: 3,
    index: 106,
  },
  {
    id: 'IN',
    name: 'Ấn Độ',
    uri: "require('../../assets/flagpng/IN.png)",
    answer: ['Romania', 'Ấn Độ', 'Albania', 'Madagascar'],
    correct: 1,
    index: 108,
  },
  {
    id: 'IQ',
    name: 'Iraq',
    uri: "require('../../assets/flagpng/IQ.png)",
    answer: ['Bosnia và Herzegovina', 'Iraq', 'Zimbabwe', 'Guinea'],
    correct: 1,
    index: 110,
  },
  {
    id: 'IR',
    name: 'Iran',
    uri: "require('../../assets/flagpng/IR.png)",
    answer: ['Gabon', 'Italy', 'Iran', 'Palau'],
    correct: 2,
    index: 111,
  },
  {
    id: 'IS',
    name: 'Iceland',
    uri: "require('../../assets/flagpng/IS.png)",
    answer: ['Iceland', 'Bờ Biển Ngà', 'Oman', 'Campuchia'],
    correct: 0,
    index: 112,
  },
  {
    id: 'IT',
    name: 'Italy',
    uri: "require('../../assets/flagpng/IT.png)",
    answer: ['Albania', 'Italy', 'Campuchia', 'Papua New Guinea'],
    correct: 1,
    index: 113,
  },
  {
    id: 'JM',
    name: 'Jamaica',
    uri: "require('../../assets/flagpng/JM.png)",
    answer: ['Guyana', 'Jamaica', 'Thụy Điển', 'Afghanistan'],
    correct: 1,
    index: 115,
  },
  {
    id: 'JO',
    name: 'Jordan',
    uri: "require('../../assets/flagpng/JO.png)",
    answer: ['Malaysia', 'Jordan', 'Đảo Síp', 'Philippines'],
    correct: 1,
    index: 116,
  },
  {
    id: 'JP',
    name: 'Nhật Bản',
    uri: "require('../../assets/flagpng/JP.png)",
    answer: ['Hy Lạp', 'Micronesia', 'Ba Lan', 'Nhật Bản'],
    correct: 3,
    index: 117,
  },
  {
    id: 'KE',
    name: 'Kenya',
    uri: "require('../../assets/flagpng/KE.png)",
    answer: ['Séc', 'Kenya', 'Mali', 'Slovenia'],
    correct: 1,
    index: 118,
  },
  {
    id: 'KG',
    name: 'Kyrgyzstan',
    uri: "require('../../assets/flagpng/KG.png)",
    answer: ['Kyrgyzstan', 'Estonia', 'Jamaica', 'Thụy Điển'],
    correct: 0,
    index: 119,
  },
  {
    id: 'KH',
    name: 'Campuchia',
    uri: "require('../../assets/flagpng/KH.png)",
    answer: ['Campuchia', 'Thổ Nhĩ Kỳ', 'Belize', 'Latvia'],
    correct: 0,
    index: 120,
  },
  {
    id: 'KI',
    name: 'Kiribati',
    uri: "require('../../assets/flagpng/KI.png)",
    answer: ['South Sudan', 'Denmark', 'Kiribati', 'Hà Lan'],
    correct: 2,
    index: 121,
  },
  {
    id: 'KM',
    name: 'Comoros',
    uri: "require('../../assets/flagpng/KM.png)",
    answer: ['Comoros', 'Gabon', 'Papua New Guinea', 'North Macedonia'],
    correct: 0,
    index: 122,
  },
  {
    id: 'KN',
    name: 'Saint Kitts và Nevis',
    uri: "require('../../assets/flagpng/KN.png)",
    answer: ['Saint Kitts và Nevis', 'Thụy Sỹ', 'Guyana', 'Tuvalu'],
    correct: 0,
    index: 123,
  },
  {
    id: 'KP',
    name: 'Triều Tiên',
    uri: "require('../../assets/flagpng/KP.png)",
    answer: ['Ả Rập Xê Út', 'Maldives', 'Egypt', 'Triều Tiên'],
    correct: 3,
    index: 124,
  },
  {
    id: 'KR',
    name: 'Hàn Quốc',
    uri: "require('../../assets/flagpng/KR.png)",
    answer: ['Saint Kitts và Nevis', 'Swaziland', 'Bhutan', 'Hàn Quốc'],
    correct: 3,
    index: 125,
  },
  {
    id: 'KW',
    name: 'Kuwait',
    uri: "require('../../assets/flagpng/KW.png)",
    answer: ['Tajikistan', 'Hà Lan', 'Kuwait', 'Gambia'],
    correct: 2,
    index: 126,
  },
  {
    id: 'KZ',
    name: 'Kazakhstan',
    uri: "require('../../assets/flagpng/KZ.png)",
    answer: ['Cuba', 'Uzbekistan', 'Li-băng', 'Kazakhstan'],
    correct: 3,
    index: 128,
  },
  {
    id: 'LA',
    name: 'Lào',
    uri: "require('../../assets/flagpng/LA.png)",
    answer: ['Lào', 'Ả Rập Xê Út', 'Cameroon', 'Israel'],
    correct: 0,
    index: 129,
  },
  {
    id: 'LB',
    name: 'Li-băng',
    uri: "require('../../assets/flagpng/LB.png)",
    answer: ['Namibia', 'Cộng hoà dân chủ Congo', 'Li-băng', 'Senegal'],
    correct: 2,
    index: 130,
  },
  {
    id: 'LC',
    name: 'Saint Lucia',
    uri: "require('../../assets/flagpng/LC.png)",
    answer: ['Saint Lucia', 'Peru', 'Cameroon', 'Libya'],
    correct: 0,
    index: 131,
  },
  {
    id: 'LI',
    name: 'Liechtenstein',
    uri: "require('../../assets/flagpng/LI.png)",
    answer: ['Liechtenstein', 'Yemen', 'Bosnia và Herzegovina', 'Mali'],
    correct: 0,
    index: 132,
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    uri: "require('../../assets/flagpng/LK.png)",
    answer: ['Ireland', 'Sri Lanka', 'Antigua và Barbuda', 'Somalia'],
    correct: 1,
    index: 133,
  },
  {
    id: 'LR',
    name: 'Liberia',
    uri: "require('../../assets/flagpng/LR.png)",
    answer: ['Jamaica', 'Ả Rập Xê Út', 'Liberia', 'Fiji'],
    correct: 2,
    index: 134,
  },
  {
    id: 'LS',
    name: 'Lesotho',
    uri: "require('../../assets/flagpng/LS.png)",
    answer: ['Việt Nam', 'Indonesia', 'Lesotho', 'Bỉ'],
    correct: 2,
    index: 135,
  },
  {
    id: 'LT',
    name: 'Lithuania',
    uri: "require('../../assets/flagpng/LT.png)",
    answer: ['Suriname', 'Ghana', 'Lithuania', 'Malaysia'],
    correct: 2,
    index: 136,
  },
  {
    id: 'LU',
    name: 'Luxembourg',
    uri: "require('../../assets/flagpng/LU.png)",
    answer: ['Bolivia', 'Luxembourg', 'Ma-rốc', 'Oman'],
    correct: 1,
    index: 137,
  },
  {
    id: 'LV',
    name: 'Latvia',
    uri: "require('../../assets/flagpng/LV.png)",
    answer: ['Thổ Nhĩ Kỳ', 'Myanmar', 'Afghanistan', 'Latvia'],
    correct: 3,
    index: 138,
  },
  {
    id: 'LY',
    name: 'Libya',
    uri: "require('../../assets/flagpng/LY.png)",
    answer: ['Comoros', 'Vanuatu', 'Libya', 'Costa Rica'],
    correct: 2,
    index: 139,
  },
  {
    id: 'MA',
    name: 'Ma-rốc',
    uri: "require('../../assets/flagpng/MA.png)",
    answer: ['Ma-rốc', 'Saint Kitts và Nevis', 'Tajikistan', 'Benin'],
    correct: 0,
    index: 140,
  },
  {
    id: 'MC',
    name: 'Monaco',
    uri: "require('../../assets/flagpng/MC.png)",
    answer: ['Andorra', 'Luxembourg', 'Monaco', 'Qatar'],
    correct: 2,
    index: 141,
  },
  {
    id: 'MD',
    name: 'Moldova',
    uri: "require('../../assets/flagpng/MD.png)",
    answer: ['Moldova', 'Samoa', 'Jamaica', 'Tây Ban Nha'],
    correct: 0,
    index: 142,
  },
  {
    id: 'ME',
    name: 'Montenegro',
    uri: "require('../../assets/flagpng/ME.png)",
    answer: ['Gabon', 'Montenegro', 'Kyrgyzstan', 'New Zealand'],
    correct: 1,
    index: 143,
  },
  {
    id: 'MG',
    name: 'Madagascar',
    uri: "require('../../assets/flagpng/MG.png)",
    answer: ['Azerbaijan', 'Equatorial Guinea', 'Togo', 'Madagascar'],
    correct: 3,
    index: 145,
  },
  {
    id: 'MH',
    name: 'Marshall Islands',
    uri: "require('../../assets/flagpng/MH.png)",
    answer: ['Cộng hoà Congo', 'Marshall Islands', 'Jamaica', 'San Marino'],
    correct: 1,
    index: 146,
  },
  {
    id: 'MK',
    name: 'North Macedonia',
    uri: "require('../../assets/flagpng/MK.png)",
    answer: ['New Zealand', 'North Macedonia', 'Belize', 'Lào'],
    correct: 1,
    index: 147,
  },
  {
    id: 'ML',
    name: 'Mali',
    uri: "require('../../assets/flagpng/ML.png)",
    answer: ['Vanuatu', 'Mali', 'Ấn Độ', 'Cộng hòa Trung Phi'],
    correct: 1,
    index: 148,
  },
  {
    id: 'MM',
    name: 'Myanmar',
    uri: "require('../../assets/flagpng/MM.png)",
    answer: ['Kazakhstan', 'New Zealand', 'Myanmar', 'Bờ Biển Ngà'],
    correct: 2,
    index: 149,
  },
  {
    id: 'MN',
    name: 'Mongolia',
    uri: "require('../../assets/flagpng/MN.png)",
    answer: ['Mongolia', 'Malaysia', 'Sierra Leone', 'Micronesia'],
    correct: 0,
    index: 150,
  },
  {
    id: 'MR',
    name: 'Mauritania',
    uri: "require('../../assets/flagpng/MR.png)",
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Madagascar',
      'Tajikistan',
      'Mauritania',
    ],
    correct: 3,
    index: 154,
  },
  {
    id: 'MT',
    name: 'Malta',
    uri: "require('../../assets/flagpng/MT.png)",
    answer: ['Triều Tiên', 'Cameroon', 'Malta', 'Rwanda'],
    correct: 2,
    index: 156,
  },
  {
    id: 'MU',
    name: 'Mauritius',
    uri: "require('../../assets/flagpng/MU.png)",
    answer: ['Mauritius', 'Kuwait', 'Rwanda', 'Bờ Biển Ngà'],
    correct: 0,
    index: 157,
  },
  {
    id: 'MV',
    name: 'Maldives',
    uri: "require('../../assets/flagpng/MV.png)",
    answer: [
      'Lithuania',
      'El Salvador',
      'Maldives',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 2,
    index: 158,
  },
  {
    id: 'MW',
    name: 'Malawi',
    uri: "require('../../assets/flagpng/MW.png)",
    answer: ['Cộng hoà Congo', 'Malawi', 'Namibia', 'Yemen'],
    correct: 1,
    index: 159,
  },
  {
    id: 'MX',
    name: 'Mexico',
    uri: "require('../../assets/flagpng/MX.png)",
    answer: ['Mexico', 'Tajikistan', 'Guatemala', 'Pháp'],
    correct: 0,
    index: 160,
  },
  {
    id: 'MY',
    name: 'Malaysia',
    uri: "require('../../assets/flagpng/MY.png)",
    answer: ['Burundi', 'Saint Vincent và Grenadines', 'Malaysia', 'Italy'],
    correct: 2,
    index: 161,
  },
  {
    id: 'MZ',
    name: 'Mozambique',
    uri: "require('../../assets/flagpng/MZ.png)",
    answer: ['Mozambique', 'Italy', 'Ecuador', 'San Marino'],
    correct: 0,
    index: 162,
  },
  {
    id: 'NA',
    name: 'Namibia',
    uri: "require('../../assets/flagpng/NA.png)",
    answer: ['Namibia', 'Mỹ (Hoa Kỳ)', 'Cộng hòa Dominica', 'Italy'],
    correct: 0,
    index: 163,
  },
  {
    id: 'NE',
    name: 'Niger',
    uri: "require('../../assets/flagpng/NE.png)",
    answer: ['Niger', 'Bờ Biển Ngà', 'Nigeria', 'Sierra Leone'],
    correct: 0,
    index: 165,
  },
  {
    id: 'NG',
    name: 'Nigeria',
    uri: "require('../../assets/flagpng/NG.png)",
    answer: ['Turkmenistan', 'Niger', 'Nigeria', 'Burkina Faso'],
    correct: 2,
    index: 167,
  },
  {
    id: 'NI',
    name: 'Nicaragua',
    uri: "require('../../assets/flagpng/NI.png)",
    answer: ['Luxembourg', 'Papua New Guinea', 'Nicaragua', 'Micronesia'],
    correct: 2,
    index: 168,
  },
  {
    id: 'NL',
    name: 'Hà Lan',
    uri: "require('../../assets/flagpng/NL.png)",
    answer: ['Hungary', 'Bangladesh', 'Saint Vincent và Grenadines', 'Hà Lan'],
    correct: 3,
    index: 169,
  },
  {
    id: 'NO',
    name: 'Na Uy',
    uri: "require('../../assets/flagpng/NO.png)",
    answer: ['Luxembourg', 'Na Uy', 'Cuba', 'Tuvalu'],
    correct: 1,
    index: 170,
  },
  {
    id: 'NP',
    name: 'Nepal',
    uri: "require('../../assets/flagpng/NP.png)",
    answer: ['Việt Nam', 'Mali', 'Canada', 'Nepal'],
    correct: 3,
    index: 171,
  },
  {
    id: 'NR',
    name: 'Nauru',
    uri: "require('../../assets/flagpng/NR.png)",
    answer: ['Mauritius', 'Angola', 'Nauru', 'El Salvador'],
    correct: 2,
    index: 172,
  },
  {
    id: 'NZ',
    name: 'New Zealand',
    uri: "require('../../assets/flagpng/NZ.png)",
    answer: ['Pakistan', 'Montenegro', 'New Zealand', 'Micronesia'],
    correct: 2,
    index: 174,
  },
  {
    id: 'OM',
    name: 'Oman',
    uri: "require('../../assets/flagpng/OM.png)",
    answer: ['Nam Phi', 'Luxembourg', 'Oman', 'Andorra'],
    correct: 2,
    index: 175,
  },
  {
    id: 'PA',
    name: 'Panama',
    uri: "require('../../assets/flagpng/PA.png)",
    answer: ['Egypt', 'Panama', 'Sri Lanka', 'São Tomé và Príncipe'],
    correct: 1,
    index: 176,
  },
  {
    id: 'PE',
    name: 'Peru',
    uri: "require('../../assets/flagpng/PE.png)",
    answer: ['Myanmar', 'Gabon', 'Peru', 'Nam Phi'],
    correct: 2,
    index: 177,
  },
  {
    id: 'PG',
    name: 'Papua New Guinea',
    uri: "require('../../assets/flagpng/PG.png)",
    answer: ['Benin', 'Mauritius', 'Papua New Guinea', 'Thailand'],
    correct: 2,
    index: 179,
  },
  {
    id: 'PH',
    name: 'Philippines',
    uri: "require('../../assets/flagpng/PH.png)",
    answer: ['Paraguay', 'Mozambique', 'Philippines', 'Vương quốc Anh'],
    correct: 2,
    index: 180,
  },
  {
    id: 'PK',
    name: 'Pakistan',
    uri: "require('../../assets/flagpng/PK.png)",
    answer: ['Mexico', 'Angola', 'Senegal', 'Pakistan'],
    correct: 3,
    index: 181,
  },
  {
    id: 'PL',
    name: 'Ba Lan',
    uri: "require('../../assets/flagpng/PL.png)",
    answer: ['Ba Lan', 'Pháp', 'Croatia', 'Nauru'],
    correct: 0,
    index: 182,
  },
  {
    id: 'PT',
    name: 'Portugal',
    uri: "require('../../assets/flagpng/PT.png)",
    answer: ['Portugal', 'Sudan', 'Ghana', 'Haiti'],
    correct: 0,
    index: 187,
  },
  {
    id: 'PW',
    name: 'Palau',
    uri: "require('../../assets/flagpng/PW.png)",
    answer: ['Belarus', 'Nam Phi', 'Palau', 'Kyrgyzstan'],
    correct: 2,
    index: 188,
  },
  {
    id: 'PY',
    name: 'Paraguay',
    uri: "require('../../assets/flagpng/PY.png)",
    answer: ['Mexico', 'Tonga', 'Bulgaria', 'Paraguay'],
    correct: 3,
    index: 189,
  },
  {
    id: 'QA',
    name: 'Qatar',
    uri: "require('../../assets/flagpng/QA.png)",
    answer: ['Ukraine', 'Chile', 'Qatar', 'Moldova'],
    correct: 2,
    index: 190,
  },
  {
    id: 'RO',
    name: 'Romania',
    uri: "require('../../assets/flagpng/RO.png)",
    answer: ['Kenya', 'Thailand', 'Romania', 'Bahrain'],
    correct: 2,
    index: 192,
  },
  {
    id: 'RS',
    name: 'Serbia',
    uri: "require('../../assets/flagpng/RS.png)",
    answer: [
      'Honduras',
      'Serbia',
      'New Zealand',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 1,
    index: 193,
  },
  {
    id: 'RU',
    name: 'Nga',
    uri: "require('../../assets/flagpng/RU.png)",
    answer: ['Nga', 'Trinidad và Tobago', 'Barbados', 'Malawi'],
    correct: 0,
    index: 194,
  },
  {
    id: 'RW',
    name: 'Rwanda',
    uri: "require('../../assets/flagpng/RW.png)",
    answer: ['Rwanda', 'Gabon', 'Tajikistan', 'Mali'],
    correct: 0,
    index: 195,
  },
  {
    id: 'SA',
    name: 'Ả Rập Xê Út',
    uri: "require('../../assets/flagpng/SA.png)",
    answer: ['New Zealand', 'Ả Rập Xê Út', 'Trung Quốc', 'Guinea-Bissau'],
    correct: 1,
    index: 196,
  },
  {
    id: 'SB',
    name: 'Quần đảo Solomon',
    uri: "require('../../assets/flagpng/SB.png)",
    answer: ['Slovenia', 'Jordan', 'Armenia', 'Quần đảo Solomon'],
    correct: 3,
    index: 197,
  },
  {
    id: 'SC',
    name: 'Seychelles',
    uri: "require('../../assets/flagpng/SC.png)",
    answer: ['Đông Timor', 'Seychelles', 'Campuchia', 'Andorra'],
    correct: 1,
    index: 198,
  },
  {
    id: 'SD',
    name: 'Sudan',
    uri: "require('../../assets/flagpng/SD.png)",
    answer: ['Tonga', 'Israel', 'Eritrea', 'Sudan'],
    correct: 3,
    index: 199,
  },
  {
    id: 'SE',
    name: 'Thụy Điển',
    uri: "require('../../assets/flagpng/SE.png)",
    answer: ['Thụy Điển', 'Cape Verde', 'Li-băng', 'Philippines'],
    correct: 0,
    index: 200,
  },
  {
    id: 'SG',
    name: 'Singapore',
    uri: "require('../../assets/flagpng/SG.png)",
    answer: ['Grenada', 'Singapore', 'São Tomé và Príncipe', 'Ma-rốc'],
    correct: 1,
    index: 201,
  },
  {
    id: 'SI',
    name: 'Slovenia',
    uri: "require('../../assets/flagpng/SI.png)",
    answer: ['Thụy Điển', 'Costa Rica', 'Honduras', 'Slovenia'],
    correct: 3,
    index: 203,
  },
  {
    id: 'SK',
    name: 'Slovakia',
    uri: "require('../../assets/flagpng/SK.png)",
    answer: ['Monaco', 'Slovakia', 'Chad', 'Belize'],
    correct: 1,
    index: 205,
  },
  {
    id: 'SL',
    name: 'Sierra Leone',
    uri: "require('../../assets/flagpng/SL.png)",
    answer: ['Sierra Leone', 'Belarus', 'Nhật Bản', 'Thổ Nhĩ Kỳ'],
    correct: 0,
    index: 206,
  },
  {
    id: 'SM',
    name: 'San Marino',
    uri: "require('../../assets/flagpng/SM.png)",
    answer: ['Burundi', 'San Marino', 'Sierra Leone', 'Iceland'],
    correct: 1,
    index: 207,
  },
  {
    id: 'SN',
    name: 'Senegal',
    uri: "require('../../assets/flagpng/SN.png)",
    answer: ['Italy', 'Nam Phi', 'Senegal', 'Bangladesh'],
    correct: 2,
    index: 208,
  },
  {
    id: 'SO',
    name: 'Somalia',
    uri: "require('../../assets/flagpng/SO.png)",
    answer: ['Somalia', 'Philippines', 'Cộng hoà Congo', 'Libya'],
    correct: 0,
    index: 209,
  },
  {
    id: 'SR',
    name: 'Suriname',
    uri: "require('../../assets/flagpng/SR.png)",
    answer: ['Sierra Leone', 'Na Uy', 'Micronesia', 'Suriname'],
    correct: 3,
    index: 210,
  },
  {
    id: 'SS',
    name: 'South Sudan',
    uri: "require('../../assets/flagpng/SS.png)",
    answer: ['Niger', 'Serbia', 'Cameroon', 'South Sudan'],
    correct: 3,
    index: 211,
  },
  {
    id: 'ST',
    name: 'São Tomé và Príncipe',
    uri: "require('../../assets/flagpng/ST.png)",
    answer: ['Myanmar', 'Philippines', 'Estonia', 'São Tomé và Príncipe'],
    correct: 3,
    index: 212,
  },
  {
    id: 'SV',
    name: 'El Salvador',
    uri: "require('../../assets/flagpng/SV.png)",
    answer: ['El Salvador', 'Ghana', 'Ma-rốc', 'Ukraine'],
    correct: 0,
    index: 213,
  },
  {
    id: 'SY',
    name: 'Syria',
    uri: "require('../../assets/flagpng/SY.png)",
    answer: ['Syria', 'Uzbekistan', 'Tây Ban Nha', 'Maldives'],
    correct: 0,
    index: 215,
  },
  {
    id: 'SZ',
    name: 'Swaziland',
    uri: "require('../../assets/flagpng/SZ.png)",
    answer: ['Djibouti', 'Hà Lan', 'Paraguay', 'Swaziland'],
    correct: 3,
    index: 216,
  },
  {
    id: 'TD',
    name: 'Chad',
    uri: "require('../../assets/flagpng/TD.png)",
    answer: ['Nhật Bản', 'Quần đảo Solomon', 'Chad', 'Phần Lan'],
    correct: 2,
    index: 218,
  },
  {
    id: 'TG',
    name: 'Togo',
    uri: "require('../../assets/flagpng/TG.png)",
    answer: ['South Sudan', 'Maldives', 'Togo', 'Afghanistan'],
    correct: 2,
    index: 220,
  },
  {
    id: 'TH',
    name: 'Thailand',
    uri: "require('../../assets/flagpng/TH.png)",
    answer: ['Panama', 'Thailand', 'Thụy Sỹ', 'Indonesia'],
    correct: 1,
    index: 221,
  },
  {
    id: 'TJ',
    name: 'Tajikistan',
    uri: "require('../../assets/flagpng/TJ.png)",
    answer: ['Tajikistan', 'Rwanda', 'Trung Quốc', 'Kuwait'],
    correct: 0,
    index: 222,
  },
  {
    id: 'TL',
    name: 'Đông Timor',
    uri: "require('../../assets/flagpng/TL.png)",
    answer: ['Đông Timor', 'Indonesia', 'Cameroon', 'Vanuatu'],
    correct: 0,
    index: 224,
  },
  {
    id: 'TM',
    name: 'Turkmenistan',
    uri: "require('../../assets/flagpng/TM.png)",
    answer: ['Turkmenistan', 'Hàn Quốc', 'Đảo Síp', 'Tajikistan'],
    correct: 0,
    index: 225,
  },
  {
    id: 'TN',
    name: 'Tunisia',
    uri: "require('../../assets/flagpng/TN.png)",
    answer: ['Romania', 'Georgia', 'Tunisia', 'Hàn Quốc'],
    correct: 2,
    index: 226,
  },
  {
    id: 'TO',
    name: 'Tonga',
    uri: "require('../../assets/flagpng/TO.png)",
    answer: ['Hungary', 'Tonga', 'Paraguay', 'Argentina'],
    correct: 1,
    index: 227,
  },
  {
    id: 'TR',
    name: 'Thổ Nhĩ Kỳ',
    uri: "require('../../assets/flagpng/TR.png)",
    answer: ['Thổ Nhĩ Kỳ', 'Liberia', 'Peru', 'Ethiopia'],
    correct: 0,
    index: 228,
  },
  {
    id: 'TT',
    name: 'Trinidad và Tobago',
    uri: "require('../../assets/flagpng/TT.png)",
    answer: [
      'Cộng hòa Trung Phi',
      'Slovenia',
      'Trinidad và Tobago',
      'North Macedonia',
    ],
    correct: 2,
    index: 229,
  },
  {
    id: 'TV',
    name: 'Tuvalu',
    uri: "require('../../assets/flagpng/TV.png)",
    answer: ['Ukraine', 'Tuvalu', 'Iceland', 'Áo'],
    correct: 1,
    index: 230,
  },
  {
    id: 'TZ',
    name: 'Tanzania',
    uri: "require('../../assets/flagpng/TZ.png)",
    answer: ['Campuchia', 'Tunisia', 'Antigua và Barbuda', 'Tanzania'],
    correct: 3,
    index: 232,
  },
  {
    id: 'UA',
    name: 'Ukraine',
    uri: "require('../../assets/flagpng/UA.png)",
    answer: ['Lithuania', 'Antigua và Barbuda', 'Ukraine', 'Nam Phi'],
    correct: 2,
    index: 233,
  },
  {
    id: 'UG',
    name: 'Uganda',
    uri: "require('../../assets/flagpng/UG.png)",
    answer: ['Uganda', 'Nauru', 'Belize', 'Libya'],
    correct: 0,
    index: 234,
  },
  {
    id: 'US',
    name: 'Mỹ (Hoa Kỳ)',
    uri: "require('../../assets/flagpng/US.png)",
    answer: ['Maldives', 'San Marino', 'Cộng hòa Trung Phi', 'Mỹ (Hoa Kỳ)'],
    correct: 3,
    index: 235,
  },
  {
    id: 'UY',
    name: 'Uruguay',
    uri: "require('../../assets/flagpng/UY.png)",
    answer: ['Thổ Nhĩ Kỳ', 'Maldives', 'Uruguay', 'Tây Ban Nha'],
    correct: 2,
    index: 236,
  },
  {
    id: 'UZ',
    name: 'Uzbekistan',
    uri: "require('../../assets/flagpng/UZ.png)",
    answer: ['Uzbekistan', 'Ma-rốc', 'Sierra Leone', 'Bulgaria'],
    correct: 0,
    index: 237,
  },
  {
    id: 'VC',
    name: 'Saint Vincent và Grenadines',
    uri: "require('../../assets/flagpng/VC.png)",
    answer: ['Grenada', 'Zambia', 'Ma-rốc', 'Saint Vincent và Grenadines'],
    correct: 3,
    index: 239,
  },
  {
    id: 'VE',
    name: 'Venezuela',
    uri: "require('../../assets/flagpng/VE.png)",
    answer: ['Saint Vincent và Grenadines', 'Andorra', 'Na Uy', 'Venezuela'],
    correct: 3,
    index: 240,
  },
  {
    id: 'VN',
    name: 'Việt Nam',
    uri: "require('../../assets/flagpng/VN.png)",
    answer: ['Việt Nam', 'Na Uy', 'Rwanda', 'Benin'],
    correct: 0,
    index: 243,
  },
  {
    id: 'VU',
    name: 'Vanuatu',
    uri: "require('../../assets/flagpng/VU.png)",
    answer: ['Vanuatu', 'Phần Lan', 'Uganda', 'Lào'],
    correct: 0,
    index: 244,
  },
  {
    id: 'WS',
    name: 'Samoa',
    uri: "require('../../assets/flagpng/WS.png)",
    answer: ['Samoa', 'Sierra Leone', 'Bờ Biển Ngà', 'Hàn Quốc'],
    correct: 0,
    index: 246,
  },
  {
    id: 'YE',
    name: 'Yemen',
    uri: "require('../../assets/flagpng/YE.png)",
    answer: ['Gambia', 'Yemen', 'Uruguay', 'Libya'],
    correct: 1,
    index: 248,
  },
  {
    id: 'ZA',
    name: 'Nam Phi',
    uri: "require('../../assets/flagpng/ZA.png)",
    answer: ['Iran', 'Nam Phi', 'Úc', 'San Marino'],
    correct: 1,
    index: 250,
  },
  {
    id: 'ZM',
    name: 'Zambia',
    uri: "require('../../assets/flagpng/ZM.png)",
    answer: ['Algeria', 'Zambia', 'El Salvador', 'Nigeria'],
    correct: 1,
    index: 251,
  },
  {
    id: 'ZW',
    name: 'Zimbabwe',
    uri: "require('../../assets/flagpng/ZW.png)",
    answer: ['Maldives', 'South Sudan', 'Egypt', 'Zimbabwe'],
    correct: 3,
    index: 252,
  },
];
