import {Country} from '../../model/Country';

export const DATAAFRICAVI: Country[] = [
  {
    answer: ['Rwanda', 'Benin', 'Angola', 'Zambia'],
    correct: 2,
    id: 'AO',
    index: 7,
    name: 'Angola',
    uri: require('../../assets/flagpng/ao.png'),
  },
  {
    answer: ['Mauritius', 'Zambia', 'Burkina Faso', 'Benin'],
    correct: 2,
    id: 'BF',
    index: 20,
    name: 'Burkina Faso',
    uri: require('../../assets/flagpng/bf.png'),
  },
  {
    answer: ['Cộng hoà dân chủ Congo', 'Burundi', 'Mali', 'Tanzania'],
    correct: 1,
    id: 'BI',
    index: 23,
    name: 'Burundi',
    uri: require('../../assets/flagpng/bi.png'),
  },
  {
    answer: ['Cộng hoà Congo', 'Zambia', 'Benin', 'Lesotho'],
    correct: 2,
    id: 'BJ',
    index: 24,
    name: 'Benin',
    uri: require('../../assets/flagpng/bj.png'),
  },
  {
    answer: ['Eritrea', 'Botswana', 'Swaziland', 'Kenya'],
    correct: 1,
    id: 'BW',
    index: 33,
    name: 'Botswana',
    uri: require('../../assets/flagpng/bw.png'),
  },
  {
    answer: ['Swaziland', 'Egypt', 'Cộng hoà dân chủ Congo', 'Niger'],
    correct: 2,
    id: 'CD',
    index: 38,
    name: 'Cộng hoà dân chủ Congo',
    uri: require('../../assets/flagpng/cd.png'),
  },
  {
    answer: [
      'Ma-rốc',
      'Cộng hòa Trung Phi',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Angola',
    ],
    correct: 1,
    id: 'CF',
    index: 39,
    name: 'Cộng hòa Trung Phi',
    uri: require('../../assets/flagpng/cf.png'),
  },
  {
    answer: ['Bờ Biển Ngà', 'Cộng hoà Congo', 'Mauritius', 'Tanzania'],
    correct: 1,
    id: 'CG',
    index: 40,
    name: 'Cộng hoà Congo',
    uri: require('../../assets/flagpng/cg.png'),
  },
  {
    answer: ['Bờ Biển Ngà', 'Djibouti', 'Mayotte', 'Lesotho'],
    correct: 0,
    id: 'CI',
    index: 42,
    name: 'Bờ Biển Ngà',
    uri: require('../../assets/flagpng/ci.png'),
  },
  {
    answer: ['Egypt', 'Cameroon', 'Seychelles', 'Nam Phi'],
    correct: 1,
    id: 'CM',
    index: 45,
    name: 'Cameroon',
    uri: require('../../assets/flagpng/cm.png'),
  },
  {
    answer: ['Zambia', 'Gabon', 'Cape Verde', 'Mali'],
    correct: 2,
    id: 'CV',
    index: 50,
    name: 'Cape Verde',
    uri: require('../../assets/flagpng/cv.png'),
  },
  {
    answer: ['South Sudan', 'Ethiopia', 'Djibouti', 'Réunion'],
    correct: 2,
    id: 'DJ',
    index: 56,
    name: 'Djibouti',
    uri: require('../../assets/flagpng/dj.png'),
  },
  {
    answer: ['Chad', 'Liberia', 'Egypt', 'Algeria'],
    correct: 3,
    id: 'DZ',
    index: 60,
    name: 'Algeria',
    uri: require('../../assets/flagpng/dz.png'),
  },
  {
    answer: ['Djibouti', 'Somalia', 'Guinea-Bissau', 'Egypt'],
    correct: 3,
    id: 'EG',
    index: 63,
    name: 'Egypt',
    uri: require('../../assets/flagpng/eg.png'),
  },
  // {
  //   answer: ['Mali', 'Algeria', 'Nam Phi', 'Tây Sahara'],
  //   correct: 3,
  //   id: 'EH',
  //   index: 64,
  //   name: 'Tây Sahara',
  //   uri: require('../../assets/flagpng/eh.png'),
  // },
  {
    answer: ['Chad', 'Gabon', 'Mali', 'Eritrea'],
    correct: 3,
    id: 'ER',
    index: 65,
    name: 'Eritrea',
    uri: require('../../assets/flagpng/er.png'),
  },
  {
    answer: ['Eritrea', 'Ethiopia', 'Mauritania', 'Tanzania'],
    correct: 1,
    id: 'ET',
    index: 67,
    name: 'Ethiopia',
    uri: require('../../assets/flagpng/et.png'),
  },
  {
    answer: ['Gabon', 'Uganda', 'Bờ Biển Ngà', 'Liberia'],
    correct: 0,
    id: 'GA',
    index: 75,
    name: 'Gabon',
    uri: require('../../assets/flagpng/ga.png'),
  },
  {
    answer: ['Cape Verde', 'Sierra Leone', 'Ghana', 'Malawi'],
    correct: 2,
    id: 'GH',
    index: 85,
    name: 'Ghana',
    uri: require('../../assets/flagpng/gh.png'),
  },
  {
    answer: ['Burkina Faso', 'Mayotte', 'Gambia', 'Libya'],
    correct: 2,
    id: 'GM',
    index: 88,
    name: 'Gambia',
    uri: require('../../assets/flagpng/gm.png'),
  },
  {
    answer: ['South Sudan', 'Guinea', 'Mauritius', 'Burundi'],
    correct: 1,
    id: 'GN',
    index: 89,
    name: 'Guinea',
    uri: require('../../assets/flagpng/gn.png'),
  },
  {
    answer: ['Seychelles', 'Cape Verde', 'Senegal', 'Equatorial Guinea'],
    correct: 3,
    id: 'GQ',
    index: 91,
    name: 'Equatorial Guinea',
    uri: require('../../assets/flagpng/gq.png'),
  },
  {
    answer: ['Somalia', 'Mauritania', 'Botswana', 'Guinea-Bissau'],
    correct: 3,
    id: 'GW',
    index: 96,
    name: 'Guinea-Bissau',
    uri: require('../../assets/flagpng/gw.png'),
  },
  {
    answer: ['Togo', 'Mali', 'Kenya', 'Bờ Biển Ngà'],
    correct: 2,
    id: 'KE',
    index: 118,
    name: 'Kenya',
    uri: require('../../assets/flagpng/ke.png'),
  },
  {
    answer: ['São Tomé và Príncipe', 'Egypt', 'Comoros', 'Liberia'],
    correct: 2,
    id: 'KM',
    index: 122,
    name: 'Comoros',
    uri: require('../../assets/flagpng/km.png'),
  },
  {
    answer: ['Comoros', 'Liberia', 'Cộng hoà Congo', 'Zambia'],
    correct: 1,
    id: 'LR',
    index: 134,
    name: 'Liberia',
    uri: require('../../assets/flagpng/lr.png'),
  },
  {
    answer: ['Lesotho', 'Nigeria', 'Tây Sahara', 'Togo'],
    correct: 0,
    id: 'LS',
    index: 135,
    name: 'Lesotho',
    uri: require('../../assets/flagpng/ls.png'),
  },
  {
    answer: ['Sudan', 'Libya', 'Guinea', 'Benin'],
    correct: 1,
    id: 'LY',
    index: 139,
    name: 'Libya',
    uri: require('../../assets/flagpng/ly.png'),
  },
  {
    answer: ['Burundi', 'Ma-rốc', 'Sudan', 'Liberia'],
    correct: 1,
    id: 'MA',
    index: 140,
    name: 'Ma-rốc',
    uri: require('../../assets/flagpng/ma.png'),
  },
  {
    answer: ['Gabon', 'Madagascar', 'Comoros', 'Zambia'],
    correct: 1,
    id: 'MG',
    index: 145,
    name: 'Madagascar',
    uri: require('../../assets/flagpng/mg.png'),
  },
  {
    answer: ['Uganda', 'Mali', 'Angola', 'Kenya'],
    correct: 1,
    id: 'ML',
    index: 148,
    name: 'Mali',
    uri: require('../../assets/flagpng/ml.png'),
  },
  {
    answer: [
      'Saint Helena, Ascension và Tristan da Cunha',
      'Mauritania',
      'Ethiopia',
      'Seychelles',
    ],
    correct: 1,
    id: 'MR',
    index: 154,
    name: 'Mauritania',
    uri: require('../../assets/flagpng/mr.png'),
  },
  {
    answer: ['Ethiopia', 'Mayotte', 'Mauritius', 'Lesotho'],
    correct: 2,
    id: 'MU',
    index: 157,
    name: 'Mauritius',
    uri: require('../../assets/flagpng/mu.png'),
  },
  {
    answer: ['Tunisia', 'Ethiopia', 'Ma-rốc', 'Malawi'],
    correct: 3,
    id: 'MW',
    index: 159,
    name: 'Malawi',
    uri: require('../../assets/flagpng/mw.png'),
  },
  {
    answer: ['Mozambique', 'Namibia', 'Somalia', 'Algeria'],
    correct: 0,
    id: 'MZ',
    index: 162,
    name: 'Mozambique',
    uri: require('../../assets/flagpng/mz.png'),
  },
  {
    answer: ['Mali', 'Bờ Biển Ngà', 'Namibia', 'Chad'],
    correct: 2,
    id: 'NA',
    index: 163,
    name: 'Namibia',
    uri: require('../../assets/flagpng/na.png'),
  },
  {
    answer: ['Sierra Leone', 'Niger', 'Burkina Faso', 'Madagascar'],
    correct: 1,
    id: 'NE',
    index: 165,
    name: 'Niger',
    uri: require('../../assets/flagpng/ne.png'),
  },
  {
    answer: ['Guinea-Bissau', 'Zambia', 'Cộng hoà Congo', 'Nigeria'],
    correct: 3,
    id: 'NG',
    index: 167,
    name: 'Nigeria',
    uri: require('../../assets/flagpng/ng.png'),
  },
  // {
  //   answer: ['Eritrea', 'Réunion', 'Mayotte', 'Namibia'],
  //   correct: 1,
  //   id: 'RE',
  //   index: 191,
  //   name: 'Réunion',
  //   uri: require('../../assets/flagpng/re.png'),
  // },
  {
    answer: ['Rwanda', 'Swaziland', 'Cameroon', 'Liberia'],
    correct: 0,
    id: 'RW',
    index: 195,
    name: 'Rwanda',
    uri: require('../../assets/flagpng/rw.png'),
  },
  {
    answer: ['Seychelles', 'Mozambique', 'Zimbabwe', 'Ghana'],
    correct: 0,
    id: 'SC',
    index: 198,
    name: 'Seychelles',
    uri: require('../../assets/flagpng/sc.png'),
  },
  {
    answer: ['Sudan', 'Uganda', 'Tây Sahara', 'Guinea'],
    correct: 0,
    id: 'SD',
    index: 199,
    name: 'Sudan',
    uri: require('../../assets/flagpng/sd.png'),
  },
  // {
  //   answer: [
  //     'Lesotho',
  //     'Saint Helena, Ascension và Tristan da Cunha',
  //     'Sierra Leone',
  //     'Bờ Biển Ngà',
  //   ],
  //   correct: 1,
  //   id: 'SH',
  //   index: 202,
  //   name: 'Saint Helena, Ascension và Tristan da Cunha',
  //   uri: require('../../assets/flagpng/sh.png'),
  // },
  {
    answer: ['Mauritania', 'Eritrea', 'São Tomé và Príncipe', 'Sierra Leone'],
    correct: 3,
    id: 'SL',
    index: 206,
    name: 'Sierra Leone',
    uri: require('../../assets/flagpng/sl.png'),
  },
  {
    answer: ['Niger', 'Senegal', 'Eritrea', 'Guinea-Bissau'],
    correct: 1,
    id: 'SN',
    index: 208,
    name: 'Senegal',
    uri: require('../../assets/flagpng/sn.png'),
  },
  {
    answer: ['Niger', 'Somalia', 'Senegal', 'Botswana'],
    correct: 1,
    id: 'SO',
    index: 209,
    name: 'Somalia',
    uri: require('../../assets/flagpng/so.png'),
  },
  {
    answer: [
      'Niger',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Cộng hoà Congo',
      'South Sudan',
    ],
    correct: 3,
    id: 'SS',
    index: 211,
    name: 'South Sudan',
    uri: require('../../assets/flagpng/ss.png'),
  },
  {
    answer: ['Cộng hoà Congo', 'Madagascar', 'São Tomé và Príncipe', 'Mayotte'],
    correct: 2,
    id: 'ST',
    index: 212,
    name: 'São Tomé và Príncipe',
    uri: require('../../assets/flagpng/st.png'),
  },
  // {
  //   answer: ['Ghana', 'Swaziland', 'Tanzania', 'Namibia'],
  //   correct: 1,
  //   id: 'SZ',
  //   index: 216,
  //   name: 'Swaziland',
  //   uri: require('../../assets/flagpng/sz.png'),
  // },
  {
    answer: ['Liberia', 'Chad', 'Cape Verde', 'Senegal'],
    correct: 1,
    id: 'TD',
    index: 218,
    name: 'Chad',
    uri: require('../../assets/flagpng/td.png'),
  },
  {
    answer: ['Togo', 'Seychelles', 'Zambia', 'Gabon'],
    correct: 0,
    id: 'TG',
    index: 220,
    name: 'Togo',
    uri: require('../../assets/flagpng/tg.png'),
  },
  {
    answer: ['Tunisia', 'Liberia', 'Burkina Faso', 'Tanzania'],
    correct: 0,
    id: 'TN',
    index: 226,
    name: 'Tunisia',
    uri: require('../../assets/flagpng/tn.png'),
  },
  {
    answer: ['Malawi', 'Tây Sahara', 'Sudan', 'Tanzania'],
    correct: 3,
    id: 'TZ',
    index: 232,
    name: 'Tanzania',
    uri: require('../../assets/flagpng/tz.png'),
  },
  {
    answer: ['Mauritania', 'Uganda', 'Sudan', 'Eritrea'],
    correct: 1,
    id: 'UG',
    index: 234,
    name: 'Uganda',
    uri: require('../../assets/flagpng/ug.png'),
  },
  // {
  //   answer: ['Malawi', 'Tanzania', 'Botswana', 'Mayotte'],
  //   correct: 3,
  //   id: 'YT',
  //   index: 249,
  //   name: 'Mayotte',
  //   uri: require('../../assets/flagpng/yt.png'),
  // },
  {
    answer: ['Nam Phi', 'Tunisia', 'Equatorial Guinea', 'Gambia'],
    correct: 0,
    id: 'ZA',
    index: 250,
    name: 'Nam Phi',
    uri: require('../../assets/flagpng/za.png'),
  },
  {
    answer: ['Cộng hoà Congo', 'Uganda', 'Guinea-Bissau', 'Zambia'],
    correct: 3,
    id: 'ZM',
    index: 251,
    name: 'Zambia',
    uri: require('../../assets/flagpng/zm.png'),
  },
  {
    answer: [
      'Rwanda',
      'Zimbabwe',
      'Saint Helena, Ascension và Tristan da Cunha',
      'Eritrea',
    ],
    correct: 1,
    id: 'ZW',
    index: 252,
    name: 'Zimbabwe',
    uri: require('../../assets/flagpng/zw.png'),
  },
  {
    answer: ['Eswatini', 'Gabon', 'Nigeria', 'Sudan'],
    correct: 0,
    id: 'SZ',
    index: 253,
    name: 'Eswatini',
    uri: require('../../assets/flagpng/sz.png'),
  },
];

export const DATAAFRICA: Country[] = [
  {
    answer: ['Algeria', 'Liberia', 'Botswana', 'Togo'],
    correct: 0,
    id: 'DZ',
    index: 2,
    name: 'Algeria',
    uri: require('../../assets/flagpng/dz.png'),
  },
  {
    answer: ['Senegal', 'Angola', 'Eswatini', 'Guinea'],
    correct: 1,
    id: 'AO',
    index: 4,
    name: 'Angola',
    uri: require('../../assets/flagpng/ao.png'),
  },
  {
    answer: ['Burundi', 'Liberia', 'Tanzania, United Republic of', 'Benin'],
    correct: 3,
    id: 'BJ',
    index: 18,
    name: 'Benin',
    uri: require('../../assets/flagpng/bj.png'),
  },
  {
    answer: ['Kenya', 'Botswana', 'Eswatini', 'Senegal'],
    correct: 1,
    id: 'BW',
    index: 22,
    name: 'Botswana',
    uri: require('../../assets/flagpng/bw.png'),
  },
  {
    answer: ['Mozambique', 'Burkina Faso', 'Zambia', 'Senegal'],
    correct: 1,
    id: 'BF',
    index: 26,
    name: 'Burkina Faso',
    uri: require('../../assets/flagpng/bf.png'),
  },
  {
    answer: [
      'Congo, Democratic Republic of the',
      'Senegal',
      'Burundi',
      'Ethiopia',
    ],
    correct: 2,
    id: 'BI',
    index: 27,
    name: 'Burundi',
    uri: require('../../assets/flagpng/bi.png'),
  },
  {
    answer: ['Cameroon', 'Cabo Verde', 'Morocco', 'Senegal'],
    correct: 1,
    id: 'CV',
    index: 28,
    name: 'Cabo Verde',
    uri: require('../../assets/flagpng/cv.png'),
  },
  {
    answer: ['Mauritius', 'Cameroon', 'Eritrea', 'Somalia'],
    correct: 1,
    id: 'CM',
    index: 30,
    name: 'Cameroon',
    uri: require('../../assets/flagpng/cm.png'),
  },
  {
    answer: ['Eritrea', 'Kenya', 'South Sudan', 'Central African Republic'],
    correct: 3,
    id: 'CF',
    index: 32,
    name: 'Central African Republic',
    uri: require('../../assets/flagpng/cf.png'),
  },
  {
    answer: ['Djibouti', 'Chad', 'Tunisia', 'Morocco'],
    correct: 1,
    id: 'TD',
    index: 33,
    name: 'Chad',
    uri: require('../../assets/flagpng/td.png'),
  },
  {
    answer: ['Nigeria', 'Seychelles', 'Eritrea', 'Comoros'],
    correct: 3,
    id: 'KM',
    index: 37,
    name: 'Comoros',
    uri: require('../../assets/flagpng/km.png'),
  },
  {
    answer: ['Ethiopia', 'Congo', 'Rwanda', 'Egypt'],
    correct: 1,
    id: 'CG',
    index: 38,
    name: 'Congo',
    uri: require('../../assets/flagpng/cg.png'),
  },
  {
    answer: [
      'Congo, Democratic Republic of the',
      'Rwanda',
      'Burkina Faso',
      'Nigeria',
    ],
    correct: 0,
    id: 'CD',
    index: 39,
    name: 'Congo, Democratic Republic of the',
    uri: require('../../assets/flagpng/cd.png'),
  },
  {
    answer: ['Cabo Verde', 'Gabon', 'Tunisia', "Côte d'Ivoire"],
    correct: 3,
    id: 'CI',
    index: 41,
    name: "Côte d'Ivoire",
    uri: require('../../assets/flagpng/ci.png'),
  },
  {
    answer: [
      'Djibouti',
      'Congo, Democratic Republic of the',
      'Guinea',
      'Seychelles',
    ],
    correct: 0,
    id: 'DJ',
    index: 47,
    name: 'Djibouti',
    uri: require('../../assets/flagpng/dj.png'),
  },
  {
    answer: [
      'Egypt',
      'Tanzania, United Republic of',
      'Central African Republic',
      'Guinea',
    ],
    correct: 0,
    id: 'EG',
    index: 51,
    name: 'Egypt',
    uri: require('../../assets/flagpng/eg.png'),
  },
  {
    answer: ['Burundi', 'Equatorial Guinea', 'Niger', 'Sao Tome and Principe'],
    correct: 1,
    id: 'GQ',
    index: 53,
    name: 'Equatorial Guinea',
    uri: require('../../assets/flagpng/gq.png'),
  },
  {
    answer: ['Eritrea', 'Gabon', 'Burundi', 'Somalia'],
    correct: 0,
    id: 'ER',
    index: 54,
    name: 'Eritrea',
    uri: require('../../assets/flagpng/er.png'),
  },
  {
    answer: ['Eswatini', 'Gabon', 'Nigeria', 'Sudan'],
    correct: 0,
    id: 'SZ',
    index: 56,
    name: 'Eswatini',
    uri: require('../../assets/flagpng/sz.png'),
  },
  {
    answer: [
      'Nigeria',
      'Tanzania, United Republic of',
      "Côte d'Ivoire",
      'Ethiopia',
    ],
    correct: 3,
    id: 'ET',
    index: 57,
    name: 'Ethiopia',
    uri: require('../../assets/flagpng/et.png'),
  },
  {
    answer: ['Rwanda', 'Morocco', 'Gabon', "Côte d'Ivoire"],
    correct: 2,
    id: 'GA',
    index: 61,
    name: 'Gabon',
    uri: require('../../assets/flagpng/ga.png'),
  },
  {
    answer: ['Botswana', 'Seychelles', 'Morocco', 'Gambia'],
    correct: 3,
    id: 'GM',
    index: 62,
    name: 'Gambia',
    uri: require('../../assets/flagpng/gm.png'),
  },
  {
    answer: ['Ghana', 'South Sudan', 'Eritrea', 'Libya'],
    correct: 0,
    id: 'GH',
    index: 65,
    name: 'Ghana',
    uri: require('../../assets/flagpng/gh.png'),
  },
  {
    answer: ['Somalia', 'Chad', 'Namibia', 'Guinea'],
    correct: 3,
    id: 'GN',
    index: 69,
    name: 'Guinea',
    uri: require('../../assets/flagpng/gn.png'),
  },
  {
    answer: ['Kenya', 'Angola', 'Uganda', 'Guinea-Bissau'],
    correct: 3,
    id: 'GW',
    index: 70,
    name: 'Guinea-Bissau',
    uri: require('../../assets/flagpng/gw.png'),
  },
  {
    answer: ['Angola', 'Kenya', 'South Africa', 'Mauritania'],
    correct: 1,
    id: 'KE',
    index: 87,
    name: 'Kenya',
    uri: require('../../assets/flagpng/ke.png'),
  },
  {
    answer: ['Namibia', "Côte d'Ivoire", 'Sierra Leone', 'Lesotho'],
    correct: 3,
    id: 'LS',
    index: 96,
    name: 'Lesotho',
    uri: require('../../assets/flagpng/ls.png'),
  },
  {
    answer: ['Libya', 'South Africa', 'Algeria', 'Liberia'],
    correct: 3,
    id: 'LR',
    index: 97,
    name: 'Liberia',
    uri: require('../../assets/flagpng/lr.png'),
  },
  {
    answer: ['South Africa', 'Liberia', 'Angola', 'Libya'],
    correct: 3,
    id: 'LY',
    index: 98,
    name: 'Libya',
    uri: require('../../assets/flagpng/ly.png'),
  },
  {
    answer: ['South Sudan', 'Madagascar', 'Burundi', 'Liberia'],
    correct: 1,
    id: 'MG',
    index: 102,
    name: 'Madagascar',
    uri: require('../../assets/flagpng/mg.png'),
  },
  {
    answer: ['Malawi', 'Djibouti', 'Guinea-Bissau', 'Sao Tome and Principe'],
    correct: 0,
    id: 'MW',
    index: 103,
    name: 'Malawi',
    uri: require('../../assets/flagpng/mw.png'),
  },
  {
    answer: ['Mali', 'Burundi', 'Gambia', 'Togo'],
    correct: 0,
    id: 'ML',
    index: 106,
    name: 'Mali',
    uri: require('../../assets/flagpng/ml.png'),
  },
  {
    answer: ['Mauritania', 'Togo', 'Mozambique', 'Comoros'],
    correct: 0,
    id: 'MR',
    index: 109,
    name: 'Mauritania',
    uri: require('../../assets/flagpng/mr.png'),
  },
  {
    answer: ['Zambia', 'Malawi', 'Mauritius', 'Angola'],
    correct: 2,
    id: 'MU',
    index: 110,
    name: 'Mauritius',
    uri: require('../../assets/flagpng/mu.png'),
  },
  {
    answer: ['Egypt', 'Morocco', 'Niger', 'Sao Tome and Principe'],
    correct: 1,
    id: 'MA',
    index: 117,
    name: 'Morocco',
    uri: require('../../assets/flagpng/ma.png'),
  },
  {
    answer: ['Morocco', "Côte d'Ivoire", 'South Sudan', 'Mozambique'],
    correct: 3,
    id: 'MZ',
    index: 118,
    name: 'Mozambique',
    uri: require('../../assets/flagpng/mz.png'),
  },
  {
    answer: ['Madagascar', 'Rwanda', 'Namibia', "Côte d'Ivoire"],
    correct: 2,
    id: 'NA',
    index: 120,
    name: 'Namibia',
    uri: require('../../assets/flagpng/na.png'),
  },
  {
    answer: ['Sierra Leone', 'Niger', 'Namibia', 'Congo'],
    correct: 1,
    id: 'NE',
    index: 126,
    name: 'Niger',
    uri: require('../../assets/flagpng/ne.png'),
  },
  {
    answer: ['Tunisia', "Côte d'Ivoire", 'Mauritius', 'Nigeria'],
    correct: 3,
    id: 'NG',
    index: 127,
    name: 'Nigeria',
    uri: require('../../assets/flagpng/ng.png'),
  },
  {
    answer: ['Rwanda', 'Equatorial Guinea', 'Mozambique', 'Tunisia'],
    correct: 0,
    id: 'RW',
    index: 143,
    name: 'Rwanda',
    uri: require('../../assets/flagpng/rw.png'),
  },
  {
    answer: [
      'Sao Tome and Principe',
      'Congo, Democratic Republic of the',
      'Libya',
      'Zambia',
    ],
    correct: 0,
    id: 'ST',
    index: 149,
    name: 'Sao Tome and Principe',
    uri: require('../../assets/flagpng/st.png'),
  },
  {
    answer: ['Tanzania, United Republic of', 'Djibouti', 'Senegal', 'Liberia'],
    correct: 2,
    id: 'SN',
    index: 151,
    name: 'Senegal',
    uri: require('../../assets/flagpng/sn.png'),
  },
  {
    answer: ['Zimbabwe', 'Malawi', 'Egypt', 'Seychelles'],
    correct: 3,
    id: 'SC',
    index: 153,
    name: 'Seychelles',
    uri: require('../../assets/flagpng/sc.png'),
  },
  {
    answer: ['Burkina Faso', 'Nigeria', 'Rwanda', 'Sierra Leone'],
    correct: 3,
    id: 'SL',
    index: 154,
    name: 'Sierra Leone',
    uri: require('../../assets/flagpng/sl.png'),
  },
  {
    answer: ['Mauritius', 'Chad', 'Rwanda', 'Somalia'],
    correct: 3,
    id: 'SO',
    index: 159,
    name: 'Somalia',
    uri: require('../../assets/flagpng/so.png'),
  },
  {
    answer: ['Libya', 'Burkina Faso', 'Senegal', 'South Africa'],
    correct: 3,
    id: 'ZA',
    index: 160,
    name: 'South Africa',
    uri: require('../../assets/flagpng/za.png'),
  },
  {
    answer: ['Sierra Leone', 'Mozambique', 'South Sudan', "Côte d'Ivoire"],
    correct: 2,
    id: 'SS',
    index: 161,
    name: 'South Sudan',
    uri: require('../../assets/flagpng/ss.png'),
  },
  {
    answer: ['Sao Tome and Principe', 'Eritrea', 'Guinea-Bissau', 'Sudan'],
    correct: 3,
    id: 'SD',
    index: 164,
    name: 'Sudan',
    uri: require('../../assets/flagpng/sd.png'),
  },
  {
    answer: [
      'Tanzania, United Republic of',
      "Côte d'Ivoire",
      'Libya',
      'Zimbabwe',
    ],
    correct: 0,
    id: 'TZ',
    index: 170,
    name: 'Tanzania, United Republic of',
    uri: require('../../assets/flagpng/tz.png'),
  },
  {
    answer: ['Tunisia', 'Lesotho', 'Togo', 'Benin'],
    correct: 2,
    id: 'TG',
    index: 173,
    name: 'Togo',
    uri: require('../../assets/flagpng/tg.png'),
  },
  {
    answer: [
      'Zimbabwe',
      'Tunisia',
      'Congo, Democratic Republic of the',
      'Ghana',
    ],
    correct: 1,
    id: 'TN',
    index: 176,
    name: 'Tunisia',
    uri: require('../../assets/flagpng/tn.png'),
  },
  {
    answer: ['Ghana', 'South Africa', 'Uganda', 'Congo'],
    correct: 2,
    id: 'UG',
    index: 180,
    name: 'Uganda',
    uri: require('../../assets/flagpng/ug.png'),
  },
  {
    answer: ['South Africa', 'Zambia', 'Comoros', 'Libya'],
    correct: 1,
    id: 'ZM',
    index: 191,
    name: 'Zambia',
    uri: require('../../assets/flagpng/zm.png'),
  },
  {
    answer: ['Morocco', 'Sudan', 'Zimbabwe', 'Chad'],
    correct: 2,
    id: 'ZW',
    index: 192,
    name: 'Zimbabwe',
    uri: require('../../assets/flagpng/zw.png'),
  },
];
