import {Country} from '../../model/Country';

export const DATAVI195: Country[] = [
  {
    answer: ['Andorra', 'Belarus', 'Mauritius', 'Việt Nam'],
    correct: 0,
    id: 'AD',
    index: 0,
    name: 'Andorra',
    uri: require('../../assets/flagpng/ad.png'),
  },
  {
    answer: [
      'Vương quốc Anh',
      'Việt Nam',
      'Mexico',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 3,
    id: 'AE',
    index: 1,
    name: 'Các tiểu vương quốc Ả Rập Thống nhất',
    uri: require('../../assets/flagpng/ae.png'),
  },
  {
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Papua New Guinea',
      'Afghanistan',
      'Iceland',
    ],
    correct: 2,
    id: 'AF',
    index: 2,
    name: 'Afghanistan',
    uri: require('../../assets/flagpng/af.png'),
  },
  {
    answer: ['Comoros', 'Vanuatu', 'Djibouti', 'Antigua và Barbuda'],
    correct: 3,
    id: 'AG',
    index: 3,
    name: 'Antigua và Barbuda',
    uri: require('../../assets/flagpng/ag.png'),
  },
  {
    answer: ['Samoa', 'Chile', 'Albania', 'Saint Kitts và Nevis'],
    correct: 2,
    id: 'AL',
    index: 5,
    name: 'Albania',
    uri: require('../../assets/flagpng/al.png'),
  },
  {
    answer: ['Campuchia', 'Thailand', 'Armenia', 'Georgia'],
    correct: 2,
    id: 'AM',
    index: 6,
    name: 'Armenia',
    uri: require('../../assets/flagpng/am.png'),
  },
  {
    answer: [
      'Brunei Darussalam',
      'Saint Vincent và Grenadines',
      'Lithuania',
      'Angola',
    ],
    correct: 3,
    id: 'AO',
    index: 7,
    name: 'Angola',
    uri: require('../../assets/flagpng/ao.png'),
  },
  {
    answer: ['Nauru', 'Argentina', 'Maldives', 'Bhutan'],
    correct: 1,
    id: 'AR',
    index: 9,
    name: 'Argentina',
    uri: require('../../assets/flagpng/ar.png'),
  },
  {
    answer: ['Ukraine', 'Mongolia', 'Albania', 'Áo'],
    correct: 3,
    id: 'AT',
    index: 11,
    name: 'Áo',
    uri: require('../../assets/flagpng/at.png'),
  },
  {
    answer: ['Marshall Islands', 'Úc', 'Georgia', 'Tajikistan'],
    correct: 1,
    id: 'AU',
    index: 12,
    name: 'Úc',
    uri: require('../../assets/flagpng/au.png'),
  },
  {
    answer: ['South Sudan', 'Maldives', 'Azerbaijan', 'Bolivia'],
    correct: 2,
    id: 'AZ',
    index: 15,
    name: 'Azerbaijan',
    uri: require('../../assets/flagpng/az.png'),
  },
  {
    answer: ['Thổ Nhĩ Kỳ', 'Bosnia và Herzegovina', 'Gabon', 'Moldova'],
    correct: 1,
    id: 'BA',
    index: 16,
    name: 'Bosnia và Herzegovina',
    uri: require('../../assets/flagpng/ba.png'),
  },
  {
    answer: ['Pakistan', 'Áo', 'Barbados', 'Indonesia'],
    correct: 2,
    id: 'BB',
    index: 17,
    name: 'Barbados',
    uri: require('../../assets/flagpng/bb.png'),
  },
  {
    answer: ['Bangladesh', 'Zambia', 'Phần Lan', 'Liberia'],
    correct: 0,
    id: 'BD',
    index: 18,
    name: 'Bangladesh',
    uri: require('../../assets/flagpng/bd.png'),
  },
  {
    answer: ['Hy Lạp', 'Serbia', 'Bỉ', 'Cộng hòa Dominica'],
    correct: 2,
    id: 'BE',
    index: 19,
    name: 'Bỉ',
    uri: require('../../assets/flagpng/be.png'),
  },
  {
    answer: ['Vương quốc Anh', 'Lesotho', 'Burkina Faso', 'Thailand'],
    correct: 2,
    id: 'BF',
    index: 20,
    name: 'Burkina Faso',
    uri: require('../../assets/flagpng/bf.png'),
  },
  {
    answer: ['Bulgaria', 'Lào', 'Grenada', 'Zambia'],
    correct: 0,
    id: 'BG',
    index: 21,
    name: 'Bulgaria',
    uri: require('../../assets/flagpng/bg.png'),
  },
  {
    answer: ['Suriname', 'Bahrain', 'Lào', 'Séc'],
    correct: 1,
    id: 'BH',
    index: 22,
    name: 'Bahrain',
    uri: require('../../assets/flagpng/bh.png'),
  },
  {
    answer: ['Lesotho', 'Estonia', 'Tuvalu', 'Burundi'],
    correct: 3,
    id: 'BI',
    index: 23,
    name: 'Burundi',
    uri: require('../../assets/flagpng/bi.png'),
  },
  {
    answer: ['Liechtenstein', 'Bahamas', 'Tuvalu', 'Benin'],
    correct: 3,
    id: 'BJ',
    index: 24,
    name: 'Benin',
    uri: require('../../assets/flagpng/bj.png'),
  },
  {
    answer: ['Đông Timor', 'Cameroon', 'Brunei Darussalam', 'Italy'],
    correct: 2,
    id: 'BN',
    index: 27,
    name: 'Brunei Darussalam',
    uri: require('../../assets/flagpng/bn.png'),
  },
  {
    answer: ['Nepal', 'Saint Kitts và Nevis', 'Brunei Darussalam', 'Bolivia'],
    correct: 3,
    id: 'BO',
    index: 28,
    name: 'Bolivia',
    uri: require('../../assets/flagpng/bo.png'),
  },
  {
    answer: ['Indonesia', 'Brazil', 'Belize', 'Nepal'],
    correct: 1,
    id: 'BR',
    index: 29,
    name: 'Brazil',
    uri: require('../../assets/flagpng/br.png'),
  },
  {
    answer: ['Ấn Độ', 'Bahamas', 'Trung Quốc', 'Togo'],
    correct: 1,
    id: 'BS',
    index: 30,
    name: 'Bahamas',
    uri: require('../../assets/flagpng/bs.png'),
  },
  {
    answer: ['Bhutan', 'Syria', 'Nicaragua', 'Colombia'],
    correct: 0,
    id: 'BT',
    index: 31,
    name: 'Bhutan',
    uri: require('../../assets/flagpng/bt.png'),
  },
  {
    answer: ['Tajikistan', 'Botswana', 'Ghana', 'Liberia'],
    correct: 1,
    id: 'BW',
    index: 33,
    name: 'Botswana',
    uri: require('../../assets/flagpng/bw.png'),
  },
  {
    answer: ['Malawi', 'Trung Quốc', 'Swaziland', 'Belarus'],
    correct: 3,
    id: 'BY',
    index: 34,
    name: 'Belarus',
    uri: require('../../assets/flagpng/by.png'),
  },
  {
    answer: ['Ba Lan', 'Gambia', 'Belize', 'Lithuania'],
    correct: 2,
    id: 'BZ',
    index: 35,
    name: 'Belize',
    uri: require('../../assets/flagpng/bz.png'),
  },
  {
    answer: ['Andorra', 'Canada', 'Saint Lucia', 'Yemen'],
    correct: 1,
    id: 'CA',
    index: 36,
    name: 'Canada',
    uri: require('../../assets/flagpng/ca.png'),
  },
  {
    answer: ['Argentina', 'Cộng hoà dân chủ Congo', 'Senegal', 'Guyana'],
    correct: 1,
    id: 'CD',
    index: 38,
    name: 'Cộng hoà dân chủ Congo',
    uri: require('../../assets/flagpng/cd.png'),
  },
  {
    answer: ['Panama', 'Moldova', 'Cộng hòa Trung Phi', 'Indonesia'],
    correct: 2,
    id: 'CF',
    index: 39,
    name: 'Cộng hòa Trung Phi',
    uri: require('../../assets/flagpng/cf.png'),
  },
  {
    answer: [
      'Quần đảo Solomon',
      'Cộng hoà Congo',
      'Indonesia',
      'Vương quốc Anh',
    ],
    correct: 1,
    id: 'CG',
    index: 40,
    name: 'Cộng hoà Congo',
    uri: require('../../assets/flagpng/cg.png'),
  },
  {
    answer: ['Thụy Sỹ', 'Hy Lạp', 'Bulgaria', 'Uruguay'],
    correct: 0,
    id: 'CH',
    index: 41,
    name: 'Thụy Sỹ',
    uri: require('../../assets/flagpng/ch.png'),
  },
  {
    answer: ['Bờ Biển Ngà', 'Pakistan', 'Canada', 'Mexico'],
    correct: 0,
    id: 'CI',
    index: 42,
    name: 'Bờ Biển Ngà',
    uri: require('../../assets/flagpng/ci.png'),
  },
  {
    answer: ['Chile', 'Moldova', 'Brunei Darussalam', 'Mỹ (Hoa Kỳ)'],
    correct: 0,
    id: 'CL',
    index: 44,
    name: 'Chile',
    uri: require('../../assets/flagpng/cl.png'),
  },
  {
    answer: ['Cameroon', 'Estonia', 'Thailand', 'Jordan'],
    correct: 0,
    id: 'CM',
    index: 45,
    name: 'Cameroon',
    uri: require('../../assets/flagpng/cm.png'),
  },
  {
    answer: ['Trung Quốc', 'Sudan', 'Luxembourg', 'Brunei Darussalam'],
    correct: 0,
    id: 'CN',
    index: 46,
    name: 'Trung Quốc',
    uri: require('../../assets/flagpng/cn.png'),
  },
  {
    answer: ['Nam Phi', 'Chile', 'Colombia', 'Equatorial Guinea'],
    correct: 2,
    id: 'CO',
    index: 47,
    name: 'Colombia',
    uri: require('../../assets/flagpng/co.png'),
  },
  {
    answer: ['Costa Rica', 'Mexico', 'Suriname', 'Úc'],
    correct: 0,
    id: 'CR',
    index: 48,
    name: 'Costa Rica',
    uri: require('../../assets/flagpng/cr.png'),
  },
  {
    answer: ['Thailand', 'Cuba', 'Áo', 'Comoros'],
    correct: 1,
    id: 'CU',
    index: 49,
    name: 'Cuba',
    uri: require('../../assets/flagpng/cu.png'),
  },
  {
    answer: ['Áo', 'Cape Verde', 'Ả Rập Xê Út', 'Luxembourg'],
    correct: 1,
    id: 'CV',
    index: 50,
    name: 'Cape Verde',
    uri: require('../../assets/flagpng/cv.png'),
  },
  {
    answer: ['Đảo Síp', 'Syria', 'Séc', 'Lào'],
    correct: 0,
    id: 'CY',
    index: 53,
    name: 'Đảo Síp',
    uri: require('../../assets/flagpng/cy.png'),
  },
  {
    answer: ['Nhật Bản', 'Slovakia', 'Denmark', 'Séc'],
    correct: 3,
    id: 'CZ',
    index: 54,
    name: 'Séc',
    uri: require('../../assets/flagpng/cz.png'),
  },
  {
    answer: ['Liechtenstein', 'Albania', 'Đức', 'Uruguay'],
    correct: 2,
    id: 'DE',
    index: 55,
    name: 'Đức',
    uri: require('../../assets/flagpng/de.png'),
  },
  {
    answer: [
      'Swaziland',
      'Mauritania',
      'Djibouti',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 2,
    id: 'DJ',
    index: 56,
    name: 'Djibouti',
    uri: require('../../assets/flagpng/dj.png'),
  },
  {
    answer: ['Trinidad và Tobago', 'Denmark', 'Liberia', 'Colombia'],
    correct: 1,
    id: 'DK',
    index: 57,
    name: 'Denmark',
    uri: require('../../assets/flagpng/dk.png'),
  },
  {
    answer: ['Somalia', 'Dominica', 'Estonia', 'Lithuania'],
    correct: 1,
    id: 'DM',
    index: 58,
    name: 'Dominica',
    uri: require('../../assets/flagpng/dm.png'),
  },
  {
    answer: [
      'Ukraine',
      'Cộng hòa Dominica',
      'Marshall Islands',
      'Cộng hoà Congo',
    ],
    correct: 1,
    id: 'DO',
    index: 59,
    name: 'Cộng hòa Dominica',
    uri: require('../../assets/flagpng/do.png'),
  },
  {
    answer: ['Kiribati', 'Suriname', 'Azerbaijan', 'Algeria'],
    correct: 3,
    id: 'DZ',
    index: 60,
    name: 'Algeria',
    uri: require('../../assets/flagpng/dz.png'),
  },
  {
    answer: ['Ecuador', 'Belize', 'Thổ Nhĩ Kỳ', 'Hungary'],
    correct: 0,
    id: 'EC',
    index: 61,
    name: 'Ecuador',
    uri: require('../../assets/flagpng/ec.png'),
  },
  {
    answer: ['Estonia', 'Portugal', 'Vương quốc Anh', 'Equatorial Guinea'],
    correct: 0,
    id: 'EE',
    index: 62,
    name: 'Estonia',
    uri: require('../../assets/flagpng/ee.png'),
  },
  {
    answer: ['Egypt', 'Botswana', 'Papua New Guinea', 'Lesotho'],
    correct: 0,
    id: 'EG',
    index: 63,
    name: 'Egypt',
    uri: require('../../assets/flagpng/eg.png'),
  },
  {
    answer: ['Jordan', 'Bỉ', 'Nga', 'Eritrea'],
    correct: 3,
    id: 'ER',
    index: 65,
    name: 'Eritrea',
    uri: require('../../assets/flagpng/er.png'),
  },
  {
    answer: ['Kyrgyzstan', 'Tây Ban Nha', 'Kuwait', 'Venezuela'],
    correct: 1,
    id: 'ES',
    index: 66,
    name: 'Tây Ban Nha',
    uri: require('../../assets/flagpng/es.png'),
  },
  {
    answer: ['Eritrea', 'Ethiopia', 'Uganda', 'Sri Lanka'],
    correct: 1,
    id: 'ET',
    index: 67,
    name: 'Ethiopia',
    uri: require('../../assets/flagpng/et.png'),
  },
  {
    answer: ['Phần Lan', 'Cộng hòa Dominica', 'Rwanda', 'Kuwait'],
    correct: 0,
    id: 'FI',
    index: 69,
    name: 'Phần Lan',
    uri: require('../../assets/flagpng/fi.png'),
  },
  {
    answer: ['Samoa', 'Bờ Biển Ngà', 'Montenegro', 'Fiji'],
    correct: 3,
    id: 'FJ',
    index: 70,
    name: 'Fiji',
    uri: require('../../assets/flagpng/fj.png'),
  },
  {
    answer: ['Micronesia', 'Phần Lan', 'Kyrgyzstan', 'Quần đảo Solomon'],
    correct: 0,
    id: 'FM',
    index: 72,
    name: 'Micronesia',
    uri: require('../../assets/flagpng/fm.png'),
  },
  {
    answer: ['Pháp', 'Honduras', 'Pakistan', 'Brazil'],
    correct: 0,
    id: 'FR',
    index: 74,
    name: 'Pháp',
    uri: require('../../assets/flagpng/fr.png'),
  },
  {
    answer: ['Monaco', 'Cộng hoà dân chủ Congo', 'Slovenia', 'Gabon'],
    correct: 3,
    id: 'GA',
    index: 75,
    name: 'Gabon',
    uri: require('../../assets/flagpng/ga.png'),
  },
  {
    answer: ['Vương quốc Anh', 'Bhutan', 'Suriname', 'Saint Lucia'],
    correct: 0,
    id: 'GB',
    index: 80,
    name: 'Vương quốc Anh',
    uri: require('../../assets/flagpng/gb.png'),
  },
  {
    answer: ['Grenada', 'Liberia', 'Suriname', 'Bahamas'],
    correct: 0,
    id: 'GD',
    index: 81,
    name: 'Grenada',
    uri: require('../../assets/flagpng/gd.png'),
  },
  {
    answer: ['São Tomé và Príncipe', 'Nigeria', 'Georgia', 'Bolivia'],
    correct: 2,
    id: 'GE',
    index: 82,
    name: 'Georgia',
    uri: require('../../assets/flagpng/ge.png'),
  },
  {
    answer: ['Iraq', 'Ghana', 'Egypt', 'Chad'],
    correct: 1,
    id: 'GH',
    index: 85,
    name: 'Ghana',
    uri: require('../../assets/flagpng/gh.png'),
  },
  {
    answer: ['Gambia', 'Costa Rica', 'Guinea-Bissau', 'South Sudan'],
    correct: 0,
    id: 'GM',
    index: 88,
    name: 'Gambia',
    uri: require('../../assets/flagpng/gm.png'),
  },
  {
    answer: ['Úc', 'El Salvador', 'Hungary', 'Guinea'],
    correct: 3,
    id: 'GN',
    index: 89,
    name: 'Guinea',
    uri: require('../../assets/flagpng/gn.png'),
  },
  {
    answer: ['Guatemala', 'Burkina Faso', 'Togo', 'Equatorial Guinea'],
    correct: 3,
    id: 'GQ',
    index: 91,
    name: 'Equatorial Guinea',
    uri: require('../../assets/flagpng/gq.png'),
  },
  {
    answer: ['Hy Lạp', 'Tuvalu', 'Guinea-Bissau', 'Thụy Sỹ'],
    correct: 0,
    id: 'GR',
    index: 92,
    name: 'Hy Lạp',
    uri: require('../../assets/flagpng/gr.png'),
  },
  {
    answer: ['Pakistan', 'Hà Lan', 'Guatemala', 'Belarus'],
    correct: 2,
    id: 'GT',
    index: 94,
    name: 'Guatemala',
    uri: require('../../assets/flagpng/gt.png'),
  },
  {
    answer: ['Ecuador', 'Uzbekistan', 'Niger', 'Guinea-Bissau'],
    correct: 3,
    id: 'GW',
    index: 96,
    name: 'Guinea-Bissau',
    uri: require('../../assets/flagpng/gw.png'),
  },
  {
    answer: ['Guyana', 'Mauritania', 'Vanuatu', 'Djibouti'],
    correct: 0,
    id: 'GY',
    index: 97,
    name: 'Guyana',
    uri: require('../../assets/flagpng/gy.png'),
  },
  {
    answer: ['Honduras', 'Guinea-Bissau', 'Oman', 'Séc'],
    correct: 0,
    id: 'HN',
    index: 100,
    name: 'Honduras',
    uri: require('../../assets/flagpng/hn.png'),
  },
  {
    answer: ['Croatia', 'San Marino', 'Antigua và Barbuda', 'Mozambique'],
    correct: 0,
    id: 'HR',
    index: 101,
    name: 'Croatia',
    uri: require('../../assets/flagpng/hr.png'),
  },
  {
    answer: ['Bỉ', 'Italy', 'Haiti', 'Tajikistan'],
    correct: 2,
    id: 'HT',
    index: 102,
    name: 'Haiti',
    uri: require('../../assets/flagpng/ht.png'),
  },
  {
    answer: ['Hungary', 'Antigua và Barbuda', 'Latvia', 'El Salvador'],
    correct: 0,
    id: 'HU',
    index: 103,
    name: 'Hungary',
    uri: require('../../assets/flagpng/hu.png'),
  },
  {
    answer: ['Peru', 'Georgia', 'Indonesia', 'Mozambique'],
    correct: 2,
    id: 'ID',
    index: 104,
    name: 'Indonesia',
    uri: require('../../assets/flagpng/id.png'),
  },
  {
    answer: ['Ireland', 'Uganda', 'Albania', 'Iceland'],
    correct: 0,
    id: 'IE',
    index: 105,
    name: 'Ireland',
    uri: require('../../assets/flagpng/ie.png'),
  },
  {
    answer: ['Rwanda', 'Croatia', 'Barbados', 'Israel'],
    correct: 3,
    id: 'IL',
    index: 106,
    name: 'Israel',
    uri: require('../../assets/flagpng/il.png'),
  },
  {
    answer: ['Romania', 'Ấn Độ', 'Albania', 'Madagascar'],
    correct: 1,
    id: 'IN',
    index: 108,
    name: 'Ấn Độ',
    uri: require('../../assets/flagpng/in.png'),
  },
  {
    answer: ['Bosnia và Herzegovina', 'Iraq', 'Zimbabwe', 'Guinea'],
    correct: 1,
    id: 'IQ',
    index: 110,
    name: 'Iraq',
    uri: require('../../assets/flagpng/iq.png'),
  },
  {
    answer: ['Gabon', 'Italy', 'Iran', 'Palau'],
    correct: 2,
    id: 'IR',
    index: 111,
    name: 'Iran',
    uri: require('../../assets/flagpng/ir.png'),
  },
  {
    answer: ['Iceland', 'Bờ Biển Ngà', 'Oman', 'Campuchia'],
    correct: 0,
    id: 'IS',
    index: 112,
    name: 'Iceland',
    uri: require('../../assets/flagpng/is.png'),
  },
  {
    answer: ['Albania', 'Italy', 'Campuchia', 'Papua New Guinea'],
    correct: 1,
    id: 'IT',
    index: 113,
    name: 'Italy',
    uri: require('../../assets/flagpng/it.png'),
  },
  {
    answer: ['Guyana', 'Jamaica', 'Thụy Điển', 'Afghanistan'],
    correct: 1,
    id: 'JM',
    index: 115,
    name: 'Jamaica',
    uri: require('../../assets/flagpng/jm.png'),
  },
  {
    answer: ['Malaysia', 'Jordan', 'Đảo Síp', 'Philippines'],
    correct: 1,
    id: 'JO',
    index: 116,
    name: 'Jordan',
    uri: require('../../assets/flagpng/jo.png'),
  },
  {
    answer: ['Hy Lạp', 'Micronesia', 'Ba Lan', 'Nhật Bản'],
    correct: 3,
    id: 'JP',
    index: 117,
    name: 'Nhật Bản',
    uri: require('../../assets/flagpng/jp.png'),
  },
  {
    answer: ['Séc', 'Kenya', 'Mali', 'Slovenia'],
    correct: 1,
    id: 'KE',
    index: 118,
    name: 'Kenya',
    uri: require('../../assets/flagpng/ke.png'),
  },
  {
    answer: ['Kyrgyzstan', 'Estonia', 'Jamaica', 'Thụy Điển'],
    correct: 0,
    id: 'KG',
    index: 119,
    name: 'Kyrgyzstan',
    uri: require('../../assets/flagpng/kg.png'),
  },
  {
    answer: ['Campuchia', 'Thổ Nhĩ Kỳ', 'Belize', 'Latvia'],
    correct: 0,
    id: 'KH',
    index: 120,
    name: 'Campuchia',
    uri: require('../../assets/flagpng/kh.png'),
  },
  {
    answer: ['South Sudan', 'Denmark', 'Kiribati', 'Hà Lan'],
    correct: 2,
    id: 'KI',
    index: 121,
    name: 'Kiribati',
    uri: require('../../assets/flagpng/ki.png'),
  },
  {
    answer: ['Comoros', 'Gabon', 'Papua New Guinea', 'North Macedonia'],
    correct: 0,
    id: 'KM',
    index: 122,
    name: 'Comoros',
    uri: require('../../assets/flagpng/km.png'),
  },
  {
    answer: ['Saint Kitts và Nevis', 'Thụy Sỹ', 'Guyana', 'Tuvalu'],
    correct: 0,
    id: 'KN',
    index: 123,
    name: 'Saint Kitts và Nevis',
    uri: require('../../assets/flagpng/kn.png'),
  },
  {
    answer: ['Ả Rập Xê Út', 'Maldives', 'Egypt', 'Triều Tiên'],
    correct: 3,
    id: 'KP',
    index: 124,
    name: 'Triều Tiên',
    uri: require('../../assets/flagpng/kp.png'),
  },
  {
    answer: ['Saint Kitts và Nevis', 'Swaziland', 'Bhutan', 'Hàn Quốc'],
    correct: 3,
    id: 'KR',
    index: 125,
    name: 'Hàn Quốc',
    uri: require('../../assets/flagpng/kr.png'),
  },
  {
    answer: ['Tajikistan', 'Hà Lan', 'Kuwait', 'Gambia'],
    correct: 2,
    id: 'KW',
    index: 126,
    name: 'Kuwait',
    uri: require('../../assets/flagpng/kw.png'),
  },
  {
    answer: ['Cuba', 'Uzbekistan', 'Li-băng', 'Kazakhstan'],
    correct: 3,
    id: 'KZ',
    index: 128,
    name: 'Kazakhstan',
    uri: require('../../assets/flagpng/kz.png'),
  },
  {
    answer: ['Lào', 'Ả Rập Xê Út', 'Cameroon', 'Israel'],
    correct: 0,
    id: 'LA',
    index: 129,
    name: 'Lào',
    uri: require('../../assets/flagpng/la.png'),
  },
  {
    answer: ['Namibia', 'Cộng hoà dân chủ Congo', 'Li-băng', 'Senegal'],
    correct: 2,
    id: 'LB',
    index: 130,
    name: 'Li-băng',
    uri: require('../../assets/flagpng/lb.png'),
  },
  {
    answer: ['Saint Lucia', 'Peru', 'Cameroon', 'Libya'],
    correct: 0,
    id: 'LC',
    index: 131,
    name: 'Saint Lucia',
    uri: require('../../assets/flagpng/lc.png'),
  },
  {
    answer: ['Liechtenstein', 'Yemen', 'Bosnia và Herzegovina', 'Mali'],
    correct: 0,
    id: 'LI',
    index: 132,
    name: 'Liechtenstein',
    uri: require('../../assets/flagpng/li.png'),
  },
  {
    answer: ['Ireland', 'Sri Lanka', 'Antigua và Barbuda', 'Somalia'],
    correct: 1,
    id: 'LK',
    index: 133,
    name: 'Sri Lanka',
    uri: require('../../assets/flagpng/lk.png'),
  },
  {
    answer: ['Jamaica', 'Ả Rập Xê Út', 'Liberia', 'Fiji'],
    correct: 2,
    id: 'LR',
    index: 134,
    name: 'Liberia',
    uri: require('../../assets/flagpng/lr.png'),
  },
  {
    answer: ['Việt Nam', 'Indonesia', 'Lesotho', 'Bỉ'],
    correct: 2,
    id: 'LS',
    index: 135,
    name: 'Lesotho',
    uri: require('../../assets/flagpng/ls.png'),
  },
  {
    answer: ['Suriname', 'Ghana', 'Lithuania', 'Malaysia'],
    correct: 2,
    id: 'LT',
    index: 136,
    name: 'Lithuania',
    uri: require('../../assets/flagpng/lt.png'),
  },
  {
    answer: ['Bolivia', 'Luxembourg', 'Ma-rốc', 'Oman'],
    correct: 1,
    id: 'LU',
    index: 137,
    name: 'Luxembourg',
    uri: require('../../assets/flagpng/lu.png'),
  },
  {
    answer: ['Thổ Nhĩ Kỳ', 'Myanmar', 'Afghanistan', 'Latvia'],
    correct: 3,
    id: 'LV',
    index: 138,
    name: 'Latvia',
    uri: require('../../assets/flagpng/lv.png'),
  },
  {
    answer: ['Comoros', 'Vanuatu', 'Libya', 'Costa Rica'],
    correct: 2,
    id: 'LY',
    index: 139,
    name: 'Libya',
    uri: require('../../assets/flagpng/ly.png'),
  },
  {
    answer: ['Ma-rốc', 'Saint Kitts và Nevis', 'Tajikistan', 'Benin'],
    correct: 0,
    id: 'MA',
    index: 140,
    name: 'Ma-rốc',
    uri: require('../../assets/flagpng/ma.png'),
  },
  {
    answer: ['Andorra', 'Luxembourg', 'Monaco', 'Qatar'],
    correct: 2,
    id: 'MC',
    index: 141,
    name: 'Monaco',
    uri: require('../../assets/flagpng/mc.png'),
  },
  {
    answer: ['Moldova', 'Samoa', 'Jamaica', 'Tây Ban Nha'],
    correct: 0,
    id: 'MD',
    index: 142,
    name: 'Moldova',
    uri: require('../../assets/flagpng/md.png'),
  },
  {
    answer: ['Gabon', 'Montenegro', 'Kyrgyzstan', 'New Zealand'],
    correct: 1,
    id: 'ME',
    index: 143,
    name: 'Montenegro',
    uri: require('../../assets/flagpng/me.png'),
  },
  {
    answer: ['Azerbaijan', 'Equatorial Guinea', 'Togo', 'Madagascar'],
    correct: 3,
    id: 'MG',
    index: 145,
    name: 'Madagascar',
    uri: require('../../assets/flagpng/mg.png'),
  },
  {
    answer: ['Cộng hoà Congo', 'Marshall Islands', 'Jamaica', 'San Marino'],
    correct: 1,
    id: 'MH',
    index: 146,
    name: 'Marshall Islands',
    uri: require('../../assets/flagpng/mh.png'),
  },
  {
    answer: ['New Zealand', 'North Macedonia', 'Belize', 'Lào'],
    correct: 1,
    id: 'MK',
    index: 147,
    name: 'North Macedonia',
    uri: require('../../assets/flagpng/mk.png'),
  },
  {
    answer: ['Vanuatu', 'Mali', 'Ấn Độ', 'Cộng hòa Trung Phi'],
    correct: 1,
    id: 'ML',
    index: 148,
    name: 'Mali',
    uri: require('../../assets/flagpng/ml.png'),
  },
  {
    answer: ['Kazakhstan', 'New Zealand', 'Myanmar', 'Bờ Biển Ngà'],
    correct: 2,
    id: 'MM',
    index: 149,
    name: 'Myanmar',
    uri: require('../../assets/flagpng/mm.png'),
  },
  {
    answer: ['Mongolia', 'Malaysia', 'Sierra Leone', 'Micronesia'],
    correct: 0,
    id: 'MN',
    index: 150,
    name: 'Mongolia',
    uri: require('../../assets/flagpng/mn.png'),
  },
  {
    answer: [
      'Các tiểu vương quốc Ả Rập Thống nhất',
      'Madagascar',
      'Tajikistan',
      'Mauritania',
    ],
    correct: 3,
    id: 'MR',
    index: 154,
    name: 'Mauritania',
    uri: require('../../assets/flagpng/mr.png'),
  },
  {
    answer: ['Triều Tiên', 'Cameroon', 'Malta', 'Rwanda'],
    correct: 2,
    id: 'MT',
    index: 156,
    name: 'Malta',
    uri: require('../../assets/flagpng/mt.png'),
  },
  {
    answer: ['Mauritius', 'Kuwait', 'Rwanda', 'Bờ Biển Ngà'],
    correct: 0,
    id: 'MU',
    index: 157,
    name: 'Mauritius',
    uri: require('../../assets/flagpng/mu.png'),
  },
  {
    answer: [
      'Lithuania',
      'El Salvador',
      'Maldives',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 2,
    id: 'MV',
    index: 158,
    name: 'Maldives',
    uri: require('../../assets/flagpng/mv.png'),
  },
  {
    answer: ['Cộng hoà Congo', 'Malawi', 'Namibia', 'Yemen'],
    correct: 1,
    id: 'MW',
    index: 159,
    name: 'Malawi',
    uri: require('../../assets/flagpng/mw.png'),
  },
  {
    answer: ['Mexico', 'Tajikistan', 'Guatemala', 'Pháp'],
    correct: 0,
    id: 'MX',
    index: 160,
    name: 'Mexico',
    uri: require('../../assets/flagpng/mx.png'),
  },
  {
    answer: ['Burundi', 'Saint Vincent và Grenadines', 'Malaysia', 'Italy'],
    correct: 2,
    id: 'MY',
    index: 161,
    name: 'Malaysia',
    uri: require('../../assets/flagpng/my.png'),
  },
  {
    answer: ['Mozambique', 'Italy', 'Ecuador', 'San Marino'],
    correct: 0,
    id: 'MZ',
    index: 162,
    name: 'Mozambique',
    uri: require('../../assets/flagpng/mz.png'),
  },
  {
    answer: ['Namibia', 'Mỹ (Hoa Kỳ)', 'Cộng hòa Dominica', 'Italy'],
    correct: 0,
    id: 'NA',
    index: 163,
    name: 'Namibia',
    uri: require('../../assets/flagpng/na.png'),
  },
  {
    answer: ['Niger', 'Bờ Biển Ngà', 'Nigeria', 'Sierra Leone'],
    correct: 0,
    id: 'NE',
    index: 165,
    name: 'Niger',
    uri: require('../../assets/flagpng/ne.png'),
  },
  {
    answer: ['Turkmenistan', 'Niger', 'Nigeria', 'Burkina Faso'],
    correct: 2,
    id: 'NG',
    index: 167,
    name: 'Nigeria',
    uri: require('../../assets/flagpng/ng.png'),
  },
  {
    answer: ['Luxembourg', 'Papua New Guinea', 'Nicaragua', 'Micronesia'],
    correct: 2,
    id: 'NI',
    index: 168,
    name: 'Nicaragua',
    uri: require('../../assets/flagpng/ni.png'),
  },
  {
    answer: ['Hungary', 'Bangladesh', 'Saint Vincent và Grenadines', 'Hà Lan'],
    correct: 3,
    id: 'NL',
    index: 169,
    name: 'Hà Lan',
    uri: require('../../assets/flagpng/nl.png'),
  },
  {
    answer: ['Luxembourg', 'Na Uy', 'Cuba', 'Tuvalu'],
    correct: 1,
    id: 'NO',
    index: 170,
    name: 'Na Uy',
    uri: require('../../assets/flagpng/no.png'),
  },
  {
    answer: ['Việt Nam', 'Mali', 'Canada', 'Nepal'],
    correct: 3,
    id: 'NP',
    index: 171,
    name: 'Nepal',
    uri: require('../../assets/flagpng/np.png'),
  },
  {
    answer: ['Mauritius', 'Angola', 'Nauru', 'El Salvador'],
    correct: 2,
    id: 'NR',
    index: 172,
    name: 'Nauru',
    uri: require('../../assets/flagpng/nr.png'),
  },
  {
    answer: ['Pakistan', 'Montenegro', 'New Zealand', 'Micronesia'],
    correct: 2,
    id: 'NZ',
    index: 174,
    name: 'New Zealand',
    uri: require('../../assets/flagpng/nz.png'),
  },
  {
    answer: ['Nam Phi', 'Luxembourg', 'Oman', 'Andorra'],
    correct: 2,
    id: 'OM',
    index: 175,
    name: 'Oman',
    uri: require('../../assets/flagpng/om.png'),
  },
  {
    answer: ['Egypt', 'Panama', 'Sri Lanka', 'São Tomé và Príncipe'],
    correct: 1,
    id: 'PA',
    index: 176,
    name: 'Panama',
    uri: require('../../assets/flagpng/pa.png'),
  },
  {
    answer: ['Myanmar', 'Gabon', 'Peru', 'Nam Phi'],
    correct: 2,
    id: 'PE',
    index: 177,
    name: 'Peru',
    uri: require('../../assets/flagpng/pe.png'),
  },
  {
    answer: ['Benin', 'Mauritius', 'Papua New Guinea', 'Thailand'],
    correct: 2,
    id: 'PG',
    index: 179,
    name: 'Papua New Guinea',
    uri: require('../../assets/flagpng/pg.png'),
  },
  {
    answer: ['Paraguay', 'Mozambique', 'Philippines', 'Vương quốc Anh'],
    correct: 2,
    id: 'PH',
    index: 180,
    name: 'Philippines',
    uri: require('../../assets/flagpng/ph.png'),
  },
  {
    answer: ['Mexico', 'Angola', 'Senegal', 'Pakistan'],
    correct: 3,
    id: 'PK',
    index: 181,
    name: 'Pakistan',
    uri: require('../../assets/flagpng/pk.png'),
  },
  {
    answer: ['Ba Lan', 'Pháp', 'Croatia', 'Nauru'],
    correct: 0,
    id: 'PL',
    index: 182,
    name: 'Ba Lan',
    uri: require('../../assets/flagpng/pl.png'),
  },
  {
    answer: ['Portugal', 'Sudan', 'Ghana', 'Haiti'],
    correct: 0,
    id: 'PT',
    index: 187,
    name: 'Portugal',
    uri: require('../../assets/flagpng/pt.png'),
  },
  {
    answer: ['Belarus', 'Nam Phi', 'Palau', 'Kyrgyzstan'],
    correct: 2,
    id: 'PW',
    index: 188,
    name: 'Palau',
    uri: require('../../assets/flagpng/pw.png'),
  },
  {
    answer: ['Mexico', 'Tonga', 'Bulgaria', 'Paraguay'],
    correct: 3,
    id: 'PY',
    index: 189,
    name: 'Paraguay',
    uri: require('../../assets/flagpng/py.png'),
  },
  {
    answer: ['Ukraine', 'Chile', 'Qatar', 'Moldova'],
    correct: 2,
    id: 'QA',
    index: 190,
    name: 'Qatar',
    uri: require('../../assets/flagpng/qa.png'),
  },
  {
    answer: ['Kenya', 'Thailand', 'Romania', 'Bahrain'],
    correct: 2,
    id: 'RO',
    index: 192,
    name: 'Romania',
    uri: require('../../assets/flagpng/ro.png'),
  },
  {
    answer: [
      'Honduras',
      'Serbia',
      'New Zealand',
      'Các tiểu vương quốc Ả Rập Thống nhất',
    ],
    correct: 1,
    id: 'RS',
    index: 193,
    name: 'Serbia',
    uri: require('../../assets/flagpng/rs.png'),
  },
  {
    answer: ['Nga', 'Trinidad và Tobago', 'Barbados', 'Malawi'],
    correct: 0,
    id: 'RU',
    index: 194,
    name: 'Nga',
    uri: require('../../assets/flagpng/ru.png'),
  },
  {
    answer: ['Rwanda', 'Gabon', 'Tajikistan', 'Mali'],
    correct: 0,
    id: 'RW',
    index: 195,
    name: 'Rwanda',
    uri: require('../../assets/flagpng/rw.png'),
  },
  {
    answer: ['New Zealand', 'Ả Rập Xê Út', 'Trung Quốc', 'Guinea-Bissau'],
    correct: 1,
    id: 'SA',
    index: 196,
    name: 'Ả Rập Xê Út',
    uri: require('../../assets/flagpng/sa.png'),
  },
  {
    answer: ['Slovenia', 'Jordan', 'Armenia', 'Quần đảo Solomon'],
    correct: 3,
    id: 'SB',
    index: 197,
    name: 'Quần đảo Solomon',
    uri: require('../../assets/flagpng/sb.png'),
  },
  {
    answer: ['Đông Timor', 'Seychelles', 'Campuchia', 'Andorra'],
    correct: 1,
    id: 'SC',
    index: 198,
    name: 'Seychelles',
    uri: require('../../assets/flagpng/sc.png'),
  },
  {
    answer: ['Tonga', 'Israel', 'Eritrea', 'Sudan'],
    correct: 3,
    id: 'SD',
    index: 199,
    name: 'Sudan',
    uri: require('../../assets/flagpng/sd.png'),
  },
  {
    answer: ['Thụy Điển', 'Cape Verde', 'Li-băng', 'Philippines'],
    correct: 0,
    id: 'SE',
    index: 200,
    name: 'Thụy Điển',
    uri: require('../../assets/flagpng/se.png'),
  },
  {
    answer: ['Grenada', 'Singapore', 'São Tomé và Príncipe', 'Ma-rốc'],
    correct: 1,
    id: 'SG',
    index: 201,
    name: 'Singapore',
    uri: require('../../assets/flagpng/sg.png'),
  },
  {
    answer: ['Thụy Điển', 'Costa Rica', 'Honduras', 'Slovenia'],
    correct: 3,
    id: 'SI',
    index: 203,
    name: 'Slovenia',
    uri: require('../../assets/flagpng/si.png'),
  },
  {
    answer: ['Monaco', 'Slovakia', 'Chad', 'Belize'],
    correct: 1,
    id: 'SK',
    index: 205,
    name: 'Slovakia',
    uri: require('../../assets/flagpng/sk.png'),
  },
  {
    answer: ['Sierra Leone', 'Belarus', 'Nhật Bản', 'Thổ Nhĩ Kỳ'],
    correct: 0,
    id: 'SL',
    index: 206,
    name: 'Sierra Leone',
    uri: require('../../assets/flagpng/sl.png'),
  },
  {
    answer: ['Burundi', 'San Marino', 'Sierra Leone', 'Iceland'],
    correct: 1,
    id: 'SM',
    index: 207,
    name: 'San Marino',
    uri: require('../../assets/flagpng/sm.png'),
  },
  {
    answer: ['Italy', 'Nam Phi', 'Senegal', 'Bangladesh'],
    correct: 2,
    id: 'SN',
    index: 208,
    name: 'Senegal',
    uri: require('../../assets/flagpng/sn.png'),
  },
  {
    answer: ['Somalia', 'Philippines', 'Cộng hoà Congo', 'Libya'],
    correct: 0,
    id: 'SO',
    index: 209,
    name: 'Somalia',
    uri: require('../../assets/flagpng/so.png'),
  },
  {
    answer: ['Sierra Leone', 'Na Uy', 'Micronesia', 'Suriname'],
    correct: 3,
    id: 'SR',
    index: 210,
    name: 'Suriname',
    uri: require('../../assets/flagpng/sr.png'),
  },
  {
    answer: ['Niger', 'Serbia', 'Cameroon', 'South Sudan'],
    correct: 3,
    id: 'SS',
    index: 211,
    name: 'South Sudan',
    uri: require('../../assets/flagpng/ss.png'),
  },
  {
    answer: ['Myanmar', 'Philippines', 'Estonia', 'São Tomé và Príncipe'],
    correct: 3,
    id: 'ST',
    index: 212,
    name: 'São Tomé và Príncipe',
    uri: require('../../assets/flagpng/st.png'),
  },
  {
    answer: ['El Salvador', 'Ghana', 'Ma-rốc', 'Ukraine'],
    correct: 0,
    id: 'SV',
    index: 213,
    name: 'El Salvador',
    uri: require('../../assets/flagpng/sv.png'),
  },
  {
    answer: ['Syria', 'Uzbekistan', 'Tây Ban Nha', 'Maldives'],
    correct: 0,
    id: 'SY',
    index: 215,
    name: 'Syria',
    uri: require('../../assets/flagpng/sy.png'),
  },
  {
    answer: ['Djibouti', 'Hà Lan', 'Paraguay', 'Swaziland'],
    correct: 3,
    id: 'SZ',
    index: 216,
    name: 'Swaziland',
    uri: require('../../assets/flagpng/sz.png'),
  },
  {
    answer: ['Nhật Bản', 'Quần đảo Solomon', 'Chad', 'Phần Lan'],
    correct: 2,
    id: 'TD',
    index: 218,
    name: 'Chad',
    uri: require('../../assets/flagpng/td.png'),
  },
  {
    answer: ['South Sudan', 'Maldives', 'Togo', 'Afghanistan'],
    correct: 2,
    id: 'TG',
    index: 220,
    name: 'Togo',
    uri: require('../../assets/flagpng/tg.png'),
  },
  {
    answer: ['Panama', 'Thailand', 'Thụy Sỹ', 'Indonesia'],
    correct: 1,
    id: 'TH',
    index: 221,
    name: 'Thailand',
    uri: require('../../assets/flagpng/th.png'),
  },
  {
    answer: ['Tajikistan', 'Rwanda', 'Trung Quốc', 'Kuwait'],
    correct: 0,
    id: 'TJ',
    index: 222,
    name: 'Tajikistan',
    uri: require('../../assets/flagpng/tj.png'),
  },
  {
    answer: ['Đông Timor', 'Indonesia', 'Cameroon', 'Vanuatu'],
    correct: 0,
    id: 'TL',
    index: 224,
    name: 'Đông Timor',
    uri: require('../../assets/flagpng/tl.png'),
  },
  {
    answer: ['Turkmenistan', 'Hàn Quốc', 'Đảo Síp', 'Tajikistan'],
    correct: 0,
    id: 'TM',
    index: 225,
    name: 'Turkmenistan',
    uri: require('../../assets/flagpng/tm.png'),
  },
  {
    answer: ['Romania', 'Georgia', 'Tunisia', 'Hàn Quốc'],
    correct: 2,
    id: 'TN',
    index: 226,
    name: 'Tunisia',
    uri: require('../../assets/flagpng/tn.png'),
  },
  {
    answer: ['Hungary', 'Tonga', 'Paraguay', 'Argentina'],
    correct: 1,
    id: 'TO',
    index: 227,
    name: 'Tonga',
    uri: require('../../assets/flagpng/to.png'),
  },
  {
    answer: ['Thổ Nhĩ Kỳ', 'Liberia', 'Peru', 'Ethiopia'],
    correct: 0,
    id: 'TR',
    index: 228,
    name: 'Thổ Nhĩ Kỳ',
    uri: require('../../assets/flagpng/tr.png'),
  },
  {
    answer: [
      'Cộng hòa Trung Phi',
      'Slovenia',
      'Trinidad và Tobago',
      'North Macedonia',
    ],
    correct: 2,
    id: 'TT',
    index: 229,
    name: 'Trinidad và Tobago',
    uri: require('../../assets/flagpng/tt.png'),
  },
  {
    answer: ['Ukraine', 'Tuvalu', 'Iceland', 'Áo'],
    correct: 1,
    id: 'TV',
    index: 230,
    name: 'Tuvalu',
    uri: require('../../assets/flagpng/tv.png'),
  },
  {
    answer: ['Campuchia', 'Tunisia', 'Antigua và Barbuda', 'Tanzania'],
    correct: 3,
    id: 'TZ',
    index: 232,
    name: 'Tanzania',
    uri: require('../../assets/flagpng/tz.png'),
  },
  {
    answer: ['Lithuania', 'Antigua và Barbuda', 'Ukraine', 'Nam Phi'],
    correct: 2,
    id: 'UA',
    index: 233,
    name: 'Ukraine',
    uri: require('../../assets/flagpng/ua.png'),
  },
  {
    answer: ['Uganda', 'Nauru', 'Belize', 'Libya'],
    correct: 0,
    id: 'UG',
    index: 234,
    name: 'Uganda',
    uri: require('../../assets/flagpng/ug.png'),
  },
  {
    answer: ['Maldives', 'San Marino', 'Cộng hòa Trung Phi', 'Mỹ (Hoa Kỳ)'],
    correct: 3,
    id: 'US',
    index: 235,
    name: 'Mỹ (Hoa Kỳ)',
    uri: require('../../assets/flagpng/us.png'),
  },
  {
    answer: ['Thổ Nhĩ Kỳ', 'Maldives', 'Uruguay', 'Tây Ban Nha'],
    correct: 2,
    id: 'UY',
    index: 236,
    name: 'Uruguay',
    uri: require('../../assets/flagpng/uy.png'),
  },
  {
    answer: ['Uzbekistan', 'Ma-rốc', 'Sierra Leone', 'Bulgaria'],
    correct: 0,
    id: 'UZ',
    index: 237,
    name: 'Uzbekistan',
    uri: require('../../assets/flagpng/uz.png'),
  },
  {
    answer: ['Grenada', 'Zambia', 'Ma-rốc', 'Saint Vincent và Grenadines'],
    correct: 3,
    id: 'VC',
    index: 239,
    name: 'Saint Vincent và Grenadines',
    uri: require('../../assets/flagpng/vc.png'),
  },
  {
    answer: ['Saint Vincent và Grenadines', 'Andorra', 'Na Uy', 'Venezuela'],
    correct: 3,
    id: 'VE',
    index: 240,
    name: 'Venezuela',
    uri: require('../../assets/flagpng/ve.png'),
  },
  {
    answer: ['Việt Nam', 'Na Uy', 'Rwanda', 'Benin'],
    correct: 0,
    id: 'VN',
    index: 243,
    name: 'Việt Nam',
    uri: require('../../assets/flagpng/vn.png'),
  },
  {
    answer: ['Vanuatu', 'Phần Lan', 'Uganda', 'Lào'],
    correct: 0,
    id: 'VU',
    index: 244,
    name: 'Vanuatu',
    uri: require('../../assets/flagpng/vu.png'),
  },
  {
    answer: ['Samoa', 'Sierra Leone', 'Bờ Biển Ngà', 'Hàn Quốc'],
    correct: 0,
    id: 'WS',
    index: 246,
    name: 'Samoa',
    uri: require('../../assets/flagpng/ws.png'),
  },
  {
    answer: ['Gambia', 'Yemen', 'Uruguay', 'Libya'],
    correct: 1,
    id: 'YE',
    index: 248,
    name: 'Yemen',
    uri: require('../../assets/flagpng/ye.png'),
  },
  {
    answer: ['Iran', 'Nam Phi', 'Úc', 'San Marino'],
    correct: 1,
    id: 'ZA',
    index: 250,
    name: 'Nam Phi',
    uri: require('../../assets/flagpng/za.png'),
  },
  {
    answer: ['Algeria', 'Zambia', 'El Salvador', 'Nigeria'],
    correct: 1,
    id: 'ZM',
    index: 251,
    name: 'Zambia',
    uri: require('../../assets/flagpng/zm.png'),
  },
  {
    answer: ['Maldives', 'South Sudan', 'Egypt', 'Zimbabwe'],
    correct: 3,
    id: 'ZW',
    index: 252,
    name: 'Zimbabwe',
    uri: require('../../assets/flagpng/zw.png'),
  },
];

export const DATA195: Country[] = [
  {
    id: 'AD',
    name: 'Andorra',
    uri: require('../../assets/flagpng/ad.png'),
    answer: [
      'Barbados',
      'Syrian Arab Republic',
      'Korea, Republic of',
      'Andorra',
    ],
    correct: 3,
    index: 0,
  },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    uri: require('../../assets/flagpng/ae.png'),
    answer: ['United Arab Emirates', 'Niger', 'Algeria', 'Switzerland'],
    correct: 0,
    index: 1,
  },
  {
    id: 'AF',
    name: 'Afghanistan',
    uri: require('../../assets/flagpng/af.png'),
    answer: ['Italy', 'Afghanistan', 'Yemen', 'Estonia'],
    correct: 1,
    index: 2,
  },
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    uri: require('../../assets/flagpng/ag.png'),
    answer: ['Djibouti', 'Panama', 'Antigua and Barbuda', 'Latvia'],
    correct: 2,
    index: 3,
  },
  {
    id: 'AL',
    name: 'Albania',
    uri: require('../../assets/flagpng/al.png'),
    answer: ['Belarus', 'United Arab Emirates', 'Albania', 'Luxembourg'],
    correct: 2,
    index: 4,
  },
  {
    id: 'AM',
    name: 'Armenia',
    uri: require('../../assets/flagpng/am.png'),
    answer: ['Angola', 'Senegal', 'North Macedonia', 'Armenia'],
    correct: 3,
    index: 5,
  },
  {
    id: 'AO',
    name: 'Angola',
    uri: require('../../assets/flagpng/ao.png'),
    answer: ['Angola', 'Tuvalu', 'Austria', 'Moldova, Republic of'],
    correct: 0,
    index: 6,
  },
  {
    id: 'AR',
    name: 'Argentina',
    uri: require('../../assets/flagpng/ar.png'),
    answer: ['Argentina', 'Kuwait', 'Austria', 'Saint Kitts and Nevis'],
    correct: 0,
    index: 7,
  },
  {
    id: 'AT',
    name: 'Austria',
    uri: require('../../assets/flagpng/at.png'),
    answer: ['Tunisia', 'Austria', 'Nigeria', 'Costa Rica'],
    correct: 1,
    index: 8,
  },
  {
    id: 'AU',
    name: 'Australia',
    uri: require('../../assets/flagpng/au.png'),
    answer: ['Australia', 'Cameroon', 'Oman', 'Sri Lanka'],
    correct: 0,
    index: 9,
  },
  {
    id: 'AZ',
    name: 'Azerbaijan',
    uri: require('../../assets/flagpng/az.png'),
    answer: ['Cyprus', 'Slovakia', 'Azerbaijan', 'Libya'],
    correct: 2,
    index: 10,
  },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    uri: require('../../assets/flagpng/ba.png'),
    answer: ['Luxembourg', 'Bosnia and Herzegovina', 'Canada', 'Zimbabwe'],
    correct: 1,
    index: 11,
  },
  {
    id: 'BB',
    name: 'Barbados',
    uri: require('../../assets/flagpng/bb.png'),
    answer: [
      'Barbados',
      'Nicaragua',
      'Denmark',
      'Saint Vincent and the Grenadines',
    ],
    correct: 0,
    index: 12,
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    uri: require('../../assets/flagpng/bd.png'),
    answer: [
      'Denmark',
      'Bangladesh',
      "Lao People's Democratic Republic",
      'United Kingdom of Great Britain and Northern Ireland',
    ],
    correct: 1,
    index: 13,
  },
  {
    id: 'BE',
    name: 'Belgium',
    uri: require('../../assets/flagpng/be.png'),
    answer: [
      'South Sudan',
      "Korea (Democratic People's Republic of)",
      'Belgium',
      'Cameroon',
    ],
    correct: 2,
    index: 14,
  },
  {
    id: 'BF',
    name: 'Burkina Faso',
    uri: require('../../assets/flagpng/bf.png'),
    answer: ['Iceland', 'Burkina Faso', 'Cameroon', 'South Africa'],
    correct: 1,
    index: 15,
  },
  {
    id: 'BG',
    name: 'Bulgaria',
    uri: require('../../assets/flagpng/bg.png'),
    answer: [
      'Chile',
      'South Africa',
      'Bulgaria',
      "Korea (Democratic People's Republic of)",
    ],
    correct: 2,
    index: 16,
  },
  {
    id: 'BH',
    name: 'Bahrain',
    uri: require('../../assets/flagpng/bh.png'),
    answer: ['Somalia', 'Gambia', 'Libya', 'Bahrain'],
    correct: 3,
    index: 17,
  },
  {
    id: 'BI',
    name: 'Burundi',
    uri: require('../../assets/flagpng/bi.png'),
    answer: ['Burundi', 'Djibouti', 'United States of America', 'Lesotho'],
    correct: 0,
    index: 18,
  },
  {
    id: 'BJ',
    name: 'Benin',
    uri: require('../../assets/flagpng/bj.png'),
    answer: ['Angola', 'Mexico', 'Serbia', 'Benin'],
    correct: 3,
    index: 19,
  },
  {
    id: 'BN',
    name: 'Brunei Darussalam',
    uri: require('../../assets/flagpng/bn.png'),
    answer: [
      'United States of America',
      'Egypt',
      'Brunei Darussalam',
      'New Zealand',
    ],
    correct: 2,
    index: 20,
  },
  {
    id: 'BO',
    name: 'Bolivia (Plurinational State of)',
    uri: require('../../assets/flagpng/bo.png'),
    answer: [
      'Timor-Leste',
      'Nepal',
      'Bolivia (Plurinational State of)',
      'Belize',
    ],
    correct: 2,
    index: 21,
  },
  {
    id: 'BR',
    name: 'Brazil',
    uri: require('../../assets/flagpng/br.png'),
    answer: ['Mali', 'Brazil', 'Vanuatu', 'Burundi'],
    correct: 1,
    index: 22,
  },
  {
    id: 'BS',
    name: 'Bahamas',
    uri: require('../../assets/flagpng/bs.png'),
    answer: ['Pakistan', 'Nicaragua', 'Georgia', 'Bahamas'],
    correct: 3,
    index: 23,
  },
  {
    id: 'BT',
    name: 'Bhutan',
    uri: require('../../assets/flagpng/bt.png'),
    answer: ['Bhutan', 'Rwanda', 'Jordan', 'Belgium'],
    correct: 0,
    index: 24,
  },
  {
    id: 'BW',
    name: 'Botswana',
    uri: require('../../assets/flagpng/bw.png'),
    answer: ['Lesotho', 'Botswana', 'Tajikistan', 'Brazil'],
    correct: 1,
    index: 25,
  },
  {
    id: 'BY',
    name: 'Belarus',
    uri: require('../../assets/flagpng/by.png'),
    answer: ['Botswana', 'Tajikistan', 'Lebanon', 'Belarus'],
    correct: 3,
    index: 26,
  },
  {
    id: 'BZ',
    name: 'Belize',
    uri: require('../../assets/flagpng/bz.png'),
    answer: ['Iraq', 'Germany', 'Somalia', 'Belize'],
    correct: 3,
    index: 27,
  },
  {
    id: 'CA',
    name: 'Canada',
    uri: require('../../assets/flagpng/ca.png'),
    answer: ['Poland', 'Canada', 'Guatemala', 'Croatia'],
    correct: 1,
    index: 28,
  },
  {
    id: 'CD',
    name: 'Congo, Democratic Republic of the',
    uri: require('../../assets/flagpng/cd.png'),
    answer: [
      'Bahrain',
      'Congo, Democratic Republic of the',
      'Lesotho',
      'Russian Federation',
    ],
    correct: 1,
    index: 29,
  },
  {
    id: 'CF',
    name: 'Central African Republic',
    uri: require('../../assets/flagpng/cf.png'),
    answer: [
      'Costa Rica',
      'Guatemala',
      'United Kingdom of Great Britain and Northern Ireland',
      'Central African Republic',
    ],
    correct: 3,
    index: 30,
  },
  {
    id: 'CG',
    name: 'Congo',
    uri: require('../../assets/flagpng/cg.png'),
    answer: [
      'Mongolia',
      'Brunei Darussalam',
      'Venezuela (Bolivarian Republic of)',
      'Congo',
    ],
    correct: 3,
    index: 31,
  },
  {
    id: 'CH',
    name: 'Switzerland',
    uri: require('../../assets/flagpng/ch.png'),
    answer: ['Switzerland', 'Belarus', 'Mali', 'Trinidad and Tobago'],
    correct: 0,
    index: 32,
  },
  {
    id: 'CI',
    name: "Côte d'Ivoire",
    uri: require('../../assets/flagpng/ci.png'),
    answer: ['Viet Nam', "Côte d'Ivoire", 'Israel', 'Burundi'],
    correct: 1,
    index: 33,
  },
  {
    id: 'CL',
    name: 'Chile',
    uri: require('../../assets/flagpng/cl.png'),
    answer: ['Cyprus', 'Chile', 'Spain', 'Kyrgyzstan'],
    correct: 1,
    index: 34,
  },
  {
    id: 'CM',
    name: 'Cameroon',
    uri: require('../../assets/flagpng/cm.png'),
    answer: ['Canada', 'Cameroon', 'Serbia', 'Greece'],
    correct: 1,
    index: 35,
  },
  {
    id: 'CN',
    name: 'China',
    uri: require('../../assets/flagpng/cn.png'),
    answer: ['Viet Nam', 'Gabon', 'Grenada', 'China'],
    correct: 3,
    index: 36,
  },
  {
    id: 'CO',
    name: 'Colombia',
    uri: require('../../assets/flagpng/co.png'),
    answer: [
      'Zimbabwe',
      'Colombia',
      'Dominican Republic',
      'Korea, Republic of',
    ],
    correct: 1,
    index: 37,
  },
  {
    id: 'CR',
    name: 'Costa Rica',
    uri: require('../../assets/flagpng/cr.png'),
    answer: ['Costa Rica', 'Uruguay', 'Liberia', 'Argentina'],
    correct: 0,
    index: 38,
  },
  {
    id: 'CU',
    name: 'Cuba',
    uri: require('../../assets/flagpng/cu.png'),
    answer: ['Tonga', 'Cuba', 'Guinea-Bissau', 'Brazil'],
    correct: 1,
    index: 39,
  },
  {
    id: 'CV',
    name: 'Cabo Verde',
    uri: require('../../assets/flagpng/cv.png'),
    answer: ['Dominica', 'Sweden', 'Kazakhstan', 'Cabo Verde'],
    correct: 3,
    index: 40,
  },
  {
    id: 'CY',
    name: 'Cyprus',
    uri: require('../../assets/flagpng/cy.png'),
    answer: [
      'Myanmar',
      'Cyprus',
      'Venezuela (Bolivarian Republic of)',
      'Gabon',
    ],
    correct: 1,
    index: 41,
  },
  {
    id: 'CZ',
    name: 'Czechia',
    uri: require('../../assets/flagpng/cz.png'),
    answer: ['Serbia', 'Czechia', 'Finland', 'Niger'],
    correct: 1,
    index: 42,
  },
  {
    id: 'DE',
    name: 'Germany',
    uri: require('../../assets/flagpng/de.png'),
    answer: ['Germany', 'Portugal', 'Comoros', 'Ireland'],
    correct: 0,
    index: 43,
  },
  {
    id: 'DJ',
    name: 'Djibouti',
    uri: require('../../assets/flagpng/dj.png'),
    answer: ['Botswana', 'Japan', 'Djibouti', 'Türkiye'],
    correct: 2,
    index: 44,
  },
  {
    id: 'DK',
    name: 'Denmark',
    uri: require('../../assets/flagpng/dk.png'),
    answer: [
      'New Zealand',
      'El Salvador',
      'Denmark',
      'United States of America',
    ],
    correct: 2,
    index: 45,
  },
  {
    id: 'DM',
    name: 'Dominica',
    uri: require('../../assets/flagpng/dm.png'),
    answer: ['Mongolia', 'Georgia', 'Turkmenistan', 'Dominica'],
    correct: 3,
    index: 46,
  },
  {
    id: 'DO',
    name: 'Dominican Republic',
    uri: require('../../assets/flagpng/do.png'),
    answer: ['Benin', 'Pakistan', 'Dominican Republic', 'Luxembourg'],
    correct: 2,
    index: 47,
  },
  {
    id: 'DZ',
    name: 'Algeria',
    uri: require('../../assets/flagpng/dz.png'),
    answer: [
      'Venezuela (Bolivarian Republic of)',
      'Lebanon',
      'Algeria',
      'Cyprus',
    ],
    correct: 2,
    index: 48,
  },
  {
    id: 'EC',
    name: 'Ecuador',
    uri: require('../../assets/flagpng/ec.png'),
    answer: ['Haiti', 'Brunei Darussalam', 'South Sudan', 'Ecuador'],
    correct: 3,
    index: 49,
  },
  {
    id: 'EE',
    name: 'Estonia',
    uri: require('../../assets/flagpng/ee.png'),
    answer: ['Costa Rica', 'Estonia', 'Sri Lanka', 'Liberia'],
    correct: 1,
    index: 50,
  },
  {
    id: 'EG',
    name: 'Egypt',
    uri: require('../../assets/flagpng/eg.png'),
    answer: ['Egypt', 'Armenia', 'Korea, Republic of', 'Tonga'],
    correct: 0,
    index: 51,
  },
  {
    id: 'ER',
    name: 'Eritrea',
    uri: require('../../assets/flagpng/er.png'),
    answer: ['Niger', 'Tonga', 'Germany', 'Eritrea'],
    correct: 3,
    index: 52,
  },
  {
    id: 'ES',
    name: 'Spain',
    uri: require('../../assets/flagpng/es.png'),
    answer: ['El Salvador', 'Spain', 'Sri Lanka', 'Japan'],
    correct: 1,
    index: 53,
  },
  {
    id: 'ET',
    name: 'Ethiopia',
    uri: require('../../assets/flagpng/et.png'),
    answer: ['Malaysia', 'El Salvador', 'Ethiopia', 'Portugal'],
    correct: 2,
    index: 54,
  },
  {
    id: 'FI',
    name: 'Finland',
    uri: require('../../assets/flagpng/fi.png'),
    answer: ['Equatorial Guinea', 'Luxembourg', 'Timor-Leste', 'Finland'],
    correct: 3,
    index: 55,
  },
  {
    id: 'FJ',
    name: 'Fiji',
    uri: require('../../assets/flagpng/fj.png'),
    answer: ['Kiribati', 'Syrian Arab Republic', 'Fiji', 'Equatorial Guinea'],
    correct: 2,
    index: 56,
  },
  {
    id: 'FM',
    name: 'Micronesia (Federated States of)',
    uri: require('../../assets/flagpng/fm.png'),
    answer: [
      'Micronesia (Federated States of)',
      'Russian Federation',
      'Jordan',
      'Estonia',
    ],
    correct: 0,
    index: 57,
  },
  {
    id: 'FR',
    name: 'France',
    uri: require('../../assets/flagpng/fr.png'),
    answer: ['Romania', 'Latvia', 'Cabo Verde', 'France'],
    correct: 3,
    index: 58,
  },
  {
    id: 'GA',
    name: 'Gabon',
    uri: require('../../assets/flagpng/ga.png'),
    answer: ['Gabon', 'Singapore', 'Angola', 'Honduras'],
    correct: 0,
    index: 59,
  },
  {
    id: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    uri: require('../../assets/flagpng/gb.png'),
    answer: [
      'Niger',
      'Antigua and Barbuda',
      'Uruguay',
      'United Kingdom of Great Britain and Northern Ireland',
    ],
    correct: 3,
    index: 60,
  },
  {
    id: 'GD',
    name: 'Grenada',
    uri: require('../../assets/flagpng/gd.png'),
    answer: ['Colombia', 'Grenada', 'Peru', 'Guinea-Bissau'],
    correct: 1,
    index: 61,
  },
  {
    id: 'GE',
    name: 'Georgia',
    uri: require('../../assets/flagpng/ge.png'),
    answer: ['Qatar', 'Andorra', 'Jordan', 'Georgia'],
    correct: 3,
    index: 62,
  },
  {
    id: 'GH',
    name: 'Ghana',
    uri: require('../../assets/flagpng/gh.png'),
    answer: ['Ghana', 'Sierra Leone', "Côte d'Ivoire", 'Luxembourg'],
    correct: 0,
    index: 63,
  },
  {
    id: 'GM',
    name: 'Gambia',
    uri: require('../../assets/flagpng/gm.png'),
    answer: ['North Macedonia', 'Portugal', 'Gambia', 'Dominica'],
    correct: 2,
    index: 64,
  },
  {
    id: 'GN',
    name: 'Guinea',
    uri: require('../../assets/flagpng/gn.png'),
    answer: ['Iran (Islamic Republic of)', 'Guinea', 'Gabon', 'Qatar'],
    correct: 1,
    index: 65,
  },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    uri: require('../../assets/flagpng/gq.png'),
    answer: [
      'Antigua and Barbuda',
      'Uzbekistan',
      'Marshall Islands',
      'Equatorial Guinea',
    ],
    correct: 3,
    index: 66,
  },
  {
    id: 'GR',
    name: 'Greece',
    uri: require('../../assets/flagpng/gr.png'),
    answer: ['Bulgaria', 'South Sudan', 'Greece', 'Lithuania'],
    correct: 2,
    index: 67,
  },
  {
    id: 'GT',
    name: 'Guatemala',
    uri: require('../../assets/flagpng/gt.png'),
    answer: ['Barbados', 'Guatemala', 'Spain', 'Lithuania'],
    correct: 1,
    index: 68,
  },
  {
    id: 'GW',
    name: 'Guinea-Bissau',
    uri: require('../../assets/flagpng/gw.png'),
    answer: ['Togo', 'Guinea-Bissau', 'Indonesia', 'Brunei Darussalam'],
    correct: 1,
    index: 69,
  },
  {
    id: 'GY',
    name: 'Guyana',
    uri: require('../../assets/flagpng/gy.png'),
    answer: ['Guyana', 'Nepal', 'Suriname', 'Afghanistan'],
    correct: 0,
    index: 70,
  },
  {
    id: 'HN',
    name: 'Honduras',
    uri: require('../../assets/flagpng/hn.png'),
    answer: ["Côte d'Ivoire", 'Romania', 'Honduras', 'Japan'],
    correct: 2,
    index: 71,
  },
  {
    id: 'HR',
    name: 'Croatia',
    uri: require('../../assets/flagpng/hr.png'),
    answer: ['Croatia', 'Indonesia', 'Philippines', 'Andorra'],
    correct: 0,
    index: 72,
  },
  {
    id: 'HT',
    name: 'Haiti',
    uri: require('../../assets/flagpng/ht.png'),
    answer: ['China', 'Serbia', 'Mexico', 'Haiti'],
    correct: 3,
    index: 73,
  },
  {
    id: 'HU',
    name: 'Hungary',
    uri: require('../../assets/flagpng/hu.png'),
    answer: ['Netherlands', 'Zambia', 'Colombia', 'Hungary'],
    correct: 3,
    index: 74,
  },
  {
    id: 'ID',
    name: 'Indonesia',
    uri: require('../../assets/flagpng/id.png'),
    answer: ['Jamaica', 'Benin', 'Togo', 'Indonesia'],
    correct: 3,
    index: 75,
  },
  {
    id: 'IE',
    name: 'Ireland',
    uri: require('../../assets/flagpng/ie.png'),
    answer: [
      'Saint Vincent and the Grenadines',
      'Ireland',
      'Congo, Democratic Republic of the',
      'Mexico',
    ],
    correct: 1,
    index: 76,
  },
  {
    id: 'IL',
    name: 'Israel',
    uri: require('../../assets/flagpng/il.png'),
    answer: ['Israel', 'Nauru', 'Seychelles', 'Eswatini'],
    correct: 0,
    index: 77,
  },
  {
    id: 'IN',
    name: 'India',
    uri: require('../../assets/flagpng/in.png'),
    answer: ['India', 'Russian Federation', 'Mongolia', 'Bulgaria'],
    correct: 0,
    index: 78,
  },
  {
    id: 'IQ',
    name: 'Iraq',
    uri: require('../../assets/flagpng/iq.png'),
    answer: ['Iraq', 'El Salvador', 'Palau', 'Mozambique'],
    correct: 0,
    index: 79,
  },
  {
    id: 'IR',
    name: 'Iran (Islamic Republic of)',
    uri: require('../../assets/flagpng/ir.png'),
    answer: [
      'Saint Vincent and the Grenadines',
      'France',
      "Korea (Democratic People's Republic of)",
      'Iran (Islamic Republic of)',
    ],
    correct: 3,
    index: 80,
  },
  {
    id: 'IS',
    name: 'Iceland',
    uri: require('../../assets/flagpng/is.png'),
    answer: ['Uruguay', 'Hungary', 'Iceland', 'Bahrain'],
    correct: 2,
    index: 81,
  },
  {
    id: 'IT',
    name: 'Italy',
    uri: require('../../assets/flagpng/it.png'),
    answer: ['Oman', 'Italy', 'Sweden', 'Andorra'],
    correct: 1,
    index: 82,
  },
  {
    id: 'JM',
    name: 'Jamaica',
    uri: require('../../assets/flagpng/jm.png'),
    answer: [
      'Venezuela (Bolivarian Republic of)',
      'Jamaica',
      'Maldives',
      'Andorra',
    ],
    correct: 1,
    index: 83,
  },
  {
    id: 'JO',
    name: 'Jordan',
    uri: require('../../assets/flagpng/jo.png'),
    answer: [
      'Jordan',
      'Bolivia (Plurinational State of)',
      'Greece',
      'Russian Federation',
    ],
    correct: 0,
    index: 84,
  },
  {
    id: 'JP',
    name: 'Japan',
    uri: require('../../assets/flagpng/jp.png'),
    answer: ['San Marino', 'Japan', 'Mauritania', 'Bhutan'],
    correct: 1,
    index: 85,
  },
  {
    id: 'KE',
    name: 'Kenya',
    uri: require('../../assets/flagpng/ke.png'),
    answer: [
      'Djibouti',
      'Tanzania, United Republic of',
      'Moldova, Republic of',
      'Kenya',
    ],
    correct: 3,
    index: 86,
  },
  {
    id: 'KG',
    name: 'Kyrgyzstan',
    uri: require('../../assets/flagpng/kg.png'),
    answer: ['Italy', 'Kyrgyzstan', 'Switzerland', 'Cameroon'],
    correct: 1,
    index: 87,
  },
  {
    id: 'KH',
    name: 'Cambodia',
    uri: require('../../assets/flagpng/kh.png'),
    answer: ['Cambodia', 'Netherlands', 'Yemen', 'Gambia'],
    correct: 0,
    index: 88,
  },
  {
    id: 'KI',
    name: 'Kiribati',
    uri: require('../../assets/flagpng/ki.png'),
    answer: ['Cabo Verde', 'Kiribati', 'Norway', 'Poland'],
    correct: 1,
    index: 89,
  },
  {
    id: 'KM',
    name: 'Comoros',
    uri: require('../../assets/flagpng/km.png'),
    answer: ['Guyana', 'Comoros', 'Zimbabwe', 'Barbados'],
    correct: 1,
    index: 90,
  },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    uri: require('../../assets/flagpng/kn.png'),
    answer: ['Costa Rica', 'Japan', 'Serbia', 'Saint Kitts and Nevis'],
    correct: 3,
    index: 91,
  },
  {
    id: 'KP',
    name: "Korea (Democratic People's Republic of)",
    uri: require('../../assets/flagpng/kp.png'),
    answer: [
      'Norway',
      "Korea (Democratic People's Republic of)",
      'Tonga',
      'Czechia',
    ],
    correct: 1,
    index: 92,
  },
  {
    id: 'KR',
    name: 'Korea, Republic of',
    uri: require('../../assets/flagpng/kr.png'),
    answer: ['Tuvalu', 'Myanmar', 'Korea, Republic of', 'Barbados'],
    correct: 2,
    index: 93,
  },
  {
    id: 'KW',
    name: 'Kuwait',
    uri: require('../../assets/flagpng/kw.png'),
    answer: ['Kuwait', 'Liberia', 'South Africa', 'China'],
    correct: 0,
    index: 94,
  },
  {
    id: 'KZ',
    name: 'Kazakhstan',
    uri: require('../../assets/flagpng/kz.png'),
    answer: ['Kazakhstan', 'Bhutan', 'Ghana', 'Yemen'],
    correct: 0,
    index: 95,
  },
  {
    id: 'LA',
    name: "Lao People's Democratic Republic",
    uri: require('../../assets/flagpng/la.png'),
    answer: [
      "Lao People's Democratic Republic",
      'Brazil',
      'Latvia',
      'Trinidad and Tobago',
    ],
    correct: 0,
    index: 96,
  },
  {
    id: 'LB',
    name: 'Lebanon',
    uri: require('../../assets/flagpng/lb.png'),
    answer: ['Switzerland', 'Morocco', 'Gabon', 'Lebanon'],
    correct: 3,
    index: 97,
  },
  {
    id: 'LC',
    name: 'Saint Lucia',
    uri: require('../../assets/flagpng/lc.png'),
    answer: ['Madagascar', 'Saint Lucia', 'Bosnia and Herzegovina', 'Tunisia'],
    correct: 1,
    index: 98,
  },
  {
    id: 'LI',
    name: 'Liechtenstein',
    uri: require('../../assets/flagpng/li.png'),
    answer: ['North Macedonia', 'Georgia', 'Liechtenstein', 'Sri Lanka'],
    correct: 2,
    index: 99,
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    uri: require('../../assets/flagpng/lk.png'),
    answer: ['Belgium', 'Mongolia', 'Sao Tome and Principe', 'Sri Lanka'],
    correct: 3,
    index: 100,
  },
  {
    id: 'LR',
    name: 'Liberia',
    uri: require('../../assets/flagpng/lr.png'),
    answer: ['Tonga', 'Liberia', 'Comoros', 'Grenada'],
    correct: 1,
    index: 101,
  },
  {
    id: 'LS',
    name: 'Lesotho',
    uri: require('../../assets/flagpng/ls.png'),
    answer: ['Indonesia', 'Zambia', 'Lesotho', 'Eritrea'],
    correct: 2,
    index: 102,
  },
  {
    id: 'LT',
    name: 'Lithuania',
    uri: require('../../assets/flagpng/lt.png'),
    answer: [
      'Iran (Islamic Republic of)',
      'South Africa',
      'Lithuania',
      'Germany',
    ],
    correct: 2,
    index: 103,
  },
  {
    id: 'LU',
    name: 'Luxembourg',
    uri: require('../../assets/flagpng/lu.png'),
    answer: [
      'Luxembourg',
      'Micronesia (Federated States of)',
      'Solomon Islands',
      'Cabo Verde',
    ],
    correct: 0,
    index: 104,
  },
  {
    id: 'LV',
    name: 'Latvia',
    uri: require('../../assets/flagpng/lv.png'),
    answer: ['Malaysia', 'Botswana', 'Latvia', 'Russian Federation'],
    correct: 2,
    index: 105,
  },
  {
    id: 'LY',
    name: 'Libya',
    uri: require('../../assets/flagpng/ly.png'),
    answer: ['Samoa', 'Libya', 'Burundi', 'Korea, Republic of'],
    correct: 1,
    index: 106,
  },
  {
    id: 'MA',
    name: 'Morocco',
    uri: require('../../assets/flagpng/ma.png'),
    answer: ['Morocco', 'Iceland', 'Comoros', 'Saint Kitts and Nevis'],
    correct: 0,
    index: 107,
  },
  {
    id: 'MC',
    name: 'Monaco',
    uri: require('../../assets/flagpng/mc.png'),
    answer: ['Monaco', 'Central African Republic', 'Tunisia', 'Oman'],
    correct: 0,
    index: 108,
  },
  {
    id: 'MD',
    name: 'Moldova, Republic of',
    uri: require('../../assets/flagpng/md.png'),
    answer: ['Cambodia', 'Rwanda', 'Luxembourg', 'Moldova, Republic of'],
    correct: 3,
    index: 109,
  },
  {
    id: 'ME',
    name: 'Montenegro',
    uri: require('../../assets/flagpng/me.png'),
    answer: ['Guyana', 'China', 'Zambia', 'Montenegro'],
    correct: 3,
    index: 110,
  },
  {
    id: 'MG',
    name: 'Madagascar',
    uri: require('../../assets/flagpng/mg.png'),
    answer: ['Turkmenistan', 'Madagascar', 'Malawi', 'Bulgaria'],
    correct: 1,
    index: 111,
  },
  {
    id: 'MH',
    name: 'Marshall Islands',
    uri: require('../../assets/flagpng/mh.png'),
    answer: ['Bahrain', 'Norway', 'Qatar', 'Marshall Islands'],
    correct: 3,
    index: 112,
  },
  {
    id: 'MK',
    name: 'North Macedonia',
    uri: require('../../assets/flagpng/mk.png'),
    answer: [
      'El Salvador',
      'Micronesia (Federated States of)',
      'Ukraine',
      'North Macedonia',
    ],
    correct: 3,
    index: 113,
  },
  {
    id: 'ML',
    name: 'Mali',
    uri: require('../../assets/flagpng/ml.png'),
    answer: ['United Arab Emirates', 'Bangladesh', 'Mali', 'New Zealand'],
    correct: 2,
    index: 114,
  },
  {
    id: 'MM',
    name: 'Myanmar',
    uri: require('../../assets/flagpng/mm.png'),
    answer: [
      "Korea (Democratic People's Republic of)",
      'Cyprus',
      'Myanmar',
      'Zimbabwe',
    ],
    correct: 2,
    index: 115,
  },
  {
    id: 'MN',
    name: 'Mongolia',
    uri: require('../../assets/flagpng/mn.png'),
    answer: [
      'Zambia',
      'Mongolia',
      "Korea (Democratic People's Republic of)",
      'Bolivia (Plurinational State of)',
    ],
    correct: 1,
    index: 116,
  },
  {
    id: 'MR',
    name: 'Mauritania',
    uri: require('../../assets/flagpng/mr.png'),
    answer: ['Mauritania', 'Panama', 'Dominica', 'Korea, Republic of'],
    correct: 0,
    index: 117,
  },
  {
    id: 'MT',
    name: 'Malta',
    uri: require('../../assets/flagpng/mt.png'),
    answer: [
      'Saint Vincent and the Grenadines',
      'Kyrgyzstan',
      'Malta',
      'Brunei Darussalam',
    ],
    correct: 2,
    index: 118,
  },
  {
    id: 'MU',
    name: 'Mauritius',
    uri: require('../../assets/flagpng/mu.png'),
    answer: ['Mauritius', 'Tajikistan', 'Montenegro', 'Australia'],
    correct: 0,
    index: 119,
  },
  {
    id: 'MV',
    name: 'Maldives',
    uri: require('../../assets/flagpng/mv.png'),
    answer: ['Italy', 'Turkmenistan', 'Maldives', 'Croatia'],
    correct: 2,
    index: 120,
  },
  {
    id: 'MW',
    name: 'Malawi',
    uri: require('../../assets/flagpng/mw.png'),
    answer: ['Zimbabwe', 'Malawi', 'Jordan', 'Cuba'],
    correct: 1,
    index: 121,
  },
  {
    id: 'MX',
    name: 'Mexico',
    uri: require('../../assets/flagpng/mx.png'),
    answer: ['Mexico', 'Suriname', 'Congo', 'Hungary'],
    correct: 0,
    index: 122,
  },
  {
    id: 'MY',
    name: 'Malaysia',
    uri: require('../../assets/flagpng/my.png'),
    answer: [
      'Saudi Arabia',
      'Kazakhstan',
      'Bolivia (Plurinational State of)',
      'Malaysia',
    ],
    correct: 3,
    index: 123,
  },
  {
    id: 'MZ',
    name: 'Mozambique',
    uri: require('../../assets/flagpng/mz.png'),
    answer: [
      'Saint Vincent and the Grenadines',
      'Morocco',
      'Mozambique',
      'Chile',
    ],
    correct: 2,
    index: 124,
  },
  {
    id: 'NA',
    name: 'Namibia',
    uri: require('../../assets/flagpng/na.png'),
    answer: ['Namibia', 'Singapore', 'Palau', 'Comoros'],
    correct: 0,
    index: 125,
  },
  {
    id: 'NE',
    name: 'Niger',
    uri: require('../../assets/flagpng/ne.png'),
    answer: ['Niger', 'Guatemala', 'Palau', 'Botswana'],
    correct: 0,
    index: 126,
  },
  {
    id: 'NG',
    name: 'Nigeria',
    uri: require('../../assets/flagpng/ng.png'),
    answer: ['Switzerland', 'Nigeria', 'Estonia', 'Moldova, Republic of'],
    correct: 1,
    index: 127,
  },
  {
    id: 'NI',
    name: 'Nicaragua',
    uri: require('../../assets/flagpng/ni.png'),
    answer: ['Albania', 'Liberia', 'Nicaragua', 'Sweden'],
    correct: 2,
    index: 128,
  },
  {
    id: 'NL',
    name: 'Netherlands',
    uri: require('../../assets/flagpng/nl.png'),
    answer: ['Netherlands', 'Mongolia', 'Panama', 'Colombia'],
    correct: 0,
    index: 129,
  },
  {
    id: 'NO',
    name: 'Norway',
    uri: require('../../assets/flagpng/no.png'),
    answer: ['Norway', 'Vanuatu', 'Denmark', 'Morocco'],
    correct: 0,
    index: 130,
  },
  {
    id: 'NP',
    name: 'Nepal',
    uri: require('../../assets/flagpng/np.png'),
    answer: ['Zimbabwe', 'Kiribati', "Côte d'Ivoire", 'Nepal'],
    correct: 3,
    index: 131,
  },
  {
    id: 'NR',
    name: 'Nauru',
    uri: require('../../assets/flagpng/nr.png'),
    answer: ['Nauru', 'Albania', 'Trinidad and Tobago', 'Japan'],
    correct: 0,
    index: 132,
  },
  {
    id: 'NZ',
    name: 'New Zealand',
    uri: require('../../assets/flagpng/nz.png'),
    answer: ['Montenegro', 'New Zealand', 'Cambodia', 'Togo'],
    correct: 1,
    index: 133,
  },
  {
    id: 'OM',
    name: 'Oman',
    uri: require('../../assets/flagpng/om.png'),
    answer: ['Oman', 'Croatia', 'Israel', 'Philippines'],
    correct: 0,
    index: 134,
  },
  {
    id: 'PA',
    name: 'Panama',
    uri: require('../../assets/flagpng/pa.png'),
    answer: ['Türkiye', 'Dominican Republic', 'Italy', 'Panama'],
    correct: 3,
    index: 135,
  },
  {
    id: 'PE',
    name: 'Peru',
    uri: require('../../assets/flagpng/pe.png'),
    answer: ['Peru', 'Eritrea', 'Ghana', 'Saudi Arabia'],
    correct: 0,
    index: 136,
  },
  {
    id: 'PG',
    name: 'Papua New Guinea',
    uri: require('../../assets/flagpng/pg.png'),
    answer: ['Slovenia', 'Jamaica', 'Papua New Guinea', 'Belarus'],
    correct: 2,
    index: 137,
  },
  {
    id: 'PH',
    name: 'Philippines',
    uri: require('../../assets/flagpng/ph.png'),
    answer: ['Cambodia', 'Kyrgyzstan', 'Samoa', 'Philippines'],
    correct: 3,
    index: 138,
  },
  {
    id: 'PK',
    name: 'Pakistan',
    uri: require('../../assets/flagpng/pk.png'),
    answer: ['Madagascar', 'Pakistan', 'Equatorial Guinea', 'Sweden'],
    correct: 1,
    index: 139,
  },
  {
    id: 'PL',
    name: 'Poland',
    uri: require('../../assets/flagpng/pl.png'),
    answer: ['Brazil', 'Nauru', 'Poland', 'Tuvalu'],
    correct: 2,
    index: 140,
  },
  {
    id: 'PT',
    name: 'Portugal',
    uri: require('../../assets/flagpng/pt.png'),
    answer: ['Israel', 'Zambia', 'Portugal', 'Georgia'],
    correct: 2,
    index: 141,
  },
  {
    id: 'PW',
    name: 'Palau',
    uri: require('../../assets/flagpng/pw.png'),
    answer: ['Equatorial Guinea', 'Zambia', 'Palau', 'Honduras'],
    correct: 2,
    index: 142,
  },
  {
    id: 'PY',
    name: 'Paraguay',
    uri: require('../../assets/flagpng/py.png'),
    answer: ['Iceland', 'Belize', 'Paraguay', 'Serbia'],
    correct: 2,
    index: 143,
  },
  {
    id: 'QA',
    name: 'Qatar',
    uri: require('../../assets/flagpng/qa.png'),
    answer: [
      'Eswatini',
      'Honduras',
      'United Kingdom of Great Britain and Northern Ireland',
      'Qatar',
    ],
    correct: 3,
    index: 144,
  },
  {
    id: 'RO',
    name: 'Romania',
    uri: require('../../assets/flagpng/ro.png'),
    answer: [
      'Saint Kitts and Nevis',
      'Romania',
      'Malta',
      'Antigua and Barbuda',
    ],
    correct: 1,
    index: 145,
  },
  {
    id: 'RS',
    name: 'Serbia',
    uri: require('../../assets/flagpng/rs.png'),
    answer: ['Maldives', 'Ukraine', 'Serbia', 'Burundi'],
    correct: 2,
    index: 146,
  },
  {
    id: 'RU',
    name: 'Russian Federation',
    uri: require('../../assets/flagpng/ru.png'),
    answer: ['Oman', 'Tonga', 'Albania', 'Russian Federation'],
    correct: 3,
    index: 147,
  },
  {
    id: 'RW',
    name: 'Rwanda',
    uri: require('../../assets/flagpng/rw.png'),
    answer: ['Togo', 'Estonia', 'Rwanda', 'Norway'],
    correct: 2,
    index: 148,
  },
  {
    id: 'SA',
    name: 'Saudi Arabia',
    uri: require('../../assets/flagpng/sa.png'),
    answer: ['Spain', 'Benin', 'Saudi Arabia', 'Guinea-Bissau'],
    correct: 2,
    index: 149,
  },
  {
    id: 'SB',
    name: 'Solomon Islands',
    uri: require('../../assets/flagpng/sb.png'),
    answer: ['Zimbabwe', 'Congo', 'Malta', 'Solomon Islands'],
    correct: 3,
    index: 150,
  },
  {
    id: 'SC',
    name: 'Seychelles',
    uri: require('../../assets/flagpng/sc.png'),
    answer: ['Sierra Leone', 'Seychelles', 'Afghanistan', 'Nigeria'],
    correct: 1,
    index: 151,
  },
  {
    id: 'SD',
    name: 'Sudan',
    uri: require('../../assets/flagpng/sd.png'),
    answer: ['Sudan', 'Myanmar', 'Tonga', 'Brunei Darussalam'],
    correct: 0,
    index: 152,
  },
  {
    id: 'SE',
    name: 'Sweden',
    uri: require('../../assets/flagpng/se.png'),
    answer: ['Sweden', 'Ukraine', 'Monaco', 'Bahamas'],
    correct: 0,
    index: 153,
  },
  {
    id: 'SG',
    name: 'Singapore',
    uri: require('../../assets/flagpng/sg.png'),
    answer: ['Singapore', 'Qatar', 'Egypt', 'Iceland'],
    correct: 0,
    index: 154,
  },
  {
    id: 'SI',
    name: 'Slovenia',
    uri: require('../../assets/flagpng/si.png'),
    answer: ['Spain', 'Cuba', 'Slovenia', 'Luxembourg'],
    correct: 2,
    index: 155,
  },
  {
    id: 'SK',
    name: 'Slovakia',
    uri: require('../../assets/flagpng/sk.png'),
    answer: ['Slovakia', 'Croatia', 'South Sudan', 'Maldives'],
    correct: 0,
    index: 156,
  },
  {
    id: 'SL',
    name: 'Sierra Leone',
    uri: require('../../assets/flagpng/sl.png'),
    answer: ['Greece', 'Rwanda', 'Belize', 'Sierra Leone'],
    correct: 3,
    index: 157,
  },
  {
    id: 'SM',
    name: 'San Marino',
    uri: require('../../assets/flagpng/sm.png'),
    answer: ['Morocco', 'San Marino', 'Philippines', 'Cyprus'],
    correct: 1,
    index: 158,
  },
  {
    id: 'SN',
    name: 'Senegal',
    uri: require('../../assets/flagpng/sn.png'),
    answer: ['Latvia', 'Chile', 'Senegal', 'Panama'],
    correct: 2,
    index: 159,
  },
  {
    id: 'SO',
    name: 'Somalia',
    uri: require('../../assets/flagpng/so.png'),
    answer: ['Trinidad and Tobago', 'Somalia', 'Jamaica', 'Germany'],
    correct: 1,
    index: 160,
  },
  {
    id: 'SR',
    name: 'Suriname',
    uri: require('../../assets/flagpng/sr.png'),
    answer: ['Tuvalu', 'Bangladesh', 'Hungary', 'Suriname'],
    correct: 3,
    index: 161,
  },
  {
    id: 'SS',
    name: 'South Sudan',
    uri: require('../../assets/flagpng/ss.png'),
    answer: ['Pakistan', 'South Sudan', 'Mauritania', 'Bosnia and Herzegovina'],
    correct: 1,
    index: 162,
  },
  {
    id: 'ST',
    name: 'Sao Tome and Principe',
    uri: require('../../assets/flagpng/st.png'),
    answer: [
      'Slovenia',
      'Afghanistan',
      'Sao Tome and Principe',
      'Iran (Islamic Republic of)',
    ],
    correct: 2,
    index: 163,
  },
  {
    id: 'SV',
    name: 'El Salvador',
    uri: require('../../assets/flagpng/sv.png'),
    answer: ['Tunisia', 'Eritrea', 'El Salvador', 'Iceland'],
    correct: 2,
    index: 164,
  },
  {
    id: 'SY',
    name: 'Syrian Arab Republic',
    uri: require('../../assets/flagpng/sy.png'),
    answer: [
      'Indonesia',
      'Syrian Arab Republic',
      'Burkina Faso',
      'Switzerland',
    ],
    correct: 1,
    index: 165,
  },
  {
    id: 'SZ',
    name: 'Eswatini',
    uri: require('../../assets/flagpng/sz.png'),
    answer: [
      'Djibouti',
      'Eswatini',
      'Zimbabwe',
      "Lao People's Democratic Republic",
    ],
    correct: 1,
    index: 166,
  },
  {
    id: 'TD',
    name: 'Chad',
    uri: require('../../assets/flagpng/td.png'),
    answer: ['Singapore', 'Chad', 'Argentina', 'Netherlands'],
    correct: 1,
    index: 167,
  },
  {
    id: 'TG',
    name: 'Togo',
    uri: require('../../assets/flagpng/tg.png'),
    answer: ['Sierra Leone', 'Estonia', 'Lithuania', 'Togo'],
    correct: 3,
    index: 168,
  },
  {
    id: 'TH',
    name: 'Thailand',
    uri: require('../../assets/flagpng/th.png'),
    answer: ['Ghana', 'Russian Federation', 'Gabon', 'Thailand'],
    correct: 3,
    index: 169,
  },
  {
    id: 'TJ',
    name: 'Tajikistan',
    uri: require('../../assets/flagpng/tj.png'),
    answer: [
      'Tajikistan',
      'Poland',
      "Côte d'Ivoire",
      "Korea (Democratic People's Republic of)",
    ],
    correct: 0,
    index: 170,
  },
  {
    id: 'TL',
    name: 'Timor-Leste',
    uri: require('../../assets/flagpng/tl.png'),
    answer: ['Timor-Leste', 'Spain', 'Malawi', 'Congo'],
    correct: 0,
    index: 171,
  },
  {
    id: 'TM',
    name: 'Turkmenistan',
    uri: require('../../assets/flagpng/tm.png'),
    answer: ['Turkmenistan', 'Fiji', 'Philippines', 'Kuwait'],
    correct: 0,
    index: 172,
  },
  {
    id: 'TN',
    name: 'Tunisia',
    uri: require('../../assets/flagpng/tn.png'),
    answer: ['Iceland', 'Slovenia', 'Estonia', 'Tunisia'],
    correct: 3,
    index: 173,
  },
  {
    id: 'TO',
    name: 'Tonga',
    uri: require('../../assets/flagpng/to.png'),
    answer: ['Afghanistan', 'Singapore', 'Malaysia', 'Tonga'],
    correct: 3,
    index: 174,
  },
  {
    id: 'TR',
    name: 'Türkiye',
    uri: require('../../assets/flagpng/tr.png'),
    answer: ['Honduras', 'Brazil', 'Tajikistan', 'Türkiye'],
    correct: 3,
    index: 175,
  },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    uri: require('../../assets/flagpng/tt.png'),
    answer: ['Ukraine', 'Monaco', 'Trinidad and Tobago', 'Bulgaria'],
    correct: 2,
    index: 176,
  },
  {
    id: 'TV',
    name: 'Tuvalu',
    uri: require('../../assets/flagpng/tv.png'),
    answer: ['Tuvalu', 'Congo', 'United Arab Emirates', 'Mauritania'],
    correct: 0,
    index: 177,
  },
  {
    id: 'TZ',
    name: 'Tanzania, United Republic of',
    uri: require('../../assets/flagpng/tz.png'),
    answer: ['Iraq', 'Barbados', 'Slovakia', 'Tanzania, United Republic of'],
    correct: 3,
    index: 178,
  },
  {
    id: 'UA',
    name: 'Ukraine',
    uri: require('../../assets/flagpng/ua.png'),
    answer: ['Japan', 'United Arab Emirates', 'Bhutan', 'Ukraine'],
    correct: 3,
    index: 179,
  },
  {
    id: 'UG',
    name: 'Uganda',
    uri: require('../../assets/flagpng/ug.png'),
    answer: ['Senegal', 'Argentina', 'Uganda', 'Korea, Republic of'],
    correct: 2,
    index: 180,
  },
  {
    id: 'US',
    name: 'United States of America',
    uri: require('../../assets/flagpng/us.png'),
    answer: ['Niger', 'Tunisia', 'Ethiopia', 'United States of America'],
    correct: 3,
    index: 181,
  },
  {
    id: 'UY',
    name: 'Uruguay',
    uri: require('../../assets/flagpng/uy.png'),
    answer: ['Kazakhstan', 'Afghanistan', 'Sierra Leone', 'Uruguay'],
    correct: 3,
    index: 182,
  },
  {
    id: 'UZ',
    name: 'Uzbekistan',
    uri: require('../../assets/flagpng/uz.png'),
    answer: ['Monaco', 'Senegal', 'Bahamas', 'Uzbekistan'],
    correct: 3,
    index: 183,
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    uri: require('../../assets/flagpng/vc.png'),
    answer: [
      'Togo',
      'Honduras',
      'Saint Vincent and the Grenadines',
      'Botswana',
    ],
    correct: 2,
    index: 184,
  },
  {
    id: 'VE',
    name: 'Venezuela (Bolivarian Republic of)',
    uri: require('../../assets/flagpng/ve.png'),
    answer: [
      'Kazakhstan',
      'Chad',
      'Venezuela (Bolivarian Republic of)',
      'South Africa',
    ],
    correct: 2,
    index: 185,
  },
  {
    id: 'VN',
    name: 'Viet Nam',
    uri: require('../../assets/flagpng/vn.png'),
    answer: ['Libya', 'Cyprus', 'Tunisia', 'Viet Nam'],
    correct: 3,
    index: 186,
  },
  {
    id: 'VU',
    name: 'Vanuatu',
    uri: require('../../assets/flagpng/vu.png'),
    answer: ['Vanuatu', 'Cyprus', 'Peru', 'Liechtenstein'],
    correct: 0,
    index: 187,
  },
  {
    id: 'WS',
    name: 'Samoa',
    uri: require('../../assets/flagpng/ws.png'),
    answer: ['Malawi', 'Egypt', 'Samoa', 'Sudan'],
    correct: 2,
    index: 188,
  },
  {
    id: 'YE',
    name: 'Yemen',
    uri: require('../../assets/flagpng/ye.png'),
    answer: ['Belize', 'Slovenia', 'Maldives', 'Yemen'],
    correct: 3,
    index: 189,
  },
  {
    id: 'ZA',
    name: 'South Africa',
    uri: require('../../assets/flagpng/za.png'),
    answer: ['Yemen', 'Cameroon', 'Oman', 'South Africa'],
    correct: 3,
    index: 190,
  },
  {
    id: 'ZM',
    name: 'Zambia',
    uri: require('../../assets/flagpng/zm.png'),
    answer: ['Mexico', 'Zambia', 'Denmark', 'Rwanda'],
    correct: 1,
    index: 191,
  },
  {
    id: 'ZW',
    name: 'Zimbabwe',
    uri: require('../../assets/flagpng/zw.png'),
    answer: ['Central African Republic', 'Zimbabwe', 'Timor-Leste', 'Iraq'],
    correct: 1,
    index: 192,
  },
];
