import {Country} from '../../model/Country';

export const DATAEUVI: Country[] = [
  {
    answer: ['Andorra', 'Bosnia và Herzegovina', 'Malta', 'Hungary'],
    correct: 0,
    id: 'AD',
    index: 0,
    name: 'Andorra',
    uri: require('../../assets/flagpng/ad.png'),
  },
  {
    answer: ['Portugal', 'Đảo Síp', 'Isle of Man', 'Albania'],
    correct: 3,
    id: 'AL',
    index: 5,
    name: 'Albania',
    uri: require('../../assets/flagpng/al.png'),
  },
  {
    answer: ['Bulgaria', 'Áo', 'Slovakia', 'Vương quốc Anh'],
    correct: 1,
    id: 'AT',
    index: 11,
    name: 'Áo',
    uri: require('../../assets/flagpng/at.png'),
  },
  // {
  //   answer: ['Thụy Sỹ', 'Åland Islands', 'Lithuania', 'Ukraine'],
  //   correct: 1,
  //   id: 'AX',
  //   index: 14,
  //   name: 'Åland Islands',
  //   uri: require('../../assets/flagpng/ax.png'),
  // },
  {
    answer: ['Bosnia và Herzegovina', 'Slovakia', 'Iceland', 'Bỉ'],
    correct: 0,
    id: 'BA',
    index: 16,
    name: 'Bosnia và Herzegovina',
    uri: require('../../assets/flagpng/ba.png'),
  },
  {
    answer: ['Kosovo', 'Bỉ', 'Belarus', 'Ireland'],
    correct: 1,
    id: 'BE',
    index: 19,
    name: 'Bỉ',
    uri: require('../../assets/flagpng/be.png'),
  },
  {
    answer: ['Bulgaria', 'Đảo Síp', 'Jersey', 'Portugal'],
    correct: 0,
    id: 'BG',
    index: 21,
    name: 'Bulgaria',
    uri: require('../../assets/flagpng/bg.png'),
  },
  {
    answer: ['Belarus', 'Montenegro', 'Ba Lan', 'Thụy Sỹ'],
    correct: 0,
    id: 'BY',
    index: 34,
    name: 'Belarus',
    uri: require('../../assets/flagpng/by.png'),
  },
  {
    answer: ['Belarus', 'Na Uy', 'Italy', 'Thụy Sỹ'],
    correct: 3,
    id: 'CH',
    index: 41,
    name: 'Thụy Sỹ',
    uri: require('../../assets/flagpng/ch.png'),
  },
  {
    answer: ['Tây Ban Nha', 'San Marino', 'Đảo Síp', 'Croatia'],
    correct: 2,
    id: 'CY',
    index: 53,
    name: 'Đảo Síp',
    uri: require('../../assets/flagpng/cy.png'),
  },
  {
    answer: ['Áo', 'Séc', 'Liechtenstein', 'Slovakia'],
    correct: 1,
    id: 'CZ',
    index: 54,
    name: 'Séc',
    uri: require('../../assets/flagpng/cz.png'),
  },
  {
    answer: ['Thành Vatican', 'Đức', 'Belarus', 'Guernsey'],
    correct: 1,
    id: 'DE',
    index: 55,
    name: 'Đức',
    uri: require('../../assets/flagpng/de.png'),
  },
  {
    answer: ['Denmark', 'Na Uy', 'Åland Islands', 'Gibraltar'],
    correct: 0,
    id: 'DK',
    index: 57,
    name: 'Denmark',
    uri: require('../../assets/flagpng/dk.png'),
  },
  {
    answer: [
      'Quần đảo Svalbard và Jan Mayen',
      'Estonia',
      'Phần Lan',
      'Lithuania',
    ],
    correct: 1,
    id: 'EE',
    index: 62,
    name: 'Estonia',
    uri: require('../../assets/flagpng/ee.png'),
  },
  {
    answer: ['Đảo Síp', 'San Marino', 'Monaco', 'Tây Ban Nha'],
    correct: 3,
    id: 'ES',
    index: 66,
    name: 'Tây Ban Nha',
    uri: require('../../assets/flagpng/es.png'),
  },
  {
    answer: ['Belarus', 'Phần Lan', 'Malta', 'Ireland'],
    correct: 1,
    id: 'FI',
    index: 69,
    name: 'Phần Lan',
    uri: require('../../assets/flagpng/fi.png'),
  },
  // {
  //   answer: ['Tây Ban Nha', 'San Marino', 'Jersey', 'Quần đảo Faroe'],
  //   correct: 3,
  //   id: 'FO',
  //   index: 73,
  //   name: 'Quần đảo Faroe',
  //   uri: require('../../assets/flagpng/fo.png'),
  // },
  {
    answer: ['Estonia', 'Kosovo', 'Pháp', 'Jersey'],
    correct: 2,
    id: 'FR',
    index: 74,
    name: 'Pháp',
    uri: require('../../assets/flagpng/fr.png'),
  },
  {
    answer: ['Malta', 'Montenegro', 'Bỉ', 'Vương quốc Anh'],
    correct: 3,
    id: 'GB',
    index: 80,
    name: 'Vương quốc Anh',
    uri: require('../../assets/flagpng/gb.png'),
  },
  // {
  //   answer: ['Moldova', 'Quần đảo Svalbard và Jan Mayen', 'Guernsey', 'Đức'],
  //   correct: 2,
  //   id: 'GG',
  //   index: 84,
  //   name: 'Guernsey',
  //   uri: require('../../assets/flagpng/gg.png'),
  // },
  // {
  //   answer: ['Áo', 'Gibraltar', 'Italy', 'Romania'],
  //   correct: 1,
  //   id: 'GI',
  //   index: 86,
  //   name: 'Gibraltar',
  //   uri: require('../../assets/flagpng/gi.png'),
  // },
  {
    answer: ['Đảo Síp', 'Montenegro', 'Hy Lạp', 'Portugal'],
    correct: 2,
    id: 'GR',
    index: 92,
    name: 'Hy Lạp',
    uri: require('../../assets/flagpng/gr.png'),
  },
  {
    answer: ['Phần Lan', 'Croatia', 'Guernsey', 'Na Uy'],
    correct: 1,
    id: 'HR',
    index: 101,
    name: 'Croatia',
    uri: require('../../assets/flagpng/hr.png'),
  },
  {
    answer: ['Hungary', 'Hungary', 'Andorra', 'Quần đảo Svalbard và Jan Mayen'],
    correct: 1,
    id: 'HU',
    index: 103,
    name: 'Hungary',
    uri: require('../../assets/flagpng/hu.png'),
  },
  {
    answer: ['Ireland', 'Serbia', 'Phần Lan', 'Lithuania'],
    correct: 0,
    id: 'IE',
    index: 105,
    name: 'Ireland',
    uri: require('../../assets/flagpng/ie.png'),
  },
  // {
  //   answer: ['Kosovo', 'Luxembourg', 'Isle of Man', 'Bulgaria'],
  //   correct: 2,
  //   id: 'IM',
  //   index: 107,
  //   name: 'Isle of Man',
  //   uri: require('../../assets/flagpng/im.png'),
  // },
  {
    answer: ['Iceland', 'Iceland', 'Hà Lan', 'Bỉ'],
    correct: 1,
    id: 'IS',
    index: 112,
    name: 'Iceland',
    uri: require('../../assets/flagpng/is.png'),
  },
  {
    answer: ['Andorra', 'Italy', 'Kosovo', 'Monaco'],
    correct: 1,
    id: 'IT',
    index: 113,
    name: 'Italy',
    uri: require('../../assets/flagpng/it.png'),
  },
  // {
  //   answer: ['Luxembourg', 'Jersey', 'Thụy Điển', 'Åland Islands'],
  //   correct: 1,
  //   id: 'JE',
  //   index: 114,
  //   name: 'Jersey',
  //   uri: require('../../assets/flagpng/je.png'),
  // },
  {
    answer: ['Bỉ', 'Kosovo', 'Croatia', 'Liechtenstein'],
    correct: 3,
    id: 'LI',
    index: 132,
    name: 'Liechtenstein',
    uri: require('../../assets/flagpng/li.png'),
  },
  {
    answer: ['Jersey', 'Bulgaria', 'Ba Lan', 'Lithuania'],
    correct: 3,
    id: 'LT',
    index: 136,
    name: 'Lithuania',
    uri: require('../../assets/flagpng/lt.png'),
  },
  {
    answer: ['Ukraine', 'Monaco', 'Luxembourg', 'Denmark'],
    correct: 2,
    id: 'LU',
    index: 137,
    name: 'Luxembourg',
    uri: require('../../assets/flagpng/lu.png'),
  },
  {
    answer: ['Séc', 'Kosovo', 'Latvia', 'Latvia'],
    correct: 3,
    id: 'LV',
    index: 138,
    name: 'Latvia',
    uri: require('../../assets/flagpng/lv.png'),
  },
  {
    answer: [
      'Monaco',
      'Quần đảo Svalbard và Jan Mayen',
      'Vương quốc Anh',
      'Đảo Síp',
    ],
    correct: 0,
    id: 'MC',
    index: 141,
    name: 'Monaco',
    uri: require('../../assets/flagpng/mc.png'),
  },
  {
    answer: ['Hy Lạp', 'Quần đảo Faroe', 'Thụy Điển', 'Moldova'],
    correct: 3,
    id: 'MD',
    index: 142,
    name: 'Moldova',
    uri: require('../../assets/flagpng/md.png'),
  },
  {
    answer: ['Montenegro', 'Phần Lan', 'Gibraltar', 'Slovakia'],
    correct: 0,
    id: 'ME',
    index: 143,
    name: 'Montenegro',
    uri: require('../../assets/flagpng/me.png'),
  },
  {
    answer: ['Áo', 'North Macedonia', 'Vương quốc Anh', 'Slovenia'],
    correct: 1,
    id: 'MK',
    index: 147,
    name: 'North Macedonia',
    uri: require('../../assets/flagpng/mk.png'),
  },
  {
    answer: [
      'North Macedonia',
      'Quần đảo Svalbard và Jan Mayen',
      'Séc',
      'Malta',
    ],
    correct: 3,
    id: 'MT',
    index: 156,
    name: 'Malta',
    uri: require('../../assets/flagpng/mt.png'),
  },
  {
    answer: [
      'Tây Ban Nha',
      'Hà Lan',
      'Quần đảo Svalbard và Jan Mayen',
      'Jersey',
    ],
    correct: 1,
    id: 'NL',
    index: 169,
    name: 'Hà Lan',
    uri: require('../../assets/flagpng/nl.png'),
  },
  {
    answer: ['Portugal', 'Hy Lạp', 'Na Uy', 'Đảo Síp'],
    correct: 2,
    id: 'NO',
    index: 170,
    name: 'Na Uy',
    uri: require('../../assets/flagpng/no.png'),
  },
  {
    answer: ['Ba Lan', 'Áo', 'Thành Vatican', 'Moldova'],
    correct: 0,
    id: 'PL',
    index: 182,
    name: 'Ba Lan',
    uri: require('../../assets/flagpng/pl.png'),
  },
  {
    answer: ['Isle of Man', 'Pháp', 'Portugal', 'Thụy Điển'],
    correct: 2,
    id: 'PT',
    index: 187,
    name: 'Portugal',
    uri: require('../../assets/flagpng/pt.png'),
  },
  {
    answer: ['Thụy Sỹ', 'Malta', 'Latvia', 'Romania'],
    correct: 3,
    id: 'RO',
    index: 192,
    name: 'Romania',
    uri: require('../../assets/flagpng/ro.png'),
  },
  {
    answer: ['Liechtenstein', 'Serbia', 'Thụy Sỹ', 'Kosovo'],
    correct: 1,
    id: 'RS',
    index: 193,
    name: 'Serbia',
    uri: require('../../assets/flagpng/rs.png'),
  },
  {
    answer: ['Portugal', 'Thụy Điển', 'Thụy Sỹ', 'North Macedonia'],
    correct: 1,
    id: 'SE',
    index: 200,
    name: 'Thụy Điển',
    uri: require('../../assets/flagpng/se.png'),
  },
  {
    answer: ['San Marino', 'Slovenia', 'Séc', 'Latvia'],
    correct: 1,
    id: 'SI',
    index: 203,
    name: 'Slovenia',
    uri: require('../../assets/flagpng/si.png'),
  },
  // {
  //   answer: [
  //     'Quần đảo Svalbard và Jan Mayen',
  //     'Ireland',
  //     'Bulgaria',
  //     'Thụy Điển',
  //   ],
  //   correct: 0,
  //   id: 'SJ',
  //   index: 204,
  //   name: 'Quần đảo Svalbard và Jan Mayen',
  //   uri: require('../../assets/flagpng/sj.png'),
  // },
  {
    answer: ['Jersey', 'Hà Lan', 'Slovakia', 'Andorra'],
    correct: 2,
    id: 'SK',
    index: 205,
    name: 'Slovakia',
    uri: require('../../assets/flagpng/sk.png'),
  },
  {
    answer: ['Liechtenstein', 'Pháp', 'Ukraine', 'San Marino'],
    correct: 3,
    id: 'SM',
    index: 207,
    name: 'San Marino',
    uri: require('../../assets/flagpng/sm.png'),
  },
  {
    answer: ['Albania', 'Kosovo', 'Ukraine', 'Lithuania'],
    correct: 2,
    id: 'UA',
    index: 233,
    name: 'Ukraine',
    uri: require('../../assets/flagpng/ua.png'),
  },
  {
    answer: ['Ukraine', 'Åland Islands', 'Thành Vatican', 'Iceland'],
    correct: 2,
    id: 'VA',
    index: 238,
    name: 'Thành Vatican',
    uri: require('../../assets/flagpng/va.png'),
  },
  // {
  //   answer: ['Bỉ', 'Thành Vatican', 'Kosovo', 'Ireland'],
  //   correct: 2,
  //   id: 'XK',
  //   index: 247,
  //   name: 'Kosovo',
  //   uri: require('../../assets/flagpng/xk.png'),
  // },
];

export const DATAEU: Country[] = [
  {
    answer: ['Lithuania', 'Romania', 'Albania', 'Bosnia and Herzegovina'],
    correct: 2,
    id: 'AL',
    index: 1,
    name: 'Albania',
    uri: require('../../assets/flagpng/al.png'),
  },
  {
    answer: ['San Marino', 'Denmark', 'Andorra', 'Hungary'],
    correct: 2,
    id: 'AD',
    index: 3,
    name: 'Andorra',
    uri: require('../../assets/flagpng/ad.png'),
  },
  {
    answer: ['Austria', 'Liechtenstein', 'Bulgaria', 'Slovakia'],
    correct: 0,
    id: 'AT',
    index: 9,
    name: 'Austria',
    uri: require('../../assets/flagpng/at.png'),
  },
  {
    answer: ['Serbia', 'Italy', 'Belarus', 'Belarus'],
    correct: 3,
    id: 'BY',
    index: 15,
    name: 'Belarus',
    uri: require('../../assets/flagpng/by.png'),
  },
  {
    answer: ['Norway', 'Czechia', 'Belgium', 'Slovakia'],
    correct: 2,
    id: 'BE',
    index: 16,
    name: 'Belgium',
    uri: require('../../assets/flagpng/be.png'),
  },
  {
    answer: ['Bosnia and Herzegovina', 'Sweden', 'Belarus', 'Luxembourg'],
    correct: 0,
    id: 'BA',
    index: 21,
    name: 'Bosnia and Herzegovina',
    uri: require('../../assets/flagpng/ba.png'),
  },
  {
    answer: ['Latvia', 'Bulgaria', 'Serbia', 'Andorra'],
    correct: 1,
    id: 'BG',
    index: 25,
    name: 'Bulgaria',
    uri: require('../../assets/flagpng/bg.png'),
  },
  {
    answer: ['Latvia', 'Croatia', 'Cyprus', 'Sweden'],
    correct: 1,
    id: 'HR',
    index: 42,
    name: 'Croatia',
    uri: require('../../assets/flagpng/hr.png'),
  },
  {
    answer: ['Austria', 'Cyprus', 'Slovenia', 'Italy'],
    correct: 1,
    id: 'CY',
    index: 44,
    name: 'Cyprus',
    uri: require('../../assets/flagpng/cy.png'),
  },
  {
    answer: ['Italy', 'Belarus', 'Romania', 'Czechia'],
    correct: 3,
    id: 'CZ',
    index: 45,
    name: 'Czechia',
    uri: require('../../assets/flagpng/cz.png'),
  },
  {
    answer: ['Switzerland', 'Italy', 'Croatia', 'Denmark'],
    correct: 3,
    id: 'DK',
    index: 46,
    name: 'Denmark',
    uri: require('../../assets/flagpng/dk.png'),
  },
  {
    answer: ['Andorra', 'Estonia', 'Slovenia', 'Luxembourg'],
    correct: 1,
    id: 'EE',
    index: 55,
    name: 'Estonia',
    uri: require('../../assets/flagpng/ee.png'),
  },
  {
    answer: ['San Marino', 'Finland', 'Norway', 'Estonia'],
    correct: 1,
    id: 'FI',
    index: 59,
    name: 'Finland',
    uri: require('../../assets/flagpng/fi.png'),
  },
  {
    answer: ['Andorra', 'Monaco', 'France', 'Sweden'],
    correct: 2,
    id: 'FR',
    index: 60,
    name: 'France',
    uri: require('../../assets/flagpng/fr.png'),
  },
  {
    answer: ['Iceland', 'Cyprus', 'Ukraine', 'Germany'],
    correct: 3,
    id: 'DE',
    index: 64,
    name: 'Germany',
    uri: require('../../assets/flagpng/de.png'),
  },
  {
    answer: ['Greece', 'Finland', 'Lithuania', 'Slovakia'],
    correct: 0,
    id: 'GR',
    index: 66,
    name: 'Greece',
    uri: require('../../assets/flagpng/gr.png'),
  },
  {
    answer: ['Hungary', 'Italy', 'Poland', 'France'],
    correct: 0,
    id: 'HU',
    index: 74,
    name: 'Hungary',
    uri: require('../../assets/flagpng/hu.png'),
  },
  {
    answer: [
      'Denmark',
      'Hungary',
      'United Kingdom of Great Britain and Northern Ireland',
      'Iceland',
    ],
    correct: 3,
    id: 'IS',
    index: 75,
    name: 'Iceland',
    uri: require('../../assets/flagpng/is.png'),
  },
  {
    answer: ['Germany', 'Ireland', 'Iceland', 'San Marino'],
    correct: 1,
    id: 'IE',
    index: 80,
    name: 'Ireland',
    uri: require('../../assets/flagpng/ie.png'),
  },
  {
    answer: ['Ireland', 'Italy', 'Austria', 'Sweden'],
    correct: 1,
    id: 'IT',
    index: 82,
    name: 'Italy',
    uri: require('../../assets/flagpng/it.png'),
  },
  {
    answer: ['Latvia', 'France', 'Portugal', 'Iceland'],
    correct: 0,
    id: 'LV',
    index: 94,
    name: 'Latvia',
    uri: require('../../assets/flagpng/lv.png'),
  },
  {
    answer: ['Bulgaria', 'Norway', 'Portugal', 'Liechtenstein'],
    correct: 3,
    id: 'LI',
    index: 99,
    name: 'Liechtenstein',
    uri: require('../../assets/flagpng/li.png'),
  },
  {
    answer: ['France', 'Lithuania', 'Italy', 'Sweden'],
    correct: 1,
    id: 'LT',
    index: 100,
    name: 'Lithuania',
    uri: require('../../assets/flagpng/lt.png'),
  },
  {
    answer: ['Ireland', 'Luxembourg', 'Sweden', 'Czechia'],
    correct: 1,
    id: 'LU',
    index: 101,
    name: 'Luxembourg',
    uri: require('../../assets/flagpng/lu.png'),
  },
  {
    answer: ['Malta', 'France', 'Malta', 'San Marino'],
    correct: 0,
    id: 'MT',
    index: 107,
    name: 'Malta',
    uri: require('../../assets/flagpng/mt.png'),
  },
  {
    answer: ['Lithuania', 'Poland', 'Moldova, Republic of', 'France'],
    correct: 2,
    id: 'MD',
    index: 113,
    name: 'Moldova, Republic of',
    uri: require('../../assets/flagpng/md.png'),
  },
  {
    answer: ['Monaco', 'Greece', 'Poland', 'Austria'],
    correct: 0,
    id: 'MC',
    index: 114,
    name: 'Monaco',
    uri: require('../../assets/flagpng/mc.png'),
  },
  {
    answer: ['Italy', 'Portugal', 'Montenegro', 'Belgium'],
    correct: 2,
    id: 'ME',
    index: 116,
    name: 'Montenegro',
    uri: require('../../assets/flagpng/me.png'),
  },
  {
    answer: ['Netherlands', 'Bulgaria', 'Moldova, Republic of', 'Ukraine'],
    correct: 0,
    id: 'NL',
    index: 123,
    name: 'Netherlands',
    uri: require('../../assets/flagpng/nl.png'),
  },
  {
    answer: ['Monaco', 'Spain', 'Bulgaria', 'North Macedonia'],
    correct: 3,
    id: 'MK',
    index: 128,
    name: 'North Macedonia',
    uri: require('../../assets/flagpng/mk.png'),
  },
  {
    answer: ['Norway', 'Slovakia', 'Moldova, Republic of', 'Belgium'],
    correct: 0,
    id: 'NO',
    index: 129,
    name: 'Norway',
    uri: require('../../assets/flagpng/no.png'),
  },
  {
    answer: ['Ireland', 'Poland', 'Denmark', 'San Marino'],
    correct: 1,
    id: 'PL',
    index: 138,
    name: 'Poland',
    uri: require('../../assets/flagpng/pl.png'),
  },
  {
    answer: ['Germany', 'Portugal', 'Moldova, Republic of', 'San Marino'],
    correct: 1,
    id: 'PT',
    index: 139,
    name: 'Portugal',
    uri: require('../../assets/flagpng/pt.png'),
  },
  {
    answer: ['Cyprus', 'Romania', 'Liechtenstein', 'Spain'],
    correct: 1,
    id: 'RO',
    index: 141,
    name: 'Romania',
    uri: require('../../assets/flagpng/ro.png'),
  },
  {
    answer: ['Malta', 'Germany', 'Spain', 'San Marino'],
    correct: 3,
    id: 'SM',
    index: 148,
    name: 'San Marino',
    uri: require('../../assets/flagpng/sm.png'),
  },
  {
    answer: ['Serbia', 'Bulgaria', 'Luxembourg', 'Slovakia'],
    correct: 0,
    id: 'RS',
    index: 152,
    name: 'Serbia',
    uri: require('../../assets/flagpng/rs.png'),
  },
  {
    answer: ['Slovakia', 'Greece', 'Andorra', 'Slovakia'],
    correct: 3,
    id: 'SK',
    index: 156,
    name: 'Slovakia',
    uri: require('../../assets/flagpng/sk.png'),
  },
  {
    answer: ['Albania', 'San Marino', 'Liechtenstein', 'Slovenia'],
    correct: 3,
    id: 'SI',
    index: 157,
    name: 'Slovenia',
    uri: require('../../assets/flagpng/si.png'),
  },
  {
    answer: ['Liechtenstein', 'Belarus', 'Spain', 'Romania'],
    correct: 2,
    id: 'ES',
    index: 162,
    name: 'Spain',
    uri: require('../../assets/flagpng/es.png'),
  },
  {
    answer: ['Romania', 'Norway', 'Sweden', 'France'],
    correct: 2,
    id: 'SE',
    index: 166,
    name: 'Sweden',
    uri: require('../../assets/flagpng/se.png'),
  },
  {
    answer: ['Estonia', 'Luxembourg', 'Sweden', 'Switzerland'],
    correct: 3,
    id: 'CH',
    index: 167,
    name: 'Switzerland',
    uri: require('../../assets/flagpng/ch.png'),
  },
  {
    answer: [
      'United Kingdom of Great Britain and Northern Ireland',
      'Latvia',
      'Ukraine',
      'Finland',
    ],
    correct: 2,
    id: 'UA',
    index: 181,
    name: 'Ukraine',
    uri: require('../../assets/flagpng/ua.png'),
  },
  {
    answer: [
      'Norway',
      'Czechia',
      'United Kingdom of Great Britain and Northern Ireland',
      'San Marino',
    ],
    correct: 2,
    id: 'GB',
    index: 183,
    name: 'United Kingdom of Great Britain and Northern Ireland',
    uri: require('../../assets/flagpng/gb.png'),
  },
  {
    answer: ['Ukraine', 'Åland Islands', 'Holy See (Vatican City)', 'Iceland'],
    correct: 2,
    id: 'VA',
    index: 238,
    name: 'Holy See (Vatican City)',
    uri: require('../../assets/flagpng/va.png'),
  },
];
