import {Dimensions} from 'react-native';
import Svgs from '../../constants/Svgs';
const widthDimensions = Dimensions.get('window').width;
export type country = {
  id: string;
  name: string;
  uri: any;
  answer: string[];
  correct: number;
};
export const DATA: country[] = [
  {
    id: 'AD',
    name: 'Andorra',
    uri: <Svgs.AD height={80} width={widthDimensions} />,
    answer: ['Belgium', 'New Caledonia', 'Andorra', 'Slovakia'],
    correct: 2,
  },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    uri: <Svgs.AE height={80} width={widthDimensions} />,
    answer: ['United States', 'Norway', 'Bangladesh', 'United Arab Emirates'],
    correct: 3,
  },
  {
    id: 'AF',
    name: 'Afghanistan',
    uri: <Svgs.AF height={80} width={widthDimensions} />,
    answer: ['Barbados', 'Gibraltar', 'Yemen', 'Afghanistan'],
    correct: 3,
  },
  {
    id: 'AG',
    name: 'Antigua and Barbuda',
    uri: <Svgs.AG height={80} width={widthDimensions} />,
    answer: ['Paraguay', 'Antigua and Barbuda', 'Germany', 'Saint Lucia'],
    correct: 1,
  },
  {
    id: 'AI',
    name: 'Anguilla',
    uri: <Svgs.AI height={80} width={widthDimensions} />,
    answer: ['Iceland', 'Tuvalu', 'Angola', 'Anguilla'],
    correct: 3,
  },
  {
    id: 'AL',
    name: 'Albania',
    uri: <Svgs.AL height={80} width={widthDimensions} />,
    answer: ['Albania', 'Uzbekistan', 'Bangladesh', 'Norway'],
    correct: 0,
  },
  {
    id: 'AM',
    name: 'Armenia',
    uri: <Svgs.AM height={80} width={widthDimensions} />,
    answer: ['Armenia', 'Bouvet Island', 'Netherlands', 'Tuvalu'],
    correct: 0,
  },
  {
    id: 'AO',
    name: 'Angola',
    uri: <Svgs.AO height={80} width={widthDimensions} />,
    answer: [
      'Poland',
      'American Samoa',
      'Angola',
      "Korea, Democratic People's Republic of",
    ],
    correct: 2,
  },
  {
    id: 'AQ',
    name: 'Antarctica',
    uri: <Svgs.AQ height={80} width={widthDimensions} />,
    answer: [
      'Antarctica',
      'Northern Mariana Islands',
      'Saudi Arabia',
      'Brazil',
    ],
    correct: 0,
  },
  {
    id: 'AR',
    name: 'Argentina',
    uri: <Svgs.AR height={80} width={widthDimensions} />,
    answer: [
      'Ecuador',
      'Holy See (Vatican City State)',
      'Argentina',
      'Guatemala',
    ],
    correct: 2,
  },
  {
    id: 'AS',
    name: 'American Samoa',
    uri: <Svgs.AS height={80} width={widthDimensions} />,
    answer: ['Bouvet Island', 'Madagascar', 'American Samoa', 'Timor-Leste'],
    correct: 2,
  },
  {
    id: 'AT',
    name: 'Austria',
    uri: <Svgs.AT height={80} width={widthDimensions} />,
    answer: ['Austria', 'Lesotho', 'Dominican Republic', 'Papua New Guinea'],
    correct: 0,
  },
  {
    id: 'AU',
    name: 'Australia',
    uri: <Svgs.AU height={80} width={widthDimensions} />,
    answer: ['Niger', 'Uganda', 'United Arab Emirates', 'Australia'],
    correct: 3,
  },
  {
    id: 'AW',
    name: 'Aruba',
    uri: <Svgs.AW height={80} width={widthDimensions} />,
    answer: ['Martinique', 'Aruba', 'Sint Maarten (Dutch part)', 'Scotland'],
    correct: 1,
  },
  {
    id: 'AX',
    name: 'Åland Islands',
    uri: <Svgs.AX height={80} width={widthDimensions} />,
    answer: ['Uzbekistan', 'Åland Islands', 'Greece', 'Fiji'],
    correct: 1,
  },
  {
    id: 'AZ',
    name: 'Azerbaijan',
    uri: <Svgs.AZ height={80} width={widthDimensions} />,
    answer: [
      'Scotland',
      'Svalbard and Jan Mayen Islands',
      'Azerbaijan',
      'Kyrgyzstan',
    ],
    correct: 2,
  },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    uri: <Svgs.BA height={80} width={widthDimensions} />,
    answer: [
      'Bosnia and Herzegovina',
      'Tanzania, United Republic of',
      'Costa Rica',
      'Morocco',
    ],
    correct: 0,
  },
  {
    id: 'BB',
    name: 'Barbados',
    uri: <Svgs.BB height={80} width={widthDimensions} />,
    answer: ['Barbados', 'Qatar', 'Azerbaijan', 'Guinea-Bissau'],
    correct: 0,
  },
  {
    id: 'BD',
    name: 'Bangladesh',
    uri: <Svgs.BD height={80} width={widthDimensions} />,
    answer: ['Gibraltar', 'Albania', 'Rwanda', 'Bangladesh'],
    correct: 3,
  },
  {
    id: 'BE',
    name: 'Belgium',
    uri: <Svgs.BE height={80} width={widthDimensions} />,
    answer: ['Belgium', 'Canada', 'Uganda', 'Saint Kitts and Nevis'],
    correct: 0,
  },
  {
    id: 'BF',
    name: 'Burkina Faso',
    uri: <Svgs.BF height={80} width={widthDimensions} />,
    answer: ['Indonesia', 'Benin', 'Burkina Faso', 'Kosovo'],
    correct: 2,
  },
  {
    id: 'BG',
    name: 'Bulgaria',
    uri: <Svgs.BG height={80} width={widthDimensions} />,
    answer: [
      'Guam',
      "China (People's Republic of China)",
      'Bulgaria',
      'Pitcairn',
    ],
    correct: 2,
  },
  {
    id: 'BH',
    name: 'Bahrain',
    uri: <Svgs.BH height={80} width={widthDimensions} />,
    answer: ['Bahrain', 'Malta', 'Virgin Islands, British', 'Finland'],
    correct: 0,
  },
  {
    id: 'BI',
    name: 'Burundi',
    uri: <Svgs.BI height={80} width={widthDimensions} />,
    answer: ['Mali', 'Burundi', 'Vanuatu', 'Belize'],
    correct: 1,
  },
  {
    id: 'BJ',
    name: 'Benin',
    uri: <Svgs.BJ height={80} width={widthDimensions} />,
    answer: [
      'Holy See (Vatican City State)',
      'Niger',
      'Benin',
      'Caribbean Netherlands',
    ],
    correct: 2,
  },
  {
    id: 'BL',
    name: 'Saint Barthélemy',
    uri: <Svgs.BL height={80} width={widthDimensions} />,
    answer: [
      'Saint Barthélemy',
      'Bangladesh',
      'Kazakhstan',
      'Trinidad and Tobago',
    ],
    correct: 0,
  },
  {
    id: 'BM',
    name: 'Bermuda',
    uri: <Svgs.BM height={80} width={widthDimensions} />,
    answer: [
      'Bermuda',
      'Western Sahara',
      'Sao Tome and Principe',
      'Guinea-Bissau',
    ],
    correct: 0,
  },
  {
    id: 'BN',
    name: 'Brunei Darussalam',
    uri: <Svgs.BN height={80} width={widthDimensions} />,
    answer: ['Romania', 'Nicaragua', 'Belize', 'Brunei Darussalam'],
    correct: 3,
  },
  {
    id: 'BO',
    name: 'Bolivia, Plurinational State of',
    uri: <Svgs.BO height={80} width={widthDimensions} />,
    answer: [
      'Liechtenstein',
      'Argentina',
      'Pitcairn',
      'Bolivia, Plurinational State of',
    ],
    correct: 3,
  },
  {
    id: 'BQ',
    name: 'Caribbean Netherlands',
    uri: <Svgs.BQ height={80} width={widthDimensions} />,
    answer: ['Sweden', 'Caribbean Netherlands', 'Saint Barthélemy', 'Myanmar'],
    correct: 1,
  },
  {
    id: 'BR',
    name: 'Brazil',
    uri: <Svgs.BR height={80} width={widthDimensions} />,
    answer: ['Belize', 'Brazil', 'Qatar', 'Hong Kong'],
    correct: 1,
  },
  {
    id: 'BS',
    name: 'Bahamas',
    uri: <Svgs.BS height={80} width={widthDimensions} />,
    answer: ['Sudan', 'Namibia', 'Ecuador', 'Bahamas'],
    correct: 3,
  },
  {
    id: 'BT',
    name: 'Bhutan',
    uri: <Svgs.BT height={80} width={widthDimensions} />,
    answer: ['Portugal', 'Afghanistan', 'Macao', 'Bhutan'],
    correct: 3,
  },
  {
    id: 'BV',
    name: 'Bouvet Island',
    uri: <Svgs.BV height={80} width={widthDimensions} />,
    answer: [
      'Zambia',
      'Lebanon',
      'Bouvet Island',
      'Micronesia, Federated States of',
    ],
    correct: 2,
  },
  {
    id: 'BW',
    name: 'Botswana',
    uri: <Svgs.BW height={80} width={widthDimensions} />,
    answer: [
      'Papua New Guinea',
      'New Caledonia',
      'Botswana',
      "China (People's Republic of China)",
    ],
    correct: 2,
  },
  {
    id: 'BY',
    name: 'Belarus',
    uri: <Svgs.BY height={80} width={widthDimensions} />,
    answer: ['Kuwait', 'Belarus', 'Austria', 'Saudi Arabia'],
    correct: 1,
  },
  {
    id: 'BZ',
    name: 'Belize',
    uri: <Svgs.BZ height={80} width={widthDimensions} />,
    answer: [
      'Belize',
      'Cocos (Keeling) Islands',
      'Turkmenistan',
      'Equatorial Guinea',
    ],
    correct: 0,
  },
  {
    id: 'CA',
    name: 'Canada',
    uri: <Svgs.CA height={80} width={widthDimensions} />,
    answer: [
      'Canada',
      'Bermuda',
      'Svalbard and Jan Mayen Islands',
      'Lithuania',
    ],
    correct: 0,
  },
  {
    id: 'CC',
    name: 'Cocos (Keeling) Islands',
    uri: <Svgs.CC height={80} width={widthDimensions} />,
    answer: [
      'Mauritius',
      'French Southern Territories',
      'Albania',
      'Cocos (Keeling) Islands',
    ],
    correct: 3,
  },
  {
    id: 'CD',
    name: 'Congo, the Democratic Republic of the',
    uri: <Svgs.CD height={80} width={widthDimensions} />,
    answer: [
      'Virgin Islands, U.S.',
      'Fiji',
      'Congo, the Democratic Republic of the',
      'Norfolk Island',
    ],
    correct: 2,
  },
  {
    id: 'CF',
    name: 'Central African Republic',
    uri: <Svgs.CF height={80} width={widthDimensions} />,
    answer: ['Switzerland', 'Panama', 'Guyana', 'Central African Republic'],
    correct: 3,
  },
  {
    id: 'CG',
    name: 'Republic of the Congo',
    uri: <Svgs.CG height={80} width={widthDimensions} />,
    answer: [
      'Republic of the Congo',
      'Christmas Island',
      'Slovakia',
      'Namibia',
    ],
    correct: 0,
  },
  {
    id: 'CH',
    name: 'Switzerland',
    uri: <Svgs.CH height={80} width={widthDimensions} />,
    answer: ['Honduras', 'Bhutan', 'Switzerland', 'Virgin Islands, British'],
    correct: 2,
  },
  {
    id: 'CI',
    name: "Côte d'Ivoire",
    uri: <Svgs.CI height={80} width={widthDimensions} />,
    answer: ["Côte d'Ivoire", 'Cameroon', 'Taiwan (Republic of China)', 'Mali'],
    correct: 0,
  },
  {
    id: 'CK',
    name: 'Cook Islands',
    uri: <Svgs.CK height={80} width={widthDimensions} />,
    answer: ['Cook Islands', 'Sao Tome and Principe', 'Finland', 'Guadeloupe'],
    correct: 0,
  },
  {
    id: 'CL',
    name: 'Chile',
    uri: <Svgs.CL height={80} width={widthDimensions} />,
    answer: ['Cocos (Keeling) Islands', 'Latvia', 'Sudan', 'Chile'],
    correct: 3,
  },
  {
    id: 'CM',
    name: 'Cameroon',
    uri: <Svgs.CM height={80} width={widthDimensions} />,
    answer: [
      'Qatar',
      'Cameroon',
      'Cocos (Keeling) Islands',
      'Equatorial Guinea',
    ],
    correct: 1,
  },
  {
    id: 'CN',
    name: "China (People's Republic of China)",
    uri: <Svgs.CN height={80} width={widthDimensions} />,
    answer: [
      "China (People's Republic of China)",
      'Australia',
      'Venezuela, Bolivarian Republic of',
      'Mauritania',
    ],
    correct: 0,
  },
  {
    id: 'CO',
    name: 'Colombia',
    uri: <Svgs.CO height={80} width={widthDimensions} />,
    answer: ['Colombia', 'Vietnam', 'Equatorial Guinea', 'Bulgaria'],
    correct: 0,
  },
  {
    id: 'CR',
    name: 'Costa Rica',
    uri: <Svgs.CR height={80} width={widthDimensions} />,
    answer: ['Kyrgyzstan', 'Paraguay', 'Costa Rica', 'Cocos (Keeling) Islands'],
    correct: 2,
  },
  {
    id: 'CU',
    name: 'Cuba',
    uri: <Svgs.CU height={80} width={widthDimensions} />,
    answer: ['Brazil', 'India', 'Turkmenistan', 'Cuba'],
    correct: 3,
  },
  {
    id: 'CV',
    name: 'Cape Verde',
    uri: <Svgs.CV height={80} width={widthDimensions} />,
    answer: ['Cape Verde', 'Madagascar', 'Bulgaria', 'Oman'],
    correct: 0,
  },
  {
    id: 'CW',
    name: 'Curaçao',
    uri: <Svgs.CW height={80} width={widthDimensions} />,
    answer: ['Curaçao', 'Guadeloupe', 'United States', 'Azerbaijan'],
    correct: 0,
  },
  {
    id: 'CX',
    name: 'Christmas Island',
    uri: <Svgs.CX height={80} width={widthDimensions} />,
    answer: ['Panama', 'Grenada', 'Cayman Islands', 'Christmas Island'],
    correct: 3,
  },
  {
    id: 'CY',
    name: 'Cyprus',
    uri: <Svgs.CY height={80} width={widthDimensions} />,
    answer: ['Ukraine', 'Liberia', 'Bhutan', 'Cyprus'],
    correct: 3,
  },
  {
    id: 'CZ',
    name: 'Czech Republic',
    uri: <Svgs.CZ height={80} width={widthDimensions} />,
    answer: [
      'Czech Republic',
      'Heard Island and McDonald Islands',
      'England',
      'Qatar',
    ],
    correct: 0,
  },
  {
    id: 'DE',
    name: 'Germany',
    uri: <Svgs.DE height={80} width={widthDimensions} />,
    answer: ['Belarus', 'Turks and Caicos Islands', 'Germany', 'Mexico'],
    correct: 2,
  },
  {
    id: 'DJ',
    name: 'Djibouti',
    uri: <Svgs.DJ height={80} width={widthDimensions} />,
    answer: ['Pitcairn', 'Dominica', 'Guatemala', 'Djibouti'],
    correct: 3,
  },
  {
    id: 'DK',
    name: 'Denmark',
    uri: <Svgs.DK height={80} width={widthDimensions} />,
    answer: ['Antarctica', 'Denmark', 'Lebanon', 'Paraguay'],
    correct: 1,
  },
  {
    id: 'DM',
    name: 'Dominica',
    uri: <Svgs.DM height={80} width={widthDimensions} />,
    answer: [
      'Åland Islands',
      'Tanzania, United Republic of',
      'Northern Mariana Islands',
      'Dominica',
    ],
    correct: 3,
  },
  {
    id: 'DO',
    name: 'Dominican Republic',
    uri: <Svgs.DO height={80} width={widthDimensions} />,
    answer: ['Cambodia', 'Cuba', 'Dominican Republic', 'Sao Tome and Principe'],
    correct: 2,
  },
  {
    id: 'DZ',
    name: 'Algeria',
    uri: <Svgs.DZ height={80} width={widthDimensions} />,
    answer: ['Central African Republic', 'Algeria', 'Sudan', 'Kiribati'],
    correct: 1,
  },
  {
    id: 'EC',
    name: 'Ecuador',
    uri: <Svgs.EC height={80} width={widthDimensions} />,
    answer: [
      'Ecuador',
      'Kuwait',
      'Ecuador',
      'Saint Vincent and the Grenadines',
    ],
    correct: 0,
  },
  {
    id: 'EE',
    name: 'Estonia',
    uri: <Svgs.EE height={80} width={widthDimensions} />,
    answer: [
      'French Guiana',
      'Estonia',
      "Laos (Lao People's Democratic Republic)",
      'Slovenia',
    ],
    correct: 1,
  },
  {
    id: 'EG',
    name: 'Egypt',
    uri: <Svgs.EG height={80} width={widthDimensions} />,
    answer: ['Egypt', 'Monaco', 'Trinidad and Tobago', 'Egypt'],
    correct: 0,
  },
  {
    id: 'EH',
    name: 'Western Sahara',
    uri: <Svgs.EH height={80} width={widthDimensions} />,
    answer: [
      'Western Sahara',
      'Tanzania, United Republic of',
      'Bhutan',
      'Morocco',
    ],
    correct: 0,
  },
  {
    id: 'ER',
    name: 'Eritrea',
    uri: <Svgs.ER height={80} width={widthDimensions} />,
    answer: ['Eritrea', 'Hungary', 'Serbia', 'Caribbean Netherlands'],
    correct: 0,
  },
  {
    id: 'ES',
    name: 'Spain',
    uri: <Svgs.ES height={80} width={widthDimensions} />,
    answer: ['Christmas Island', 'Spain', 'Somalia', 'Italy'],
    correct: 1,
  },
  {
    id: 'ET',
    name: 'Ethiopia',
    uri: <Svgs.ET height={80} width={widthDimensions} />,
    answer: ['Saint Barthélemy', 'Kuwait', 'Ethiopia', 'Vietnam'],
    correct: 2,
  },
  {
    id: 'EU',
    name: 'Europe',
    uri: <Svgs.EU height={80} width={widthDimensions} />,
    answer: ['Solomon Islands', 'Europe', 'Iraq', 'Chile'],
    correct: 1,
  },
  {
    id: 'FI',
    name: 'Finland',
    uri: <Svgs.FI height={80} width={widthDimensions} />,
    answer: [
      'Egypt',
      'Svalbard and Jan Mayen Islands',
      'Saint Martin',
      'Finland',
    ],
    correct: 3,
  },
  {
    id: 'FJ',
    name: 'Fiji',
    uri: <Svgs.FJ height={80} width={widthDimensions} />,
    answer: ['Namibia', 'Zimbabwe', 'Antigua and Barbuda', 'Fiji'],
    correct: 3,
  },
  {
    id: 'FK',
    name: 'Falkland Islands (Malvinas)',
    uri: <Svgs.FK height={80} width={widthDimensions} />,
    answer: [
      'Falkland Islands (Malvinas)',
      'Mauritania',
      'Christmas Island',
      'Papua New Guinea',
    ],
    correct: 0,
  },
  {
    id: 'FM',
    name: 'Micronesia, Federated States of',
    uri: <Svgs.FM height={80} width={widthDimensions} />,
    answer: [
      'Micronesia, Federated States of',
      'Solomon Islands',
      'France',
      'Lesotho',
    ],
    correct: 0,
  },
  {
    id: 'FO',
    name: 'Faroe Islands',
    uri: <Svgs.FO height={80} width={widthDimensions} />,
    answer: ['Azerbaijan', 'Pakistan', 'Faroe Islands', 'Mali'],
    correct: 2,
  },
  {
    id: 'FR',
    name: 'France',
    uri: <Svgs.FR height={80} width={widthDimensions} />,
    answer: ['Benin', 'Spain', 'France', 'Lesotho'],
    correct: 2,
  },
  {
    id: 'GA',
    name: 'Gabon',
    uri: <Svgs.GA height={80} width={widthDimensions} />,
    answer: ['British Indian Ocean Territory', 'Burundi', 'Chad', 'Gabon'],
    correct: 3,
  },
  {
    id: 'GB-ENG',
    name: 'England',
    uri: <Svgs.GB_ENG height={80} width={widthDimensions} />,
    answer: ['Spain', 'England', 'Montenegro', 'Peru'],
    correct: 1,
  },
  {
    id: 'GB-NIR',
    name: 'Northern Ireland',
    uri: <Svgs.GB_NIR height={80} width={widthDimensions} />,
    answer: [
      'Korea, Republic of',
      'Sint Maarten (Dutch part)',
      'Angola',
      'Northern Ireland',
    ],
    correct: 3,
  },
  {
    id: 'GB-SCT',
    name: 'Scotland',
    uri: <Svgs.GB_SCT height={80} width={widthDimensions} />,
    answer: ['Lebanon', 'Scotland', 'Ethiopia', 'Vanuatu'],
    correct: 1,
  },
  {
    id: 'GB-WLS',
    name: 'Wales',
    uri: <Svgs.GB_WLS height={80} width={widthDimensions} />,
    answer: ['Wales', 'Georgia', 'Senegal', 'Hungary'],
    correct: 0,
  },
  {
    id: 'GB',
    name: 'United Kingdom',
    uri: <Svgs.GB height={80} width={widthDimensions} />,
    answer: [
      'United Kingdom',
      'Christmas Island',
      'Comoros',
      'French Polynesia',
    ],
    correct: 0,
  },
  {
    id: 'GD',
    name: 'Grenada',
    uri: <Svgs.GD height={80} width={widthDimensions} />,
    answer: ['France', 'Grenada', 'Syrian Arab Republic', 'Malaysia'],
    correct: 1,
  },
  {
    id: 'GE',
    name: 'Georgia',
    uri: <Svgs.GE height={80} width={widthDimensions} />,
    answer: ['Sweden', 'Georgia', 'Canada', 'Guadeloupe'],
    correct: 1,
  },
  {
    id: 'GF',
    name: 'French Guiana',
    uri: <Svgs.GF height={80} width={widthDimensions} />,
    answer: ['Ethiopia', 'Japan', 'French Guiana', 'Poland'],
    correct: 2,
  },
  {
    id: 'GG',
    name: 'Guernsey',
    uri: <Svgs.GG height={80} width={widthDimensions} />,
    answer: ['Kyrgyzstan', 'Denmark', 'Swaziland', 'Guernsey'],
    correct: 3,
  },
  {
    id: 'GH',
    name: 'Ghana',
    uri: <Svgs.GH height={80} width={widthDimensions} />,
    answer: ['Bulgaria', 'Namibia', 'Ghana', 'Tonga'],
    correct: 2,
  },
  {
    id: 'GI',
    name: 'Gibraltar',
    uri: <Svgs.GI height={80} width={widthDimensions} />,
    answer: ['Gibraltar', 'New Caledonia', 'Sudan', 'Caribbean Netherlands'],
    correct: 0,
  },
  {
    id: 'GL',
    name: 'Greenland',
    uri: <Svgs.GL height={80} width={widthDimensions} />,
    answer: ['Scotland', 'Guadeloupe', 'Greenland', 'Uruguay'],
    correct: 2,
  },
  {
    id: 'GM',
    name: 'Gambia',
    uri: <Svgs.GM height={80} width={widthDimensions} />,
    answer: ['Grenada', 'Virgin Islands, U.S.', 'Gambia', 'Comoros'],
    correct: 2,
  },
  {
    id: 'GN',
    name: 'Guinea',
    uri: <Svgs.GN height={80} width={widthDimensions} />,
    answer: ['Martinique', 'Guinea', 'Brazil', 'Tunisia'],
    correct: 1,
  },
  {
    id: 'GP',
    name: 'Guadeloupe',
    uri: <Svgs.GP height={80} width={widthDimensions} />,
    answer: [
      'Kazakhstan',
      'Taiwan (Republic of China)',
      'Guadeloupe',
      'Andorra',
    ],
    correct: 2,
  },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    uri: <Svgs.GQ height={80} width={widthDimensions} />,
    answer: ['Italy', 'Philippines', 'Egypt', 'Equatorial Guinea'],
    correct: 3,
  },
  {
    id: 'GR',
    name: 'Greece',
    uri: <Svgs.GR height={80} width={widthDimensions} />,
    answer: [
      'Dominican Republic',
      'Saint Helena, Ascension and Tristan da Cunha',
      'British Indian Ocean Territory',
      'Greece',
    ],
    correct: 3,
  },
  {
    id: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    uri: <Svgs.GS height={80} width={widthDimensions} />,
    answer: [
      'Vietnam',
      'South Georgia and the South Sandwich Islands',
      'Spain',
      'Myanmar',
    ],
    correct: 1,
  },
  {
    id: 'GT',
    name: 'Guatemala',
    uri: <Svgs.GT height={80} width={widthDimensions} />,
    answer: ['Guatemala', 'Israel', 'Solomon Islands', 'Switzerland'],
    correct: 0,
  },
  {
    id: 'GU',
    name: 'Guam',
    uri: <Svgs.GU height={80} width={widthDimensions} />,
    answer: ['Guam', 'Seychelles', 'Northern Ireland', 'Israel'],
    correct: 0,
  },
  {
    id: 'GW',
    name: 'Guinea-Bissau',
    uri: <Svgs.GW height={80} width={widthDimensions} />,
    answer: ['Sri Lanka', 'Syrian Arab Republic', 'Guinea-Bissau', 'Georgia'],
    correct: 2,
  },
  {
    id: 'GY',
    name: 'Guyana',
    uri: <Svgs.GY height={80} width={widthDimensions} />,
    answer: [
      "Korea, Democratic People's Republic of",
      'Tajikistan',
      'Guyana',
      'Antarctica',
    ],
    correct: 2,
  },
  {
    id: 'HK',
    name: 'Hong Kong',
    uri: <Svgs.HK height={80} width={widthDimensions} />,
    answer: [
      'Saint Vincent and the Grenadines',
      'Northern Mariana Islands',
      'Antarctica',
      'Hong Kong',
    ],
    correct: 3,
  },
  {
    id: 'HM',
    name: 'Heard Island and McDonald Islands',
    uri: <Svgs.HM height={80} width={widthDimensions} />,
    answer: [
      'Heard Island and McDonald Islands',
      'Sierra Leone',
      'Heard Island and McDonald Islands',
      'Ecuador',
    ],
    correct: 0,
  },
  {
    id: 'HN',
    name: 'Honduras',
    uri: <Svgs.HN height={80} width={widthDimensions} />,
    answer: ['Honduras', 'Bosnia and Herzegovina', 'Zambia', 'Myanmar'],
    correct: 0,
  },
  {
    id: 'HR',
    name: 'Croatia',
    uri: <Svgs.HR height={80} width={widthDimensions} />,
    answer: ['French Polynesia', 'Benin', 'Croatia', 'Jordan'],
    correct: 2,
  },
  {
    id: 'HT',
    name: 'Haiti',
    uri: <Svgs.HT height={80} width={widthDimensions} />,
    answer: ['England', 'Saint Martin', 'Haiti', 'US Minor Outlying Islands'],
    correct: 2,
  },
  {
    id: 'HU',
    name: 'Hungary',
    uri: <Svgs.HU height={80} width={widthDimensions} />,
    answer: ['Hungary', 'Montserrat', 'Cocos (Keeling) Islands', 'Réunion'],
    correct: 0,
  },
  {
    id: 'ID',
    name: 'Indonesia',
    uri: <Svgs.ID height={80} width={widthDimensions} />,
    answer: ['New Zealand', 'Central African Republic', 'Ghana', 'Indonesia'],
    correct: 3,
  },
  {
    id: 'IE',
    name: 'Ireland',
    uri: <Svgs.IE height={80} width={widthDimensions} />,
    answer: ['Ireland', 'Moldova, Republic of', 'Fiji', 'Niue'],
    correct: 0,
  },
  {
    id: 'IL',
    name: 'Israel',
    uri: <Svgs.IL height={80} width={widthDimensions} />,
    answer: ['Israel', 'Greenland', 'Algeria', 'Sweden'],
    correct: 0,
  },
  {
    id: 'IM',
    name: 'Isle of Man',
    uri: <Svgs.IM height={80} width={widthDimensions} />,
    answer: [
      'Scotland',
      'Isle of Man',
      'Indonesia',
      'Sint Maarten (Dutch part)',
    ],
    correct: 1,
  },
  {
    id: 'IN',
    name: 'India',
    uri: <Svgs.IN height={80} width={widthDimensions} />,
    answer: ['India', 'Japan', 'Faroe Islands', 'Paraguay'],
    correct: 0,
  },
  {
    id: 'IO',
    name: 'British Indian Ocean Territory',
    uri: <Svgs.IO height={80} width={widthDimensions} />,
    answer: ['Georgia', 'British Indian Ocean Territory', 'Serbia', 'Norway'],
    correct: 1,
  },
  {
    id: 'IQ',
    name: 'Iraq',
    uri: <Svgs.IQ height={80} width={widthDimensions} />,
    answer: ['Armenia', 'Réunion', 'Iraq', 'Myanmar'],
    correct: 2,
  },
  {
    id: 'IR',
    name: 'Iran, Islamic Republic of',
    uri: <Svgs.IR height={80} width={widthDimensions} />,
    answer: ['Palau', 'Lithuania', 'Georgia', 'Iran, Islamic Republic of'],
    correct: 3,
  },
  {
    id: 'IS',
    name: 'Iceland',
    uri: <Svgs.IS height={80} width={widthDimensions} />,
    answer: ['Iceland', 'Papua New Guinea', 'French Guiana', 'Guinea-Bissau'],
    correct: 0,
  },
  {
    id: 'IT',
    name: 'Italy',
    uri: <Svgs.IT height={80} width={widthDimensions} />,
    answer: ['Russian Federation', 'Italy', 'Sri Lanka', 'Dominican Republic'],
    correct: 1,
  },
  {
    id: 'JE',
    name: 'Jersey',
    uri: <Svgs.JE height={80} width={widthDimensions} />,
    answer: ['Anguilla', 'Nigeria', 'Jersey', 'Turkey'],
    correct: 2,
  },
  {
    id: 'JM',
    name: 'Jamaica',
    uri: <Svgs.JM height={80} width={widthDimensions} />,
    answer: [
      'Faroe Islands',
      'Wallis and Futuna Islands',
      'South Georgia and the South Sandwich Islands',
      'Jamaica',
    ],
    correct: 3,
  },
  {
    id: 'JO',
    name: 'Jordan',
    uri: <Svgs.JO height={80} width={widthDimensions} />,
    answer: ['Mali', 'Jordan', 'Micronesia, Federated States of', 'Zimbabwe'],
    correct: 1,
  },
  {
    id: 'JP',
    name: 'Japan',
    uri: <Svgs.JP height={80} width={widthDimensions} />,
    answer: ['Bahamas', 'Monaco', 'Japan', 'Syrian Arab Republic'],
    correct: 2,
  },
  {
    id: 'KE',
    name: 'Kenya',
    uri: <Svgs.KE height={80} width={widthDimensions} />,
    answer: ['Kuwait', 'Western Sahara', 'Kenya', 'Sierra Leone'],
    correct: 2,
  },
  {
    id: 'KG',
    name: 'Kyrgyzstan',
    uri: <Svgs.KG height={80} width={widthDimensions} />,
    answer: ['Cambodia', 'Bermuda', 'Kyrgyzstan', 'Kazakhstan'],
    correct: 2,
  },
  {
    id: 'KH',
    name: 'Cambodia',
    uri: <Svgs.KH height={80} width={widthDimensions} />,
    answer: ['Jamaica', 'Cambodia', 'US Minor Outlying Islands', 'Barbados'],
    correct: 1,
  },
  {
    id: 'KI',
    name: 'Kiribati',
    uri: <Svgs.KI height={80} width={widthDimensions} />,
    answer: ['Syrian Arab Republic', 'Kiribati', 'Macao', 'Dominica'],
    correct: 1,
  },
  {
    id: 'KM',
    name: 'Comoros',
    uri: <Svgs.KM height={80} width={widthDimensions} />,
    answer: [
      'Sudan',
      "Korea, Democratic People's Republic of",
      'Colombia',
      'Comoros',
    ],
    correct: 3,
  },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    uri: <Svgs.KN height={80} width={widthDimensions} />,
    answer: ['Germany', 'Saint Kitts and Nevis', 'Kiribati', 'Ukraine'],
    correct: 1,
  },
  {
    id: 'KP',
    name: "Korea, Democratic People's Republic of",
    uri: <Svgs.KP height={80} width={widthDimensions} />,
    answer: [
      "Korea, Democratic People's Republic of",
      'Pitcairn',
      'Luxembourg',
      'England',
    ],
    correct: 0,
  },
  {
    id: 'KR',
    name: 'Korea, Republic of',
    uri: <Svgs.KR height={80} width={widthDimensions} />,
    answer: [
      'Uzbekistan',
      'Moldova, Republic of',
      'Spain',
      'Korea, Republic of',
    ],
    correct: 3,
  },
  {
    id: 'KW',
    name: 'Kuwait',
    uri: <Svgs.KW height={80} width={widthDimensions} />,
    answer: ['Seychelles', 'Kuwait', 'Mauritania', 'Fiji'],
    correct: 1,
  },
  {
    id: 'KY',
    name: 'Cayman Islands',
    uri: <Svgs.KY height={80} width={widthDimensions} />,
    answer: [
      'Faroe Islands',
      'Thailand',
      'Iran, Islamic Republic of',
      'Cayman Islands',
    ],
    correct: 3,
  },
  {
    id: 'KZ',
    name: 'Kazakhstan',
    uri: <Svgs.KZ height={80} width={widthDimensions} />,
    answer: ['Costa Rica', 'Kazakhstan', 'Virgin Islands, British', 'Malawi'],
    correct: 1,
  },
  {
    id: 'LA',
    name: "Laos (Lao People's Democratic Republic)",
    uri: <Svgs.LA height={80} width={widthDimensions} />,
    answer: [
      "Laos (Lao People's Democratic Republic)",
      'Venezuela, Bolivarian Republic of',
      'Aruba',
      'Martinique',
    ],
    correct: 0,
  },
  {
    id: 'LB',
    name: 'Lebanon',
    uri: <Svgs.LB height={80} width={widthDimensions} />,
    answer: ['Mexico', 'Saint Pierre and Miquelon', 'Lebanon', 'France'],
    correct: 2,
  },
  {
    id: 'LC',
    name: 'Saint Lucia',
    uri: <Svgs.LC height={80} width={widthDimensions} />,
    answer: [
      'Saint Lucia',
      'Moldova, Republic of',
      'Saint Pierre and Miquelon',
      'Belarus',
    ],
    correct: 0,
  },
  {
    id: 'LI',
    name: 'Liechtenstein',
    uri: <Svgs.LI height={80} width={widthDimensions} />,
    answer: [
      'Isle of Man',
      'Russian Federation',
      'Bangladesh',
      'Liechtenstein',
    ],
    correct: 3,
  },
  {
    id: 'LK',
    name: 'Sri Lanka',
    uri: <Svgs.LK height={80} width={widthDimensions} />,
    answer: ['Bhutan', 'Sri Lanka', 'Liberia', 'Somalia'],
    correct: 1,
  },
  {
    id: 'LR',
    name: 'Liberia',
    uri: <Svgs.LR height={80} width={widthDimensions} />,
    answer: ['Finland', 'Mauritius', 'Liberia', 'Tokelau'],
    correct: 2,
  },
  {
    id: 'LS',
    name: 'Lesotho',
    uri: <Svgs.LS height={80} width={widthDimensions} />,
    answer: ['Lesotho', 'Moldova, Republic of', 'Denmark', 'Palau'],
    correct: 0,
  },
  {
    id: 'LT',
    name: 'Lithuania',
    uri: <Svgs.LT height={80} width={widthDimensions} />,
    answer: [
      'Saint Helena, Ascension and Tristan da Cunha',
      'Burkina Faso',
      'Malta',
      'Lithuania',
    ],
    correct: 3,
  },
  {
    id: 'LU',
    name: 'Luxembourg',
    uri: <Svgs.LU height={80} width={widthDimensions} />,
    answer: [
      'Italy',
      'Luxembourg',
      'Congo, the Democratic Republic of the',
      'Turks and Caicos Islands',
    ],
    correct: 1,
  },
  {
    id: 'LV',
    name: 'Latvia',
    uri: <Svgs.LV height={80} width={widthDimensions} />,
    answer: ['Chile', 'Latvia', 'Liechtenstein', 'Palestine'],
    correct: 1,
  },
  {
    id: 'LY',
    name: 'Libya',
    uri: <Svgs.LY height={80} width={widthDimensions} />,
    answer: ['New Caledonia', 'Libya', 'South Africa', 'Cyprus'],
    correct: 1,
  },
  {
    id: 'MA',
    name: 'Morocco',
    uri: <Svgs.MA height={80} width={widthDimensions} />,
    answer: [
      'Taiwan (Republic of China)',
      'Wales',
      'Equatorial Guinea',
      'Morocco',
    ],
    correct: 3,
  },
  {
    id: 'MC',
    name: 'Monaco',
    uri: <Svgs.MC height={80} width={widthDimensions} />,
    answer: [
      'Saint Vincent and the Grenadines',
      'Albania',
      'Montserrat',
      'Monaco',
    ],
    correct: 3,
  },
  {
    id: 'MD',
    name: 'Moldova, Republic of',
    uri: <Svgs.MD height={80} width={widthDimensions} />,
    answer: [
      'Moldova, Republic of',
      'Honduras',
      'Australia',
      'Saint Helena, Ascension and Tristan da Cunha',
    ],
    correct: 0,
  },
  {
    id: 'ME',
    name: 'Montenegro',
    uri: <Svgs.ME height={80} width={widthDimensions} />,
    answer: ['Montenegro', 'South Sudan', 'Iraq', 'Bosnia and Herzegovina'],
    correct: 0,
  },
  {
    id: 'MF',
    name: 'Saint Martin',
    uri: <Svgs.MF height={80} width={widthDimensions} />,
    answer: ['Brazil', 'Korea, Republic of', 'Turkmenistan', 'Saint Martin'],
    correct: 3,
  },
  {
    id: 'MG',
    name: 'Madagascar',
    uri: <Svgs.MG height={80} width={widthDimensions} />,
    answer: ['Réunion', 'Madagascar', 'Libya', 'Antigua and Barbuda'],
    correct: 1,
  },
  {
    id: 'MH',
    name: 'Marshall Islands',
    uri: <Svgs.MH height={80} width={widthDimensions} />,
    answer: [
      'Saint Pierre and Miquelon',
      'Marshall Islands',
      'Guyana',
      'Djibouti',
    ],
    correct: 1,
  },
  {
    id: 'MK',
    name: 'North Macedonia',
    uri: <Svgs.MK height={80} width={widthDimensions} />,
    answer: [
      'Paraguay',
      'Iran, Islamic Republic of',
      'Djibouti',
      'North Macedonia',
    ],
    correct: 3,
  },
  {
    id: 'ML',
    name: 'Mali',
    uri: <Svgs.ML height={80} width={widthDimensions} />,
    answer: ['Curaçao', 'Mali', 'Northern Mariana Islands', 'Réunion'],
    correct: 1,
  },
  {
    id: 'MM',
    name: 'Myanmar',
    uri: <Svgs.MM height={80} width={widthDimensions} />,
    answer: ['Myanmar', 'Kenya', 'Germany', 'Saudi Arabia'],
    correct: 0,
  },
  {
    id: 'MN',
    name: 'Mongolia',
    uri: <Svgs.MN height={80} width={widthDimensions} />,
    answer: ['Belize', 'Greenland', 'Nepal', 'Mongolia'],
    correct: 3,
  },
  {
    id: 'MO',
    name: 'Macao',
    uri: <Svgs.MO height={80} width={widthDimensions} />,
    answer: ['Macao', 'Bermuda', 'Indonesia', 'Uruguay'],
    correct: 0,
  },
  {
    id: 'MP',
    name: 'Northern Mariana Islands',
    uri: <Svgs.MP height={80} width={widthDimensions} />,
    answer: [
      'Northern Mariana Islands',
      'Saint Kitts and Nevis',
      'Egypt',
      'Somalia',
    ],
    correct: 0,
  },
  {
    id: 'MQ',
    name: 'Martinique',
    uri: <Svgs.MQ height={80} width={widthDimensions} />,
    answer: ['Martinique', 'Mexico', 'Philippines', 'Algeria'],
    correct: 0,
  },
  {
    id: 'MR',
    name: 'Mauritania',
    uri: <Svgs.MR height={80} width={widthDimensions} />,
    answer: [
      'Mauritania',
      'Senegal',
      'Argentina',
      'Heard Island and McDonald Islands',
    ],
    correct: 0,
  },
  {
    id: 'MS',
    name: 'Montserrat',
    uri: <Svgs.MS height={80} width={widthDimensions} />,
    answer: ['Bangladesh', 'Sierra Leone', 'Croatia', 'Montserrat'],
    correct: 3,
  },
  {
    id: 'MT',
    name: 'Malta',
    uri: <Svgs.MT height={80} width={widthDimensions} />,
    answer: ['Caribbean Netherlands', 'Hong Kong', 'Malta', 'El Salvador'],
    correct: 2,
  },
  {
    id: 'MU',
    name: 'Mauritius',
    uri: <Svgs.MU height={80} width={widthDimensions} />,
    answer: [
      'Mauritius',
      'Ukraine',
      'India',
      'Congo, the Democratic Republic of the',
    ],
    correct: 0,
  },
  {
    id: 'MV',
    name: 'Maldives',
    uri: <Svgs.MV height={80} width={widthDimensions} />,
    answer: [
      "Korea, Democratic People's Republic of",
      'Maldives',
      'Virgin Islands, U.S.',
      'Bolivia, Plurinational State of',
    ],
    correct: 1,
  },
  {
    id: 'MW',
    name: 'Malawi',
    uri: <Svgs.MW height={80} width={widthDimensions} />,
    answer: ['Latvia', 'Belgium', 'Malawi', 'Nepal'],
    correct: 2,
  },
  {
    id: 'MX',
    name: 'Mexico',
    uri: <Svgs.MX height={80} width={widthDimensions} />,
    answer: ['Mexico', 'Paraguay', 'Bulgaria', 'Kuwait'],
    correct: 0,
  },
  {
    id: 'MY',
    name: 'Malaysia',
    uri: <Svgs.MY height={80} width={widthDimensions} />,
    answer: ['Mozambique', 'Palau', 'Canada', 'Malaysia'],
    correct: 3,
  },
  {
    id: 'MZ',
    name: 'Mozambique',
    uri: <Svgs.MZ height={80} width={widthDimensions} />,
    answer: ['Western Sahara', 'Iceland', 'Ukraine', 'Mozambique'],
    correct: 3,
  },
  {
    id: 'NA',
    name: 'Namibia',
    uri: <Svgs.NA height={80} width={widthDimensions} />,
    answer: ['Namibia', 'Nigeria', 'Bouvet Island', 'Portugal'],
    correct: 0,
  },
  {
    id: 'NC',
    name: 'New Caledonia',
    uri: <Svgs.NC height={80} width={widthDimensions} />,
    answer: [
      'Saint Pierre and Miquelon',
      'New Caledonia',
      'Finland',
      'Indonesia',
    ],
    correct: 1,
  },
  {
    id: 'NE',
    name: 'Niger',
    uri: <Svgs.NE height={80} width={widthDimensions} />,
    answer: ['Fiji', 'Gibraltar', 'Niger', 'Togo'],
    correct: 2,
  },
  {
    id: 'NF',
    name: 'Norfolk Island',
    uri: <Svgs.NF height={80} width={widthDimensions} />,
    answer: ['Palau', 'Germany', 'Haiti', 'Norfolk Island'],
    correct: 3,
  },
  {
    id: 'NG',
    name: 'Nigeria',
    uri: <Svgs.NG height={80} width={widthDimensions} />,
    answer: ['Antarctica', 'Nigeria', 'Romania', 'Nigeria'],
    correct: 3,
  },
  {
    id: 'NI',
    name: 'Nicaragua',
    uri: <Svgs.NI height={80} width={widthDimensions} />,
    answer: [
      'Nicaragua',
      'Nepal',
      'Benin',
      "Laos (Lao People's Democratic Republic)",
    ],
    correct: 0,
  },
  {
    id: 'NL',
    name: 'Netherlands',
    uri: <Svgs.NL height={80} width={widthDimensions} />,
    answer: [
      'Saint Kitts and Nevis',
      'Czech Republic',
      'Netherlands',
      'Slovenia',
    ],
    correct: 2,
  },
  {
    id: 'NO',
    name: 'Norway',
    uri: <Svgs.NO height={80} width={widthDimensions} />,
    answer: ['Georgia', 'Norway', 'Tonga', 'Norway'],
    correct: 3,
  },
  {
    id: 'NP',
    name: 'Nepal',
    uri: <Svgs.NP height={80} width={widthDimensions} />,
    answer: ['Swaziland', 'Nepal', 'Canada', 'Malta'],
    correct: 1,
  },
  {
    id: 'NR',
    name: 'Nauru',
    uri: <Svgs.NR height={80} width={widthDimensions} />,
    answer: ['Guam', 'Pakistan', 'Argentina', 'Nauru'],
    correct: 3,
  },
  {
    id: 'NU',
    name: 'Niue',
    uri: <Svgs.NU height={80} width={widthDimensions} />,
    answer: ['Niue', 'Timor-Leste', 'Aruba', 'Madagascar'],
    correct: 0,
  },
  {
    id: 'NZ',
    name: 'New Zealand',
    uri: <Svgs.NZ height={80} width={widthDimensions} />,
    answer: [
      'Cayman Islands',
      'New Zealand',
      'Guernsey',
      'Saint Helena, Ascension and Tristan da Cunha',
    ],
    correct: 1,
  },
  {
    id: 'OM',
    name: 'Oman',
    uri: <Svgs.OM height={80} width={widthDimensions} />,
    answer: ['Panama', 'Australia', 'Oman', 'New Caledonia'],
    correct: 2,
  },
  {
    id: 'PA',
    name: 'Panama',
    uri: <Svgs.PA height={80} width={widthDimensions} />,
    answer: [
      'British Indian Ocean Territory',
      'Panama',
      'Austria',
      'Puerto Rico',
    ],
    correct: 1,
  },
  {
    id: 'PE',
    name: 'Peru',
    uri: <Svgs.PE height={80} width={widthDimensions} />,
    answer: ['Peru', 'Ghana', 'Qatar', "China (People's Republic of China)"],
    correct: 0,
  },
  {
    id: 'PF',
    name: 'French Polynesia',
    uri: <Svgs.PF height={80} width={widthDimensions} />,
    answer: [
      'Wales',
      'Liechtenstein',
      'French Polynesia',
      'Saint Pierre and Miquelon',
    ],
    correct: 2,
  },
  {
    id: 'PG',
    name: 'Papua New Guinea',
    uri: <Svgs.PG height={80} width={widthDimensions} />,
    answer: ['Western Sahara', 'Papua New Guinea', 'Iraq', 'San Marino'],
    correct: 1,
  },
  {
    id: 'PH',
    name: 'Philippines',
    uri: <Svgs.PH height={80} width={widthDimensions} />,
    answer: ['Djibouti', 'Philippines', 'Jersey', 'Peru'],
    correct: 1,
  },
  {
    id: 'PK',
    name: 'Pakistan',
    uri: <Svgs.PK height={80} width={widthDimensions} />,
    answer: ['Finland', 'Pakistan', 'Montenegro', 'Somalia'],
    correct: 1,
  },
  {
    id: 'PL',
    name: 'Poland',
    uri: <Svgs.PL height={80} width={widthDimensions} />,
    answer: ['Western Sahara', 'Haiti', 'Poland', 'Suriname'],
    correct: 2,
  },
  {
    id: 'PM',
    name: 'Saint Pierre and Miquelon',
    uri: <Svgs.PM height={80} width={widthDimensions} />,
    answer: [
      'El Salvador',
      'Marshall Islands',
      'Saint Pierre and Miquelon',
      'Colombia',
    ],
    correct: 2,
  },
  {
    id: 'PN',
    name: 'Pitcairn',
    uri: <Svgs.PN height={80} width={widthDimensions} />,
    answer: ['Pitcairn', 'Haiti', 'Solomon Islands', 'Cameroon'],
    correct: 0,
  },
  {
    id: 'PR',
    name: 'Puerto Rico',
    uri: <Svgs.PR height={80} width={widthDimensions} />,
    answer: ['Portugal', 'Sri Lanka', 'Anguilla', 'Puerto Rico'],
    correct: 3,
  },
  {
    id: 'PS',
    name: 'Palestine',
    uri: <Svgs.PS height={80} width={widthDimensions} />,
    answer: ['French Polynesia', 'Palestine', 'Belgium', 'Gibraltar'],
    correct: 1,
  },
  {
    id: 'PT',
    name: 'Portugal',
    uri: <Svgs.PT height={80} width={widthDimensions} />,
    answer: ['Malta', 'Sierra Leone', 'Czech Republic', 'Portugal'],
    correct: 3,
  },
  {
    id: 'PW',
    name: 'Palau',
    uri: <Svgs.PW height={80} width={widthDimensions} />,
    answer: [
      'Svalbard and Jan Mayen Islands',
      'Mexico',
      'Palau',
      'Bosnia and Herzegovina',
    ],
    correct: 2,
  },
  {
    id: 'PY',
    name: 'Paraguay',
    uri: <Svgs.PY height={80} width={widthDimensions} />,
    answer: ['Paraguay', 'Mauritania', 'Palestine', 'Bosnia and Herzegovina'],
    correct: 0,
  },
  {
    id: 'QA',
    name: 'Qatar',
    uri: <Svgs.QA height={80} width={widthDimensions} />,
    answer: ['Denmark', 'Qatar', 'Réunion', 'Israel'],
    correct: 1,
  },
  {
    id: 'RE',
    name: 'Réunion',
    uri: <Svgs.RE height={80} width={widthDimensions} />,
    answer: ['United Kingdom', 'Réunion', 'Maldives', 'Panama'],
    correct: 1,
  },
  {
    id: 'RO',
    name: 'Romania',
    uri: <Svgs.RO height={80} width={widthDimensions} />,
    answer: [
      'Venezuela, Bolivarian Republic of',
      'United Arab Emirates',
      'Namibia',
      'Romania',
    ],
    correct: 3,
  },
  {
    id: 'RS',
    name: 'Serbia',
    uri: <Svgs.RS height={80} width={widthDimensions} />,
    answer: ['Serbia', 'Russian Federation', 'Cyprus', 'Norway'],
    correct: 0,
  },
  {
    id: 'RU',
    name: 'Russian Federation',
    uri: <Svgs.RU height={80} width={widthDimensions} />,
    answer: [
      'Russian Federation',
      'Palestine',
      'Grenada',
      'Saint Kitts and Nevis',
    ],
    correct: 0,
  },
  {
    id: 'RW',
    name: 'Rwanda',
    uri: <Svgs.RW height={80} width={widthDimensions} />,
    answer: ['Rwanda', 'Turkey', "Côte d'Ivoire", 'Liberia'],
    correct: 0,
  },
  {
    id: 'SA',
    name: 'Saudi Arabia',
    uri: <Svgs.SA height={80} width={widthDimensions} />,
    answer: [
      'French Polynesia',
      'Saudi Arabia',
      'Bahamas',
      'Northern Mariana Islands',
    ],
    correct: 1,
  },
  {
    id: 'SB',
    name: 'Solomon Islands',
    uri: <Svgs.SB height={80} width={widthDimensions} />,
    answer: ['Solomon Islands', 'Mozambique', 'Sudan', 'Canada'],
    correct: 0,
  },
  {
    id: 'SC',
    name: 'Seychelles',
    uri: <Svgs.SC height={80} width={widthDimensions} />,
    answer: ['Seychelles', 'Senegal', "Côte d'Ivoire", 'Lebanon'],
    correct: 0,
  },
  {
    id: 'SD',
    name: 'Sudan',
    uri: <Svgs.SD height={80} width={widthDimensions} />,
    answer: ['Sudan', 'Germany', 'Singapore', 'Cambodia'],
    correct: 0,
  },
  {
    id: 'SE',
    name: 'Sweden',
    uri: <Svgs.SE height={80} width={widthDimensions} />,
    answer: ['Sweden', 'France', 'Svalbard and Jan Mayen Islands', 'Malaysia'],
    correct: 0,
  },
  {
    id: 'SG',
    name: 'Singapore',
    uri: <Svgs.SG height={80} width={widthDimensions} />,
    answer: ['Bhutan', 'Singapore', 'Mauritius', 'Seychelles'],
    correct: 1,
  },
  {
    id: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    uri: <Svgs.SH height={80} width={widthDimensions} />,
    answer: [
      'Bahamas',
      'Saint Helena, Ascension and Tristan da Cunha',
      'Svalbard and Jan Mayen Islands',
      'Hungary',
    ],
    correct: 1,
  },
  {
    id: 'SI',
    name: 'Slovenia',
    uri: <Svgs.SI height={80} width={widthDimensions} />,
    answer: [
      'Oman',
      'Bosnia and Herzegovina',
      'Slovenia',
      'Moldova, Republic of',
    ],
    correct: 2,
  },
  {
    id: 'SJ',
    name: 'Svalbard and Jan Mayen Islands',
    uri: <Svgs.SJ height={80} width={widthDimensions} />,
    answer: [
      'Mali',
      'Svalbard and Jan Mayen Islands',
      'Taiwan (Republic of China)',
      'Cook Islands',
    ],
    correct: 1,
  },
  {
    id: 'SK',
    name: 'Slovakia',
    uri: <Svgs.SK height={80} width={widthDimensions} />,
    answer: ['Belgium', 'Holy See (Vatican City State)', 'Slovakia', 'Kuwait'],
    correct: 2,
  },
  {
    id: 'SL',
    name: 'Sierra Leone',
    uri: <Svgs.SL height={80} width={widthDimensions} />,
    answer: ['Australia', 'Moldova, Republic of', 'Sierra Leone', 'Qatar'],
    correct: 2,
  },
  {
    id: 'SM',
    name: 'San Marino',
    uri: <Svgs.SM height={80} width={widthDimensions} />,
    answer: ['Ukraine', 'Jamaica', 'Northern Ireland', 'San Marino'],
    correct: 3,
  },
  {
    id: 'SN',
    name: 'Senegal',
    uri: <Svgs.SN height={80} width={widthDimensions} />,
    answer: ['Timor-Leste', 'Ghana', 'Senegal', 'Georgia'],
    correct: 2,
  },
  {
    id: 'SO',
    name: 'Somalia',
    uri: <Svgs.SO height={80} width={widthDimensions} />,
    answer: ['Somalia', 'Martinique', 'Belarus', 'Réunion'],
    correct: 0,
  },
  {
    id: 'SR',
    name: 'Suriname',
    uri: <Svgs.SR height={80} width={widthDimensions} />,
    answer: [
      'Azerbaijan',
      'Virgin Islands, British',
      'Equatorial Guinea',
      'Suriname',
    ],
    correct: 3,
  },
  {
    id: 'SS',
    name: 'South Sudan',
    uri: <Svgs.SS height={80} width={widthDimensions} />,
    answer: ['Pitcairn', 'South Sudan', 'Azerbaijan', 'Gibraltar'],
    correct: 1,
  },
  {
    id: 'ST',
    name: 'Sao Tome and Principe',
    uri: <Svgs.ST height={80} width={widthDimensions} />,
    answer: [
      'Syrian Arab Republic',
      'Brunei Darussalam',
      'Lithuania',
      'Sao Tome and Principe',
    ],
    correct: 3,
  },
  {
    id: 'SV',
    name: 'El Salvador',
    uri: <Svgs.SV height={80} width={widthDimensions} />,
    answer: ['El Salvador', 'New Caledonia', 'Solomon Islands', 'Belgium'],
    correct: 0,
  },
  {
    id: 'SX',
    name: 'Sint Maarten (Dutch part)',
    uri: <Svgs.SX height={80} width={widthDimensions} />,
    answer: [
      'Norway',
      'Burundi',
      'Saint Helena, Ascension and Tristan da Cunha',
      'Sint Maarten (Dutch part)',
    ],
    correct: 3,
  },
  {
    id: 'SY',
    name: 'Syrian Arab Republic',
    uri: <Svgs.SY height={80} width={widthDimensions} />,
    answer: ['Malta', 'Syrian Arab Republic', 'Romania', 'Cook Islands'],
    correct: 1,
  },
  {
    id: 'SZ',
    name: 'Swaziland',
    uri: <Svgs.SZ height={80} width={widthDimensions} />,
    answer: ['Bosnia and Herzegovina', 'Israel', 'Swaziland', 'Sierra Leone'],
    correct: 2,
  },
  {
    id: 'TC',
    name: 'Turks and Caicos Islands',
    uri: <Svgs.TC height={80} width={widthDimensions} />,
    answer: [
      'United Arab Emirates',
      'Turks and Caicos Islands',
      'Qatar',
      'Guatemala',
    ],
    correct: 1,
  },
  {
    id: 'TD',
    name: 'Chad',
    uri: <Svgs.TD height={80} width={widthDimensions} />,
    answer: [
      'French Guiana',
      'British Indian Ocean Territory',
      'Chad',
      'Timor-Leste',
    ],
    correct: 2,
  },
  {
    id: 'TF',
    name: 'French Southern Territories',
    uri: <Svgs.TF height={80} width={widthDimensions} />,
    answer: [
      'Serbia',
      'Cocos (Keeling) Islands',
      'Madagascar',
      'French Southern Territories',
    ],
    correct: 3,
  },
  {
    id: 'TG',
    name: 'Togo',
    uri: <Svgs.TG height={80} width={widthDimensions} />,
    answer: ['Papua New Guinea', 'Nicaragua', 'Belarus', 'Togo'],
    correct: 3,
  },
  {
    id: 'TH',
    name: 'Thailand',
    uri: <Svgs.TH height={80} width={widthDimensions} />,
    answer: ['Pitcairn', 'Gibraltar', 'Armenia', 'Thailand'],
    correct: 3,
  },
  {
    id: 'TJ',
    name: 'Tajikistan',
    uri: <Svgs.TJ height={80} width={widthDimensions} />,
    answer: ['South Sudan', 'Macao', 'Tajikistan', 'Georgia'],
    correct: 2,
  },
  {
    id: 'TK',
    name: 'Tokelau',
    uri: <Svgs.TK height={80} width={widthDimensions} />,
    answer: [
      'Montserrat',
      'Svalbard and Jan Mayen Islands',
      'Tokelau',
      'Dominica',
    ],
    correct: 2,
  },
  {
    id: 'TL',
    name: 'Timor-Leste',
    uri: <Svgs.TL height={80} width={widthDimensions} />,
    answer: ['Saint Martin', 'Romania', 'Timor-Leste', 'Afghanistan'],
    correct: 2,
  },
  {
    id: 'TM',
    name: 'Turkmenistan',
    uri: <Svgs.TM height={80} width={widthDimensions} />,
    answer: ['Mexico', 'Turkmenistan', 'Anguilla', 'Pitcairn'],
    correct: 1,
  },
  {
    id: 'TN',
    name: 'Tunisia',
    uri: <Svgs.TN height={80} width={widthDimensions} />,
    answer: ['France', 'Isle of Man', 'Saudi Arabia', 'Tunisia'],
    correct: 3,
  },
  {
    id: 'TO',
    name: 'Tonga',
    uri: <Svgs.TO height={80} width={widthDimensions} />,
    answer: ['Papua New Guinea', 'Tonga', 'Bahrain', 'Saint Lucia'],
    correct: 1,
  },
  {
    id: 'TR',
    name: 'Turkey',
    uri: <Svgs.TR height={80} width={widthDimensions} />,
    answer: ['Scotland', 'Turkey', 'Greenland', 'Chad'],
    correct: 1,
  },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    uri: <Svgs.TT height={80} width={widthDimensions} />,
    answer: ['France', 'Trinidad and Tobago', 'Yemen', 'Cambodia'],
    correct: 1,
  },
  {
    id: 'TV',
    name: 'Tuvalu',
    uri: <Svgs.TV height={80} width={widthDimensions} />,
    answer: ['Bulgaria', 'Somalia', 'Tuvalu', 'Isle of Man'],
    correct: 2,
  },
  {
    id: 'TW',
    name: 'Taiwan (Republic of China)',
    uri: <Svgs.TW height={80} width={widthDimensions} />,
    answer: [
      'Taiwan (Republic of China)',
      'Indonesia',
      'Seychelles',
      'Germany',
    ],
    correct: 0,
  },
  {
    id: 'TZ',
    name: 'Tanzania, United Republic of',
    uri: <Svgs.TZ height={80} width={widthDimensions} />,
    answer: [
      'Tanzania, United Republic of',
      'Angola',
      'India',
      'Venezuela, Bolivarian Republic of',
    ],
    correct: 0,
  },
  {
    id: 'UA',
    name: 'Ukraine',
    uri: <Svgs.UA height={80} width={widthDimensions} />,
    answer: ['England', 'Ukraine', 'Panama', 'Sri Lanka'],
    correct: 1,
  },
  {
    id: 'UG',
    name: 'Uganda',
    uri: <Svgs.UG height={80} width={widthDimensions} />,
    answer: ['Curaçao', 'Nepal', 'Uganda', 'Croatia'],
    correct: 2,
  },
  {
    id: 'UM',
    name: 'US Minor Outlying Islands',
    uri: <Svgs.UM height={80} width={widthDimensions} />,
    answer: ['Saint Lucia', 'US Minor Outlying Islands', 'Chad', 'Algeria'],
    correct: 1,
  },
  {
    id: 'US',
    name: 'United States',
    uri: <Svgs.US height={80} width={widthDimensions} />,
    answer: ['United States', 'Rwanda', 'Chile', 'Guatemala'],
    correct: 0,
  },
  {
    id: 'UY',
    name: 'Uruguay',
    uri: <Svgs.UY height={80} width={widthDimensions} />,
    answer: ['Uruguay', 'Turkey', 'Saint Barthélemy', 'Madagascar'],
    correct: 0,
  },
  {
    id: 'UZ',
    name: 'Uzbekistan',
    uri: <Svgs.UZ height={80} width={widthDimensions} />,
    answer: ['American Samoa', 'North Macedonia', 'Uzbekistan', 'Uzbekistan'],
    correct: 3,
  },
  {
    id: 'VA',
    name: 'Holy See (Vatican City State)',
    uri: <Svgs.VA height={80} width={widthDimensions} />,
    answer: [
      'Korea, Republic of',
      'Poland',
      'Colombia',
      'Holy See (Vatican City State)',
    ],
    correct: 3,
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    uri: <Svgs.VC height={80} width={widthDimensions} />,
    answer: [
      'Japan',
      'Saint Vincent and the Grenadines',
      'Switzerland',
      'Seychelles',
    ],
    correct: 1,
  },
  {
    id: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    uri: <Svgs.VE height={80} width={widthDimensions} />,
    answer: [
      'Jersey',
      "China (People's Republic of China)",
      'Venezuela, Bolivarian Republic of',
      'Palestine',
    ],
    correct: 2,
  },
  {
    id: 'VG',
    name: 'Virgin Islands, British',
    uri: <Svgs.VG height={80} width={widthDimensions} />,
    answer: [
      'Western Sahara',
      'British Indian Ocean Territory',
      'Russian Federation',
      'Virgin Islands, British',
    ],
    correct: 3,
  },
  {
    id: 'VI',
    name: 'Virgin Islands, U.S.',
    uri: <Svgs.VI height={80} width={widthDimensions} />,
    answer: [
      'Bosnia and Herzegovina',
      'Togo',
      'Virgin Islands, U.S.',
      'Madagascar',
    ],
    correct: 2,
  },
  {
    id: 'VN',
    name: 'Vietnam',
    uri: <Svgs.VN height={80} width={widthDimensions} />,
    answer: [
      'Algeria',
      'Vietnam',
      'South Georgia and the South Sandwich Islands',
      'Senegal',
    ],
    correct: 1,
  },
  {
    id: 'VU',
    name: 'Vanuatu',
    uri: <Svgs.VU height={80} width={widthDimensions} />,
    answer: [
      'Singapore',
      'Vanuatu',
      'Guinea',
      "China (People's Republic of China)",
    ],
    correct: 1,
  },
  {
    id: 'WF',
    name: 'Wallis and Futuna Islands',
    uri: <Svgs.WF height={80} width={widthDimensions} />,
    answer: ['Serbia', 'Belize', 'Wallis and Futuna Islands', 'Lithuania'],
    correct: 2,
  },
  {
    id: 'WS',
    name: 'Samoa',
    uri: <Svgs.WS height={80} width={widthDimensions} />,
    answer: ["Côte d'Ivoire", 'Serbia', 'Samoa', 'Malta'],
    correct: 2,
  },
  {
    id: 'XK',
    name: 'Kosovo',
    uri: <Svgs.XK height={80} width={widthDimensions} />,
    answer: ['Curaçao', 'Luxembourg', 'Kosovo', 'Saudi Arabia'],
    correct: 2,
  },
  {
    id: 'YE',
    name: 'Yemen',
    uri: <Svgs.YE height={80} width={widthDimensions} />,
    answer: [
      'England',
      'Yemen',
      'Zimbabwe',
      'South Georgia and the South Sandwich Islands',
    ],
    correct: 1,
  },
  {
    id: 'YT',
    name: 'Mayotte',
    uri: <Svgs.YT height={80} width={widthDimensions} />,
    answer: ['Gambia', 'Slovakia', 'Andorra', 'Mayotte'],
    correct: 3,
  },
  {
    id: 'ZA',
    name: 'South Africa',
    uri: <Svgs.ZA height={80} width={widthDimensions} />,
    answer: [
      'South Africa',
      'American Samoa',
      'South Georgia and the South Sandwich Islands',
      'Portugal',
    ],
    correct: 0,
  },
  {
    id: 'ZM',
    name: 'Zambia',
    uri: <Svgs.ZM height={80} width={widthDimensions} />,
    answer: ['Ireland', 'Grenada', 'Wallis and Futuna Islands', 'Zambia'],
    correct: 3,
  },
  {
    id: 'ZW',
    name: 'Zimbabwe',
    uri: <Svgs.ZW height={80} width={widthDimensions} />,
    answer: ['Bolivia, Plurinational State of', 'Rwanda', 'Zimbabwe', 'Malawi'],
    correct: 2,
  },
];
